### ISSUE TITLE
error: cannot find symbol new GoogleFitPackage(MainActivity.activity)

### ISSUE THREAD

**Issue by marcusds** [StasDoskalenko/react-native-google-fit#1]
I followed the instructions for the plugin, but when I building I get:

```
MainApplication.java:29: error: cannot find symbol
                                        new GoogleFitPackage(MainActivity.activity)
```

**Comment by StasDoskalenko** [comment]
Hello, @marcusds 
> I followed the instructions for the plugin, but when I building I get:

Check your MainActivity.java:

`public class MainActivity extends ReactActivity {
 ....

    static MainActivity activity = null;
    {
        activity = this;
    }

 ...
}`

Wich React Native version do you use? If 0.41 there are could be some breaking changes. I'll update module in the nearest future.
Thanks!

**Comment by StasDoskalenko** [comment]
@marcusds version 0.1.0-beta released. Can we close this issue?
