### ISSUE TITLE
Can China use it?

### ISSUE THREAD

**Issue by TrustTheBoy** [StasDoskalenko/react-native-google-fit#10]

**Comment by StasDoskalenko** [comment]
Why not? :)

**Comment by TrustTheBoy** [comment]
@StasDoskalenko Get  on Google Healthcare data? China network access restrictions, do not know if you want to use this component?

**Comment by TrustTheBoy** [comment]
In China, Andrews devices can not use `Google Fitness`, all through the third party `App get on fitness data`

**Comment by StasDoskalenko** [comment]
@TrustTheBoy sorry, I don't know. This lib uses common google policies as well.
