### ISSUE TITLE
getDailyCalorieSamples return value not correctly

### ISSUE THREAD

**Issue by chienvu123** [StasDoskalenko/react-native-google-fit#100]
I have get steps value => 0
and I get value of calories => value = 1234.5kcal or approximate this value. I want to real value of calories for rating with step value
example: 30 steps => 100 kcal or approximate

**Comment by vaibhgupta09** [comment]
@chienvu123  can you share your getDailyCalorieSamples function

**Comment by ShaharyarMaroof** [comment]
```
  GoogleFit.authorize(options)
    .then(authResult => {
      console.log('auth successful')
      const range = {
        startDate: "2020-01-23T00:00:17.971Z", // required ISO8601Timestamp
        endDate: new Date().toISOString() // required ISO8601Timestamp
      };

      GoogleFit.getDailyStepCountSamples(range)
        .then((res) => {
          console.log('Daily steps >>> ', res)
          const countData = res.find((data) => data.source === 'com.google.android.gms:estimated_steps')
          console.log('count Data', countData)
        })
        .catch((err) => { console.warn(err) })
    })
    .catch(() => {
      console.log('auth error')
    })
```
![image](https://user-images.githubusercontent.com/10959027/72961829-48aed580-3dd4-11ea-96e6-c72503c031a3.png)

I am also facing a similar issue, Google Fit shows steps logged but, when I query it, I don't get any steps.
