### ISSUE TITLE
react-native-google-fit fails for AndroidX

### ISSUE THREAD

**Issue by saudahmed** [StasDoskalenko/react-native-google-fit#106]
I created a new react-native project using

- react-native init sample
- cd sample
- npm install
- react-native run-android

Complies correctly and runs on device perfectly but after doing the following inside sample/

- npm i react-native-google-fit
- react-native link react-native-google-fit
- react-native run-android

I get this 

Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

Started happening after June 17, 2019

https://developers.google.com/android/guides/releases

Please fix these changes in your package

**Comment by akash-rajput** [comment]
Same here

**Comment by salimsket** [comment]
So far I found that changing the `node_modules/react-native-google-fit/android/build.gradle play-service versions from + to 15.0.+ works out, because it does not depend on androidx libs.

```dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:+'
    ~compile 'com.google.android.gms:play-services-auth:+'~
    compile 'com.google.android.gms:play-services-auth:15.0.+'
    ~compile 'com.google.android.gms:play-services-fitness:+'~
    compile 'com.google.android.gms:play-services-fitness:15.0.+'
}```

**Comment by HiroNonoyama** [comment]
In my case, this also work.
```
com.google.android.gms:play-services-auth:16.0.1
com.google.android.gms:play-services-fitness:16.0.1
```

**Comment by antoinedelp** [comment]
You can also modify your android/app/build.gradle by excluding react-native-google-fit call to android-gms:

```
dependencies {
    implementation (project(':react-native-google-fit'), {
    exclude group: "com.google.android.gms"
    })
}
```

@StasDoskalenko, you should probably release a fix in order to call a specific com.google.android.gms version :)

**Comment by cddin** [comment]
implementation(project(":react-native-google-fit"),  {
        exclude group: "com.google.android.gms"
    })`
implementation ("com.google.android.gms:play-services-auth:16.0.1"){
        force = true
    }
    implementation ("com.google.android.gms:play-services-fitness:16.0.1"){
        force = true
    }`

**Comment by cddin** [comment]
I exclude and force to use specific version.. and its work

implementation(project(":react-native-google-fit"), {
exclude group: "com.google.android.gms"
})
implementation ("com.google.android.gms:play-services-auth:16.0.1"){
force = true
}
implementation ("com.google.android.gms:play-services-fitness:16.0.1"){
force = true
}`

**Comment by akash-rajput** [comment]
After the new release: `0.9.14` you can simply override the package's gplayservices versions.
In your `app/build.gradle` 
```
rootProject.ext.set("authVersion", "16.0.1")
rootProject.ext.set("fitnessVersion", "16.0.1")
```

**Comment by saudahmed** [comment]
@akash-rajput 

under which lines do you set

rootProject.ext.set("authVersion", "16.0.1")
rootProject.ext.set("fitnessVersion", "16.0.1")

**Comment by vaibsshukla** [comment]
> @akash-rajput
> 
> under which lines do you set
> 
> rootProject.ext.set("authVersion", "16.0.1")
> rootProject.ext.set("fitnessVersion", "16.0.1")

**In app dependencies**


dependencies {
    implementation project(':react-native-google-fit'), {
        exclude group: "com.google.android.gms"
    }
    implementation project(':react-native-toast-native')
    implementation project(':react-native-image-picker')
    implementation project(':realm')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-svg')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation project(':react-native-google-signin')
    implementation project(':react-native-firebase')
    implementation project(':react-native-fbsdk')
    implementation ("com.google.android.gms:play-services-auth:16.0.1"){
        force = true
    }
    implementation ("com.google.android.gms:play-services-fitness:16.0.1"){
        force = true
    }

//    implementation project(':react-native-linear-gradient')*/


    implementation project(':react-native-gesture-handler')
    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
    implementation "com.google.firebase:firebase-auth:17.0.0"
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"
//
//
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation('com.crashlytics.sdk.android:crashlytics:2.10.1@aar') {
        transitive = true;
    }
    rootProject.ext.set("authVersion", "16.0.1")
    rootProject.ext.set("fitnessVersion", "16.0.1")
}
