### ISSUE TITLE
getActivitySamples() not working says: There is no any distance data for this period.

### ISSUE THREAD

**Issue by akash-rajput** [StasDoskalenko/react-native-google-fit#108]
I've logged various activities with distance, calories & steps in Google Fit app. While trying to get activity sample using authorised `GoogleFit` client: 
```
console.warn(startDate, endDateToQuery);

    let options = {
      startDate: new Date(2019, 6, 20).valueOf(), // simply outputs the number of milliseconds since the Unix Epoch
      endDate: new Date(2019, 6, 21, 15, 20, 20).valueOf(), // also doesn't work for: `Date(2019, 6, 21)`
    };

    const result = await GoogleFit.getActivitySamples(options, (isError, result) => {
      console.warn(isError, result);
    });
```

The warn gives prints `There is no any distance data for this period.`

**Comment by Tobertet** [comment]
I'm having the same issue.

**Comment by Tobertet** [comment]
Finally I've been able to receive some data. Just make sure you are requesting both body and location information on authentication:

GoogleFit.authorize({
      scopes: [Scopes.FITNESS_ACTIVITY_READ, Scopes.FITNESS_LOCATION_READ],
    });

**Comment by ShaharyarMaroof** [comment]
@Tobertet thanks for posting this, got me out of a sticky situation!

**Comment by ruanlinos** [comment]
> Finally I've been able to receive some data. Just make sure you are requesting both body and location information on authentication:
> 
> GoogleFit.authorize({
> scopes: [Scopes.FITNESS_ACTIVITY_READ, Scopes.FITNESS_LOCATION_READ],
> });

It worked perfectly here, I think it's interesting that it's in the readme, it will help many people with the same problem.

**Comment by rameshvishnoi90904** [comment]
Thanks @Tobertet. Works like charm
