### ISSUE TITLE
react-native-google-fit fails in RN 60

### ISSUE THREAD

**Issue by spasecadet** [StasDoskalenko/react-native-google-fit#109]
I created a new project with react-native 0.60.0-rc.1 which now does auto linking and implements AndroidX.  It is still a bit buggy but I've got a working app in both android and ios.  After doing `yarn add react-native-google-fit` and trying to run the app in android I've had a number of problems.  

On the AndroidX side all instances of 
```
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
```
 needed to be changed to 
```
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
```
Additionally, the GoogleFitPackage is now added to a dynamically created file `android/app/build/generated/rncli/src/main/java/com/facebok/react/PackageList.java` but is missing the arg `BuildConfig.APPLICATION_ID`.  

*PackageList.java*
```
../

public ArrayList<ReactPackage> getPackages() {
  return new ArrayList<>(Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new ReactNativeFirebaseAppPackage(),new ReactNativeFirebaseAuthPackage(),new RNGestureHandlerPackage(),new GoogleFitPackage()
  ));
}
```

*MainApplication.java*
```
@Override
  protected List<ReactPackage> getPackages() {
    @SuppressWarnings("UnnecessaryLocalVariable")
    List<ReactPackage> packages = new PackageList(this).getPackages();
    // Packages that cannot be autolinked yet can be added manually here, for example:
    // packages.add(new MyReactNativePackage());
    return packages;
  }
```

Unfortunately if I try manually adding `new GoogleFitPackage(BuildConfig.APPLICATION_ID)` to getPackages in MainApplication it is overridden by PackageList.  

No issues with `react-native run-ios` - though all I've done is add `import GoogleFit, { Scopes } from 'react-native-google-fit';`.

**Comment by plahteenlahti** [comment]
@spasecadet I was able to make this work by adding the library as an exception to react-native.config.js, as explained here https://github.com/react-native-community/cli/blob/master/docs/autolinking.md 

This way the library is not autolinked and PackageList doesn't override the package.

**Comment by vaibsshukla** [comment]
> @spasecadet I was able to make this work by adding the library as an exception to react-native.config.js, as explained here https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
> 
> This way the library is not autolinked and PackageList doesn't override the package.

@spasecadet  Did this worked for you?

**Comment by StasDoskalenko** [comment]
Hey guys. If some1 has a working solution - please share, I'll document it. Thanks!

**Comment by spasecadet** [comment]
@plahteenlahti thanks for the suggestion, I haven't got it working yet for myself. I've tired:
```
yarn add react-native-google-fit
react-native unlink react-native-google-fit
```
Then added a react-native.config.js file inside ./node_modules/react-native-google-fit with this code:
```
// react-native.config.js
module.exports = {
  dependencies: {
    'react-native-google-fit': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};
```
Then added to MainApplication.java
`packages.add(new GoogleFitPackage(BuildConfig.APPLICATION_ID));`
Then
`react-native link react-native-google-fit`

I also tried doing this without the `react-native link` step and just used the manual installation for google fit and that hasn't worked either, I still get the same error in PackageList.java

```
error: constructor GoogleFitPackage in class GoogleFitPackage cannot be applied to given types;
      new GoogleFitPackage(),
      ^
  required: String
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
```

What steps did you follow to make it work?

**Comment by spasecadet** [comment]
Ok I misunderstood the react-native.config.js file.  I added that file to the root of my application with the same code as above and it appears to be working now.  However, I would not consider this a long-term solution since it doesn't really take advantage of autolinking and requires extra steps to get this working.  I'm not clear on whether or not settings can be configured within this package that enable the use of PackageList.java.  I posted a question here: https://github.com/react-native-community/cli/issues/599.

**Comment by spasecadet** [comment]
I got a response on my question above (https://github.com/react-native-community/cli/issues/599) and the solution that allows autolinking to work is (first remove `react-native-google-fit` if it is already installed) to add a react-native.config.js file to your app root, with these contents:

```
module.exports = {
  dependencies: {
    'react-native-google-fit': {
      platforms: {
        android: {
          packageInstance: "new GoogleFitPackage(BuildConfig.APPLICATION_ID)",
        },
      },
    },
  },
};

```
save

Then 
`yarn add react-native-google-fit`

This allows autolinking to work and PackageList.java instantiates the package the correct way.  This solution should ultimately be included in the package itself and I've submitted a [PR](https://github.com/StasDoskalenko/react-native-google-fit/pull/116) to add it.  Note, I have NOT tested this for RN <60.  I _suspect_ it will not cause any problems because I believe using react-native.config.js is new to RN 60, but again, this is untested.

**Comment by spasecadet** [comment]
@StasDoskalenko This package still needs to be updated to AndroidX which includes changing all of these: 
```
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
```
to
```
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
```
in 
- CalorieHistory.java
- DistanceHistory.java
- GoogleFitManager.java
- StepHistory.java
- StepCounter.java
- StepSensor.java
- RecordingApi.java
- ActivityHistory.java

However that WILL cause RN <60 to break so for now users can install jetifier and run `npx jetify` after installing react-native-google-fit for RN >=60.

**Comment by StasDoskalenko** [comment]
@spasecadet sure. thank you for this

**Comment by janpe** [comment]
Any progress on this?

**Comment by dkwl93** [comment]
Is there any update on this? I've followed the steps in the description but my builds in appcenter are still failing. I'm on react-native 0.60.4 and assumed jetifier would run automatically (which it does I think). However, I was still getting build issues so I added `npx jetifier` to the `postinstall` script in my package.json and it is still failing

**Comment by dkwl93** [comment]
Sorry, I managed to resolve the builds by trying various different solutions
* Added `npx jetifier` to the postinstall
* Change tooling version of android
```
buildscript {
    ext {
        buildToolsVersion = "29.0.0"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
    }
}
```
