### ISSUE TITLE
How to use getDailyCalorieSamples????

### ISSUE THREAD

**Issue by vaibhgupta09** [StasDoskalenko/react-native-google-fit#111]

**Comment by Tobertet** [comment]
Library is not well documented, you shouldn't use milliseconds. I used it like this:

const options = {
      startDate: moment().startOf('day').format(),
      endDate: moment().format(),
    };
GoogleFit.getDailyCalorieSamples(options, (err, res) => {
          if (err) {
            reject(err);
          } else {
            resolve(res);
          }
        });

**Comment by jguix** [comment]
Actually, it is not using milliseconds. You can check the file `index.android.js` where it is picking the input params to call the Java library:

```
getDailyCalorieSamples(options, callback) {
    const basalCalculation = options.basalCalculation !== false
    const startDate = Date.parse(options.startDate)
    const endDate = Date.parse(options.endDate)
    googleFit.getDailyCalorieSamples(
      startDate,
      endDate,
      basalCalculation,
      msg => {
        callback(msg, false)
      },
      res => {
        if (res.length > 0) {
          callback(false, prepareResponse(res, 'calorie'))
        } else {
          callback('There is no any calorie data for this period', false)
        }
      }
    )
  }
```

Where `Date.parse(options.startDate)` implies that options.startDate is a `string`.

I just updated the documentation for this and other methods. You can check the README.
