### ISSUE TITLE
observeSteps doesn't trigger callback

### ISSUE THREAD

**Issue by Karpengold** [StasDoskalenko/react-native-google-fit#117]
I'm trying to count steps and show them on screen

```
 GoogleFit.startRecording(response1 => {
    if (response1.type != "steps") return;
    GoogleFit.observeSteps(response2=> {
      console.log(response2);
      setSteps(response2);
    });
  });
```

But steps doesn't change and  also  here

```
GoogleFit.getDailyStepCountSamples(options).then(res => {
    console.log("Daily steps >>> ", res);
  });
```

Steps arrays are  empty 

What I need to do to start counting steps?

**Comment by milad1367** [comment]
get daily is ok but observer steps don't work!
if you want to test daily steps you can add steps in google fits app in your phone or simulator, it works.
but I can not use GoogleFit.observeSteps !!

**Comment by nojas01** [comment]
@milad1367 @Karpengold  @StasDoskalenko see the answer in : https://github.com/StasDoskalenko/react-native-google-fit/issues/119#issuecomment-565010555 
In the file StepCounter.java, line 116 the StepChangedEvent is sent when the DataType.TYPE_STEP_COUNT_CUMULATIVE is triggerd. However I haven't seen this event triggerd in logcat. If you change the type to TYPE_STEP_COUNT_DELTA, the observeSteps will work. the changed function will look like:
`
// StepCounter.java line:116 if(type.equals(DataType.TYPE_STEP_COUNT_DELTA)) { WritableMap map = Arguments.createMap(); map.putDouble("steps", value.asInt()); sendEvent(this.mReactContext, "StepChangedEvent", map); }
`

**Comment by StasDoskalenko** [comment]
@Karpengold @nojas01 @milad1367 thanks! Fixed
