### ISSUE TITLE
GoogleFit.authorize is ok in android emulator but has problem in real device! 

### ISSUE THREAD

**Issue by milad1367** [StasDoskalenko/react-native-google-fit#118]
I use the example code and everything is ok in emulator but I can not authorize in a real device,
**in emulator:**
![Screen Shot 2019-08-07 at 11 18 56 PM](https://user-images.githubusercontent.com/15375991/62649823-c6883d00-b96a-11e9-8c6a-1e775079f046.png)

**on the phone :**
![photo_2019-08-07_23-28-11](https://user-images.githubusercontent.com/15375991/62649987-1535d700-b96b-11e9-8815-f2437ed2559b.jpg)

> {
  "name": "",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-circular-progress": "1.1.0",
    "react-native-easy-toast": "1.2.0",
    "react-native-elements": "1.1.0",
    "react-native-gesture-handler": "1.3.0",
    "react-native-google-fit": "^0.9.15",
    "react-native-image-picker": "0.28",
    "react-native-keyboard-aware-scroll-view": "0.8.0",
    "react-native-keychain": "3.1.3",
    "react-native-progress-circle": "2.0.1",
    "react-native-svg": "9.5.1",
    "react-native-vector-icons": "6.5.0",
    "react-navigation": "3.11.0",
    "react-redux": "7.1.0",
    "redux": "4.0.1"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/runtime": "7.4.5",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "assets/fonts"
    ]
  }
}

**Comment by milad1367** [comment]
I use Release certificate instead of debugging certificate and problems solved.

**Comment by jakallergis** [comment]
I have problems with `autorize` as well. I keep getting **_"Autorisation cancelled"_** as soon as I select my Google account. The problem for me is for both simulators and real devices. Also I have created credentials in the Google Console for both the debug keystore and the release keystore.
I've also created the consent screen mentioned there.

What can I do?
