### ISSUE TITLE
observer step counter not work!

### ISSUE THREAD

**Issue by milad1367** [StasDoskalenko/react-native-google-fit#119]
everything is ok but step counter not work!

![Screen Shot 2019-08-11 at 10 46 50 AM](https://user-images.githubusercontent.com/15375991/62830537-e26b3780-bc25-11e9-855d-a737bd2e0e5d.png)

**Comment by nojas01** [comment]
In the file StepCounter.java, line 116 the StepChangedEvent is sent when the DataType.TYPE_STEP_COUNT_CUMULATIVE is triggerd. However I haven't seen this event triggerd in logcat. If you change the type to TYPE_STEP_COUNT_DELTA, the observeSteps will work. the changed function will look like: 
`  
// StepCounter.java line:116
if(type.equals(DataType.TYPE_STEP_COUNT_DELTA)) {
                WritableMap map = Arguments.createMap();
                map.putDouble("steps", value.asInt());
                sendEvent(this.mReactContext, "StepChangedEvent", map);
            }
`

**Comment by StasDoskalenko** [comment]
@nojas01 fixed, thanks!

**Comment by milad1367** [comment]
@nojas01  Thanks, it's worked
