### ISSUE TITLE
burned calories

### ISSUE THREAD

**Issue by nehvaleem** [StasDoskalenko/react-native-google-fit#12]
Hi! 
First of all let me thanks for your great work! 

I am wondering if it possible to obtain burned calories info from google fit? If so - how? If not - would you consider adding it?

**Comment by StasDoskalenko** [comment]
Hi, @nehvaleem ! Going to investigate such kind of Data Source. Thanks for the feedback!

**Comment by StasDoskalenko** [comment]
https://github.com/StasDoskalenko/react-native-google-fit/projects/1#card-4397564

**Comment by nullpointer07** [comment]
gave a PR for same https://github.com/StasDoskalenko/react-native-google-fit/pull/23

**Comment by StasDoskalenko** [comment]
@nullpointer07 thanks! NPM published

@nehvaleem could you please check this out?
