### ISSUE TITLE
Authorisation Prompt freezing after selecting Google-Account

### ISSUE THREAD

**Issue by c-goettert** [StasDoskalenko/react-native-google-fit#120]
I installed the library as described in the documentation and also created a client-id for my package. I think my setup is generally supposed to be right, because I could successfully authenticate to google fit on my emulator (Android 9.0) and on my Samsung S6 (Android 7.0).

But when I run my App on my Nexus Phone (Android 8.1.0), I somehow can't authenticate. After selecting my Google-Account, the authorisation-promt is kind of freezing and only shows a loading indicator:
![Screenshot_20190814-171950](https://user-images.githubusercontent.com/7591624/63034268-4a857c00-beb9-11e9-88db-fbbb6a0d5b0e.png)

I can't find any helpful debug information, because the promise just doesn't seem to resovle. I also doesn't reject / throw any errors. It just doesn't do anything. Also in logcat I couldn't find any related logs / warnings. I tried using `client_secrets` for debug and release, both didn't help. Does anyone have an idea what could be the issue here, or how to debug further?

I am using RN Version 0.59.5 with the latest version of this package (0.9.14).
Thanks for your help!

**Comment by c-goettert** [comment]
Update: Today I found out this issues doesn't seem to be related with my phone, but with my google accout. I can also authorize on my phone when i'm using my test-account, but it freezes when I'm trying to auth with my private google accout. Closing this issue because I guess it's more a OAuth / Google problem and not related to this library. Still, any comments and ideas how to fix it would be welcome :)

**Comment by c-goettert** [comment]
In case this might help someone else:
The problem was indeed related to my private google account. It was because I was still using my "@googlemail.com" account suffix (because it was the official suffix in germany in the past). I swichted my account to "@gmail.com" and now it is working fine.

**Comment by jakallergis** [comment]
I have problems with `autorize` as well. I keep getting **_"Autorisation cancelled"_** as soon as I select my Google account. The problem for me is for both simulators and real devices. Also I have created credentials in the Google Console for both the debug keystore and the release keystore.
I've also created the consent screen mentioned there.

What can I do?

**Comment by Aurangempire** [comment]
Hi there, I am facing the same issue as the above screenshot, dialog is keep loading and loading. I am using my @gmail.com account but still having this issue, still not fixed. Any help would be appreciated.

**Comment by nabati** [comment]
I am seeing the same behaviour.
