### ISSUE TITLE
GoogleFit.getHeartRateSamples() return only 5 objects

### ISSUE THREAD

**Issue by PORS911** [StasDoskalenko/react-native-google-fit#121]
Hi @StasDoskalenko ,
Your package is so great, It's helped me a lot, but I don't know why getHeartRateSamples() function didn't return more result for me.

Please help !!!!
Here is my code...
`let options = {
      startDate: startDate,
      endDate: Moment().toISOString()
    }

// Get heart rate
GoogleFit.getHeartRateSamples(options, (err, results) => {
          if (err) {
            return resolve()
          } else {
            console.log('heart', results)
            return resolve(results)
          }
        })
`
Thanks

**Comment by vamvoukas** [comment]
Any news?

**Comment by jasonpaulos** [comment]
I am having the same problem, it looks like it's because of this line: https://github.com/StasDoskalenko/react-native-google-fit/blob/8bcd5bf39669242db5a48e5c6429727e167ec27f/android/src/main/java/com/reactnative/googlefit/HeartrateHistory.java#L75

**Comment by lambui09** [comment]
setLimit must always be passed to right? I tried not to transmit data but it did not return. If I want to get all records of 2 months, is that possible?
