### ISSUE TITLE
Not able to build RN project after installing react-native-google-fit. 

### ISSUE THREAD

**Issue by anshulsingh2403** [StasDoskalenko/react-native-google-fit#122]
I m on following versions - 
```
{
  "react-native": "0.59.3",
  "react": "16.8.3",
  "react-native-google-fit": "0.9.15"
}
```

_**can someone please help me.**_

**Comment by anshul12** [comment]
can someone please help me.

**Comment by StasDoskalenko** [comment]
Please share a build log

**Comment by anshul12** [comment]
Hi @StasDoskalenko First of all, thanks for the response.
I am sharing details here.
FYI, my app was building perfectly so after this react-native-google-fit I am getting this error.

First i got this error - 

<img width="1458" alt="Screenshot 2019-09-17 at 1 47 01 PM" src="https://user-images.githubusercontent.com/2108503/65024463-90b77a80-d952-11e9-897c-0b2f6b7dff4f.png">

To fix this, I did this change - 
<img width="450" alt="Screenshot 2019-09-17 at 1 48 07 PM" src="https://user-images.githubusercontent.com/2108503/65024497-9d3bd300-d952-11e9-8db6-3e263994c854.png">


Now I m getting this error - 

<img width="1591" alt="Screenshot 2019-09-17 at 1 49 57 PM" src="https://user-images.githubusercontent.com/2108503/65024514-a7f66800-d952-11e9-88d3-d9d6fb064d9a.png">

When I searched on google for this error - "error: cannot access zzbfm rmI.putExtra"
I got solution as  
`To solve this, please update your Play Service dependecy to the latest version like this`
So upgraded `com.google.android.gms` and `com.google.firebase` to 16.+ and 15.+ respectively. 
<img width="1070" alt="Screenshot 2019-09-17 at 2 07 32 PM" src="https://user-images.githubusercontent.com/2108503/65025542-88f8d580-d954-11e9-8aeb-1487fcc172b7.png">
When I tried to fix this - I was asked to add 
```
android.enableJetifier=true
android.useAndroidX=true
```
But this has given me
<img width="1602" alt="Screenshot 2019-09-17 at 2 12 29 PM" src="https://user-images.githubusercontent.com/2108503/65025941-366be900-d955-11e9-84c7-82e4284f3f06.png">
And it's gone.
Now, I am asked to migrate to android X which I don't want.
Can u please help here. It's 2-3 days, I am hanged here.

**Comment by anshul12** [comment]
@StasDoskalenko Can I get help. Still not able to figure out.

**Comment by rantoinne** [comment]
> Hi @StasDoskalenko First of all, thanks for the response.
> I am sharing details here.
> FYI, my app was building perfectly so after this react-native-google-fit I am getting this error.
> 
> First i got this error -
> 
> <img alt="Screenshot 2019-09-17 at 1 47 01 PM" width="1458" src="https://user-images.githubusercontent.com/2108503/65024463-90b77a80-d952-11e9-897c-0b2f6b7dff4f.png">
> 
> To fix this, I did this change -
> <img alt="Screenshot 2019-09-17 at 1 48 07 PM" width="450" src="https://user-images.githubusercontent.com/2108503/65024497-9d3bd300-d952-11e9-8db6-3e263994c854.png">
> 
> Now I m getting this error -
> 
> <img alt="Screenshot 2019-09-17 at 1 49 57 PM" width="1591" src="https://user-images.githubusercontent.com/2108503/65024514-a7f66800-d952-11e9-88d3-d9d6fb064d9a.png">
> 
> When I searched on google for this error - "error: cannot access zzbfm rmI.putExtra"
> I got solution as
> `To solve this, please update your Play Service dependecy to the latest version like this`
> So upgraded `com.google.android.gms` and `com.google.firebase` to 16.+ and 15.+ respectively.
> <img alt="Screenshot 2019-09-17 at 2 07 32 PM" width="1070" src="https://user-images.githubusercontent.com/2108503/65025542-88f8d580-d954-11e9-8aeb-1487fcc172b7.png">
> When I tried to fix this - I was asked to add
> 
> ```
> android.enableJetifier=true
> android.useAndroidX=true
> ```
> 
> But this has given me
> <img alt="Screenshot 2019-09-17 at 2 12 29 PM" width="1602" src="https://user-images.githubusercontent.com/2108503/65025941-366be900-d955-11e9-84c7-82e4284f3f06.png">
> And it's gone.
> Now, I am asked to migrate to android X which I don't want.
> Can u please help here. It's 2-3 days, I am hanged here.

@anshul12 what is the version of react-native you are using?

**Comment by mifi** [comment]
Same problem here, RN 0.59.10

**Comment by anshul12** [comment]
@rantoinne It's mentioned on top - RN : 0.59.3

**Comment by anshul12** [comment]
@StasDoskalenko Any update ?

**Comment by a37803464** [comment]
Same problem here, RN 0.55.4，Has anyone solved it yet？

**Comment by mifi** [comment]
I "solved" by taking the plunge and upgrading to 0.60

**Comment by rameshvishnoi90904** [comment]
Any updates on this?

**Comment by hmazer** [comment]
running npx jetify before build fixed it for me.
