### ISSUE TITLE
Any plans to add custom workout data?

### ISSUE THREAD

**Issue by SergiOnGit** [StasDoskalenko/react-native-google-fit#127]
@StasDoskalenko I wonder if you play to add custom workout data? I mean syncing workout with app title, app icon, workout name, workout time and burned calories for example.

**Comment by StasDoskalenko** [comment]
There is a PR, but we need to clean this up.
https://github.com/StasDoskalenko/react-native-google-fit/pull/85

**Comment by SergiOnGit** [comment]
Really waiting for this feature

**Comment by dmic89** [comment]
@StasDoskalenko are there any updates when it will be done?

**Comment by Nesh108** [comment]
Also looking forward for this feature to be merged!
