### ISSUE TITLE
Getting error - {"message": "Authorization cancelled", "success": false}

### ISSUE THREAD

**Issue by akiladevinda** [StasDoskalenko/react-native-google-fit#128]
Please provide me working solution for this issue. I have connected my application with Google Console using SHA key. I have do all the need things according to documentation. But every time I trigger the GoogleFit.authorize() method I'm getting the error  {"message": "Authorization cancelled", "success": false} 
How to work with client id which was taken from console ? I haven't added it to android project.
![Google Fit](https://user-images.githubusercontent.com/20571997/67667500-f9533780-f993-11e9-93ff-df6d551240cf.png)

**Comment by akiladevinda** [comment]
Hey all,
I fixed the issue.. Issue is with debug.keystore file. If you encounted this issue please remove your keystore file and try to use new one

**Comment by jakallergis** [comment]
I have problems with autorize as well. I keep getting "Autorisation cancelled" as soon as I select my Google account. The problem for me is for both simulators and real devices. Also I have created credentials in the Google Console for both the debug keystore and the release keystore.
I've also created the consent screen mentioned there.

What can I do?

**Comment by Vivek205** [comment]
How to use a new keystore file

**Comment by jayampathiadhikari** [comment]
For those who are still having the problem (for debug):  
- create an Oauth 2.0 Client ID with your sha1 value which is USED in the debug.keystore
- to create OAuth client  use this: https://developers.google.com/fit/android/get-api-key
- to get sha1 value use this in cmd :  keytool -list -v -keystore "PATH TO YOUR PROJECT\android\app\debug.keystore" -alias androiddebugkey -storepass android -keypass android 
- if you don't have an debug.keystore create one first.
