### ISSUE TITLE
Steps not accurate

### ISSUE THREAD

**Issue by abhikulshrestha22** [StasDoskalenko/react-native-google-fit#129]
**Daily Steps are not accurate . It is differing with the google fit steps by 10 or 15.** 

I tried the following code to get the daily steps of 5th Nov.
` const dateRange = {
            startDate: '2019-11-05T00:00:00.000Z',
            endDate: '2019-11-06T00:00:00.000Z'
          };

  GoogleFit.getDailyStepCountSamples(dateRange)
            .then((res) => {
 console.log(res)
})`

I got the response such as 

`[
  { source: "com.google.android.gms:estimated_steps", steps: [
    {
      "date":"2019-11-05","value":2370
    }
    ]
  },
  { source: "com.google.android.gms:merge_step_deltas", steps: [ ]
  },
  { source: "com.xiaomi.hm.health", steps: [] }
];`

where as in google fir, it shows steps as 2380.

**Comment by Yuvi7447** [comment]
@abhikulshrestha22 I am facing the same issue, I guess @StasDoskalenko  would have a better explanation to it, if something is missed in configuration.

**Comment by aboveyunhai** [comment]
@abhikulshrestha22  This issue refers to https://developers.google.com/fit/faq#get-step-count. 
There is also a unusual situation where if a set of data has something like 
{  startDate: 01/02 23:23 , endDate: 01/03 00:23, step: 30  } from api. 
The current code will add the step into 01/02 but it seems like google will add those step based on the `endDate`. I attempt to fix both. The Recording API in use is deprecated also (not going to touch it as long as it works).

**Comment by aboveyunhai** [comment]
Since now you can pass time interval to further adjust the accuracy, this problem is not longer existed.
