### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by DeevD** [StasDoskalenko/react-native-google-fit#131]
I test authorize() in xioami device . Google account dialog is never show and message got authorization canceled. But other device is working fine.

Mi CC9 
google service installed

**Comment by Vivek205** [comment]
Same issue for me in the release APK.. 
Have you added the client_secret of the googleFit?

**Comment by chamile** [comment]
> Same issue for me in the release APK..
> Have you added the client_secret of the googleFit?

 to whare should it add? please elaborate it please?

**Comment by Pankti16** [comment]
Yes, where to add client_secret?
