### ISSUE TITLE
How to check if already authorized or not - API methods are not working

### ISSUE THREAD

**Issue by akiladevinda** [StasDoskalenko/react-native-google-fit#133]
How to check the google fit is already authorized or not ? Given isEnabled(callback) function returns false everytime. I want to render separate view if already authorized

**Comment by ShaharyarMaroof** [comment]
@akiladevinda Any luck on figuring this out?

**Comment by akiladevinda** [comment]
@ShaharyarMaroof  not yet buddy :(  Each and every time i need to call authorized function to check

**Comment by ShaharyarMaroof** [comment]
@akiladevinda but won't the prompt the user every time the authorized function is called?

**Comment by akiladevinda** [comment]
@ShaharyarMaroof  Yes ! We need to check authorized function every time screen renders inside componentDidMount.. Anyhow if we can make isEnable function working we can work well..Unless this authorized function is little bit slow

**Comment by jacquerie** [comment]
If you are using the JavaScript API then the boolean `GoogleFit.isAuthorized` should be what you want. If instead you're using TypeScript you can use this simple patch: https://github.com/StasDoskalenko/react-native-google-fit/pull/135

**Comment by akiladevinda** [comment]
@jacquerie  In the documentation we can't find GoogleFit.isAuthorized function example ?

**Comment by jacquerie** [comment]
This is indeed undocumented. I'm referring to this boolean: https://github.com/StasDoskalenko/react-native-google-fit/blob/cc7ee0b393744b6d28e8bede8bb2e952cc8893df/index.android.js#L11 and this function:https://github.com/StasDoskalenko/react-native-google-fit/blob/cc7ee0b393744b6d28e8bede8bb2e952cc8893df/index.android.js#L46-L49

**Comment by anija** [comment]
`GoogleFit.isAuthorized` is always false when the app starts.

**Comment by StasDoskalenko** [comment]
Added to Readme
