### ISSUE TITLE
invalid end time exception thrown in getDailyStepCountSamples

### ISSUE THREAD

**Issue by ShaharyarMaroof** [StasDoskalenko/react-native-google-fit#136]
I am trying to cal getDailyStepCountSamples() with the following code.

This is the data I'm sending to the function to fetch steps
```
const params = {
startDate: "2020-01-20T00:00:00.000Z",
endDate: "2020-01-20T23:59:59.999Z"
};
```

```
const options = {
  startDate: moment(startDate).toISOString(),
  endDate: moment(endDate).toISOString()
};
console.log('options', options)
const result = await GoogleFit.getDailyStepCountSamples(options)
const estimatedSteps = find(propEq('source', 'com.google.android.gms:estimated_steps'), result)
```
But I get the error invalid end time with the number of milliseconds shown. @StasDoskalenko any idea what is the issue here?

**Comment by ShaharyarMaroof** [comment]
![image](https://user-images.githubusercontent.com/10959027/72732390-6b17d780-3bb7-11ea-889a-b88a03375949.png)

**Comment by ShaharyarMaroof** [comment]
```    
const options = {
      startDate: "2020-01-20T00:00:17.971Z", // required ISO8601Timestamp
      endDate: new Date().toISOString() // required ISO8601Timestamp
    };
```
I have used the date and time format from the example as well. but still getting the same error

**Comment by shayanea** [comment]
Same here!

**Comment by ShaharyarMaroof** [comment]
@shayanea  I found out that the exception occurs if
1. the start and end date are the same
2. the start date is after the end date
I had to handle the check before passing the dates to the lib. Hope this helps.

**Comment by surndraraj3** [comment]
@ShaharyarMaroof  I am getting the same issue, I have to get records for a single day in this scenario start and end date will be the same. Can you help with your sample code of dates passing

**Comment by aboveyunhai** [comment]
Get the start of day and end of day if you want to get data from the same date. Or pass specific time span by yourself
Helpful info: https://stackoverflow.com/questions/8636617/how-to-get-start-and-end-of-day-in-javascript
