### ISSUE TITLE
Device is always null 

### ISSUE THREAD

**Issue by winardis** [StasDoskalenko/react-native-google-fit#138]
Hi does anyone know why the device is always returning null, or am i missing something with my code
i am able to get the step counts per day but i am unable to retrieve the source of the steps

`const options = {
                        startDate: `${Helper.prev6Days()}T00:00:00.971Z`, // required
                        endDate: Helper.isoString(),
                    };

                    GoogleFit.getDailyStepCountSamples(options).then((res) => {
                        res.forEach(element => {
                            if (element.source.includes('estimated_steps')) {
                                this.sendSteps(element.steps, GOOGLEFIT);
                            }
                        });

                        GoogleFit.disconnect();
                    }).catch((err) => {
                        console.warn(err)
                    })`
![Screen Shot 2020-02-06 at 11 57 13 AM](https://user-images.githubusercontent.com/48976564/73907354-977e6400-48d8-11ea-94d9-3f1c41a8e0d8.png)

**Comment by aboveyunhai** [comment]
It seems like the code existed for some legacy reasons, it should be always null based on the current code implementation. There is no methods to assign the device info.
