### ISSUE TITLE
Retrieving sleep data from react-native-google-fit

### ISSUE THREAD

**Issue by narayanrahulv** [StasDoskalenko/react-native-google-fit#139]
I have integrated sleep for android with google fit and am able to successfully see sleep data under the journal section in google fit. Does your library provide a good way to retrieve sleep data integrated into google fit in this manner ? I tried using observeHistory and getActivitySamples methods but neither seem to be returning sleep data.

**Comment by JoelOnGithub** [comment]
Hi I am also wondering how to gather sleep data!

**Comment by mochi08** [comment]
I am wondering as well.  If it is not implemented, is there any plan to add the function in the near future?

**Comment by aboveyunhai** [comment]
This feature is included in latest version
