### ISSUE TITLE
Choose Account for *app Pop up: persists even when selected account?

### ISSUE THREAD

**Issue by kh1990** [StasDoskalenko/react-native-google-fit#14]
Anyone else getting this bug?

The choose google account pops up at the start of the app and when the account is selected, it doesn't prompt to the permission screen consistently...

**Comment by StasDoskalenko** [comment]
@kh1990 it's not an issue. Just follow official/or unofficial Google Play API installation instructions and all should be fine. 
e.g. follow first three steps from here:
https://developers.google.com/fit/android/get-started

**Comment by kh1990** [comment]
Hmm i did follow those steps. Like I said in the initial post, the permission screen doesn't seem to display consistently, only some devices had the issue...any ideas? 

I.e. on my test device xiao mi 5 running 7.0 it works fine but on my friend's pixel the repeat choose account screen persists...

**Comment by kh1990** [comment]
Ahh I think I figured it out, I think Im missing the release certificate. Since the debug version works flawlessly yet the release versions seem to be getting stuck on the choose account page. Testing out this hypothesis now.
