### ISSUE TITLE
getActivitySamples running in background freeze the app

### ISSUE THREAD

**Issue by anija** [StasDoskalenko/react-native-google-fit#140]
I have a function running in background when the app starts, that fetch the user activities from GoogleFit. startDate is set as 30 days ago, endDate is set as now.

```
return new Promise((resolve, reject) => {
    return GoogleFit.authorize({ scopes: [ Scopes.FITNESS_ACTIVITY_READ, Scopes.FITNESS_BODY_READ_WRITE, Scopes.FITNESS_LOCATION_READ ] })
      .then(async () => {
        const options = {
          startDate,
          endDate,
        };
        return GoogleFit.getActivitySamples(options, (err, res) => {
          if (err)  reject(err);
          else      resolve(res);
        });
      }).catch(err => {
        reject(err);
      })
  });
```

While the authorization process is fast, when the activities are a lot (in my case, 872) the getActivitySamples takes a lot of time to return the callback. The speed itself is not a problem, is the main reason why i'm running the task in background, but the problem is that while the getActivitySamples is executed, the app is freezed.
I've checked the implementation, moved the function elsewere in the app without any return or other things, but the app still freeze. Nothing is clickable.
And, also, after a lot of waiting and app freezed, when i'm in debug mode on the emulator i got this warning:
`Debugger and device times are drifted by more than 60s. Please crrect this by running adb shell ...`

**Comment by StasDoskalenko** [comment]
React-native handles background jobs very bad (especially in development mode). Does it work for you in production?

**Comment by anija** [comment]
No, also in production i have the same problem. I have a lot of other tasks running in background, fetching datas from Strava, Apple Health, various REST api, but this one is the only one that freeze the app.

**Comment by anija** [comment]
Calling 30 times the getActivitySamples for each day instead of calling it one times with a startDate/endDate range of 30 days doesn't freeze the app (but is horrible).

**Comment by aboveyunhai** [comment]
Google fit api has a threshold of roughly 2500 - 3000 data per request, request less than or around 2000 is always a safe choice, but since `getActivitySample()` request multiple types of data, it's probably the reason why it causes halt. I would personally request each type of data separately so they hold their own limits instead of all together. But since the implementation was already changed. This might not be the reason.
