### ISSUE TITLE
getWeightSamples() returns an empty array in response

### ISSUE THREAD

**Issue by Yuvi7447** [StasDoskalenko/react-native-google-fit#144]
I have added my height and weight data to Google Fit App. Now I am trying to retrieve data from Google Fit Store using getWeightSamples()and getHeightSamples(), where I am receiving height in meter but for weight, it returns an empty array!
@StasDoskalenko Can you help me out to understand this issue?

**Comment by aboveyunhai** [comment]
close since no further update
