### ISSUE TITLE
Hi, its showing every time Authorization cancelled

### ISSUE THREAD

**Issue by Sarathphd** [StasDoskalenko/react-native-google-fit#145]

**Comment by antoinedelp** [comment]
Hi, have you checked these issues?

https://github.com/StasDoskalenko/react-native-google-fit/issues/123
https://github.com/StasDoskalenko/react-native-google-fit/issues/128

**Comment by jakallergis** [comment]
I have problems with `authorize` as well. I have also looked at both #123 and #128.

I keep getting **_"Autorisation cancelled"_** as soon as I select my Google account. The problem for me is for both simulators and real devices. Also, I have created credentials in the Google Console for both the debug keystore and the release keystore.
I've also created the consent screen mentioned there.

What can I do?

**Comment by Sarathphd** [comment]
try it build.gradle file to add this
     implementation 'com.google.android.gms:play-services-fitness:18.0.0'
    implementation 'com.google.android.gms:play-services-auth:17.0.0'

**Comment by jakallergis** [comment]
Hi! I finally had the time to search more into it and solved it.

1) I didn't have these in:
```
implementation "com.google.android.gms:play-services-base:+"
implementation "com.google.android.gms:play-services-auth:+"
implementation "com.google.android.gms:play-services-fitness:+"
```

2. I also used the wrong package name in the Auth Client I created in the google admin page. Because it said you'd find the package name from the manifest file but in there the `package` was different from the `applicationId` in my case. Turns out the Auth Client needs the `applicationId`. Sorry for any confusion!
This one should be more clear tho.
‾\ _(ツ)_/‾

**Comment by Lalla-Aicha** [comment]
hey, where can I find the applicationId ??

**Comment by IlliaFilatov** [comment]
Hi, I'm still getting message "Authorization canceled". I did all the steps from the instructions and tried every solution from issues here. Nothing happened. Still keep getting "Autorisation cancelled" as soon as I select my Google account.

**Comment by enigcreator** [comment]
@IlliaFilatov have you able to solve this ?

**Comment by Dastan4r** [comment]
> Hi! I finally had the time to search more into it and solved it.
> 
> 1. I didn't have these in:
> 
> ```
> implementation "com.google.android.gms:play-services-base:+"
> implementation "com.google.android.gms:play-services-auth:+"
> implementation "com.google.android.gms:play-services-fitness:+"
> ```
> 
> 1. I also used the wrong package name in the Auth Client I created in the google admin page. Because it said you'd find the package name from the manifest file but in there the `package` was different from the `applicationId` in my case. Turns out the Auth Client needs the `applicationId`. Sorry for any confusion!
>    This one should be more clear tho.
>    ‾\ _(ツ)_/‾

Thanks, i checked my admin, and realy i used another sha1 and package name. Thanks for advice!
