### ISSUE TITLE
Authorization fails - {"message": "Authorization cancelled", "success": false}

### ISSUE THREAD

**Issue by jakallergis** [StasDoskalenko/react-native-google-fit#146]
No matter what I try, I always get this message from the `authorize` method.

- [x] I have enabled the Fitness API in the Google APIs console
- [x] I have created credentials using the debug keystore
- [x] I have created credentials using the release keystore
- [x] I have created a consent screen (that hasn't finish review yet tho)

When I open the app, the popup asking me to select a Google account  is displayed, and the moment I select one (no matter which one), I get the following response from `authorize`:

```javascript
{
  "message": "Authorization cancelled",
  "success": false
}
```

**Comment by jakallergis** [comment]
Obviously everything else I try to use after that `authorize` call, returns `undefined`.

**Comment by antoinedelp** [comment]
I also experienced this issue several times, and everytime it was related to a incorrect initialization of the Google credentials. I fixed it yesterday: I add imported the wrong debug.keystore values for my Google Credentials. I advise you to double, triple check how your app is signed in debug and release: I had duplicated debug.keystore, one in my project folder and one at the root of my computer.

In your app/build.gradle, look for the path of signingConfigs storeFile, and modify it if necessary to point to the debug.keystore you created credentials for.

**Comment by jakallergis** [comment]
Thanks for your reply @antoinedelp. I appreciate your help.

I've just gone through the whole directory and I only have one and only one debug.keystore file which is also what the `signingConfigs` looks at in the `storeFile` property of the `debug` config inside `app/build.gradle`.

But even if that was the case and the debug.keystore was the wrong one. I know for sure that I have only one release keystore, and using that I still get the same error. So I don't think it really has to do with the debug.keystore, and even if that fixed it for me for the simulator, I would still be in trouble for the production version of the app.

**Comment by antoinedelp** [comment]
I had the same problem once again today when rebuilding my app.
In order to make sure point 1 of the installation is done right,  try to add these lines to your android/app/build.gradle

```
implementation "com.google.android.gms:play-services-base:+"
implementation "com.google.android.gms:play-services-auth:+"
implementation "com.google.android.gms:play-services-fitness:+"
```

**Comment by jakallergis** [comment]
Hey @antoinedelp

With a quick look, I noticed that I only have the `play-services-base` dependency and not the other 2. Can't test that right now, but as soon as I do, I will let you know. 

This sounds promising though. Thank you so much for your time

**Comment by atoool** [comment]
try to get your SHA1 key withis command ....
keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias android
debugkey -keypass android -dname "CN=Android Debug,O=Android,C=US"
....
most probably the problem maybe caused by the path of keystore. I was also having the same problem because i forgot to change the path of keystore "~/.android/debug.keystore"

**Comment by atoool** [comment]
ensure you have got the SHA1 key for the debug by using the correct path which is "android/app/debug.keystore" and not by "~/.android/debug.keystore"

**Comment by jakallergis** [comment]
Hi! I finally had the time to search more into it and solved it.

1) Yeah I didn't have these in:
```
implementation "com.google.android.gms:play-services-base:+"
implementation "com.google.android.gms:play-services-auth:+"
implementation "com.google.android.gms:play-services-fitness:+"
```

2. I also had the wrong package name. Because it said you'd find the package name from the manifest file but in there the `package` was different from the `applicationId` in my case. Turns out it needs the `applicationId`. This one should be more clear.

**Comment by TayyabaAslamSeecs** [comment]
@jakallergis where should we get the application id? I am using the one in manifest file and for me it os different from the application id entered for my project on google console.

**Comment by jakallergis** [comment]
If you go to the `app`'s `build.gradle` file inside you'll find something like this:

```gradle
defaultConfig {
        applicationId 'com.example.or.whatever' // <---- THIS IS WHAT U WANT
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 74
        versionName "31.0"
 }
```

The value in `applicationId` is what you need. In this example it's "com.example.or.whatever". In your case it will be something different.

**Comment by Vivek205** [comment]
@antoinedelp & @jakallergis . 
I already have ` compile project(':react-native-google-fit')` in the build.gradle dependencies.should I still have to add
```
implementation "com.google.android.gms:play-services-base:+"
implementation "com.google.android.gms:play-services-auth:+"
implementation "com.google.android.gms:play-services-fitness:+"
```
. should I remove the existing compile project?

**Comment by thesagarshakya** [comment]
If you've configured android to use build variants, please double check our app's package name. We were having this same issue and the cause was that the debug APK's package name was different from that on `AndroidManifest.xml` because we had configured build variants on android. So, we were using the wrong package name on google console settings.
