### ISSUE TITLE
Filter manual entered data

### ISSUE THREAD

**Issue by fmbnar** [StasDoskalenko/react-native-google-fit#148]
We are developing an App which give you "Coins" when you reached an achievement. You can manually enter step in Google Fit. Is it possible to filter out this manual entered data.

**Comment by antoinedelp** [comment]
Activities entered manually are registered without the 'tracked' property set to true. 
We remove the steps of these activities like this : 

`const removeSteps = (options) => {
  return new Promise(function (resolve, reject) {
    var stepsToRemove = 0;
    GoogleFit.getActivitySamples(options, (err, res) => {
      if (err) {
        return resolve(stepsToRemove);
      }
      if (!res || res === false) {
        return resolve(stepsToRemove);
      }
      let manualActivities = res.filter(
        (x) => x.tracked !== true && x.quantity
      );
      // we map on manualActivities to remove steps entered manually by the user.
      manualActivities.map(
        (activity) => (stepsToRemove = stepsToRemove + activity.quantity)
      );
      return resolve(stepsToRemove);
    });
  });
};`

**Comment by marlene89** [comment]
> Activities entered manually are registered without the 'tracked' property set to true.
> 
> We remove the steps of these activities like this :
> 
> ```js
> const removeSteps = (options) => {
>   return new Promise(function (resolve, reject) {
>     var stepsToRemove = 0;
>     GoogleFit.getActivitySamples(options, (err, res) => {
>       if (err) {
>         return resolve(stepsToRemove);
>       }
>       if (!res || res === false) {
>         return resolve(stepsToRemove);
>       }
>       let manualActivities = res.filter(
>         (x) => x.tracked !== true && x.quantity
>       );
>       // we map on manualActivities to remove steps entered manually by the user.
>       manualActivities.map(
>         (activity) => (stepsToRemove = stepsToRemove + activity.quantity)
>       );
>       return resolve(stepsToRemove);
>     });
>   });
> };
> ```

I am getting this error 'attempt to invoke virtual method 'double java.lang.double.doublevalue()' on a null object reference' when I attempt to use this snippet to filter out manually entered data. Anyone else seeing this issue?
