### ISSUE TITLE
Detect if user is registered with google fit or not

### ISSUE THREAD

**Issue by Yuvi7447** [StasDoskalenko/react-native-google-fit#149]
How to check if user is registered with google fit or not, is there any method available to the package? As is i tried with `isAvailable()`and `isEnabled()`methods, but couldn't get any desired output!

**Comment by aboveyunhai** [comment]
Can be checked viable `GoogleFit.isAuthorized`

You can do something like
```
  var isAuth = GoogleFit.isAuthorized;

  // toggle authentication
  if (!isAuth) { 

  } 
```
