### ISSUE TITLE
Cannot read property 'isAuthorized' of undefined

### ISSUE THREAD

**Issue by Vivek205** [StasDoskalenko/react-native-google-fit#150]
- Created an expo app
 - Ejected the expo app
 - installed react-native-google-fit
 - linked the package
 - Added GoogleFit.authorize
 
got the following error.

```
authorized >>> Object {
  "message": "Cannot read property 'isAuthorized' of undefined",
  "success": false,
}
```

**Comment by sreedhu-7** [comment]
I am also facing the same issue, did you get this issue fixed?

**Comment by Vivek205** [comment]
Yh. I created a new keystore file. and used it as my relese keystore. it started working then. 

But still I could not get it working in a real mobile

**Comment by sreedhu-7** [comment]
@Vivek205 Thanks for the update, I have also fixed that issue in my case it was a miss.
I forgot to add this below line in Application.java class
`new GoogleFitPackage(BuildConfig.APPLICATION_ID)`
I think we can close this issue.
