### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by chriswithoak** [StasDoskalenko/react-native-google-fit#151]
I have everything setup. I am authorized and I run the code below on an Android Emulator and I keep getting this error - "There is no any heart rate data for this period false". I am using a Nexus 5 for the emulator and it says Google Play Services. When authorizing I go through the steps of allowing access and it appears that it runs the code below successfully, I just can't get data to return and I know that I have data over the last few days. Any help is very much appreciated.

        const options = {
            startDate: "2017-01-01T00:00:17.971Z", // required
            endDate: "2020-05-30T00:00:17.971Z", // required
          }
          const callback = ((error, response) => {
            console.log(error, response)
          });

          GoogleFit.getHeartRateSamples(options, callback);

**Comment by Vivek205** [comment]
How did you complete authorization.
I'm always getting ```{"message": "Authorization cancelled", "success": false}```

I have even added the `client_secret.json` in the path `android/app/src/main/resources/client_secret.json`.

Should I have to add extra certificates for development as well?

**Comment by MyroslavKoval1999** [comment]
The same problem Any idea?

**Comment by Il-Cesco** [comment]
same here

**Comment by Pankti16** [comment]
Same issue, any solution?
