### ISSUE TITLE
GoogleFit.authorize is not working in the release APK

### ISSUE THREAD

**Issue by Vivek205** [StasDoskalenko/react-native-google-fit#152]
Whenever GoogleFit.authorize is used in the **release APK**, it is returning
 `{"message": "Authorization cancelled", "success": false}`. 
But the same is working in the development mode.

**Comment by AMITGOUDA-SS** [comment]
did you solved the authorization issue during build ?

**Comment by Vivek205** [comment]
> did you solved the authorization issue during build ?

https://github.com/StasDoskalenko/react-native-google-fit/issues/150#issuecomment-632077545

**Comment by Vivek205** [comment]
No I could not able to solve it in release package.

**Comment by dethell** [comment]
@Vivek205 this is usually because of a problem in your Google API Console settings. Make sure that you have the correct SHA-1 in your console settings that matches the SHA of your release keystore.

**Comment by ravi2611gupta** [comment]
for getting SHA1
you can use 


cd android/app

keytool -list -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android
