### ISSUE TITLE
getting issue while calling GoogleFit.authorize(options)

### ISSUE THREAD

**Issue by AMITGOUDA-SS** [StasDoskalenko/react-native-google-fit#153]
AUTH_DENIED cannot read propery of isAuthorized of undefined.

**Comment by Pragnesh-Dharajiya** [comment]
**AUTH_DENIED cannot read propery of isAuthorized of undefined. please tell steps to implement authorization with google fit**

**Comment by aboveyunhai** [comment]
https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md#demo-walkthrough

This link should help you out now
