### ISSUE TITLE
Cannot find a method to retrieve blood glucose 

### ISSUE THREAD

**Issue by tolik85** [StasDoskalenko/react-native-google-fit#154]
Hello!

I cannot find a method to retrieve blood glucose, although FITNESS_BLOOD_GLUCOSE_READ appears in scopes.

Please advise.

Thanks!
Nathan

**Comment by aboveyunhai** [comment]
can be fetched by calling `GoogleFit.getBloodPressureSamples(options, callback)`

**Comment by ksetrin** [comment]
@aboveyunhai checked now and I can't retrieve blood glucose from `getBloodPressureSamples`
