### ISSUE TITLE
Cannot get all weight samples on a given day

### ISSUE THREAD

**Issue by tvisnia** [StasDoskalenko/react-native-google-fit#158]
I would be grateful if you could help me to find a way to get all weight samples from Google Fit on a given day (from 00:00:000 to 23:59:999). 

For example, at this moment I am getting two or three most recent weight measurements, while there are 5 or 6 on a given day. I have also read native code in which I got to know that only max, min or average value may be returned, but is there any option to refactor Java code so as to get all samples on a day ? 

My second question refers to buckets. What is this ? How is this limiting or influencing queries to Google Fit in a context of getting weight samples ?

**Comment by aboveyunhai** [comment]
because the original implementation is getting the `type_weight_summary` which only contains `max`, `min` and `average`, and apparently the current implementation only take the average only. I will look into it if I improve the old code.
