### ISSUE TITLE
How to get steps sample on hourly basis on a given day

### ISSUE THREAD

**Issue by surndraraj3** [StasDoskalenko/react-native-google-fit#160]
Can you help me on to get steps hourly basis breakup on given day.

**Eg: (2020-05-30 01:00:00 - 2020-05-30 11:59:00)**

**Comment by aboveyunhai** [comment]
The short answer is you cannot . 
For the API itself, it's doable to get steps from specific timestamp range. 
But the current function regarding `step` data only includes the daily count. Most likely you have to dig through the original code, modify native module and create new function for yourself, or wait for someone contribute to the repo. I'm actually working on it but it could take a while.

**Comment by FrikkieSnyman** [comment]
I think this PR should address this: https://github.com/StasDoskalenko/react-native-google-fit/pull/174
