### ISSUE TITLE
Get Sleep Data crashes application

### ISSUE THREAD

**Issue by eszlerbianca** [StasDoskalenko/react-native-google-fit#162]
Hello, I noticed there is a new version (0.11.0) which includes support for getting google fit sleep data. I am trying to get it working, but did not manage yet. Nevertheless, I am successfully using getDailyStepCount, for instance.

I tried simply 

```
const options = {
    endDate: new Date().toISOString(),
    startDate: moment(new Date()).subtract(2, 'day').toISOString(),
  };

  const sleepPromise = GoogleFit.getSleepData(options);

  if (!sleepPromise) {
    return;
  }

  sleepPromise.then((res) => console.log(res));
	.catch((error) => { console.warn(error); });

```

And also using the callback parameter

```
const options = {
    endDate: new Date().toISOString(),
    startDate: moment(new Date()).subtract(2, 'day').toISOString(),
  };

  const sleepPromise = GoogleFit.getSleepData(options, (isError, result) => {
    console.log('sleep result', isError, result);
  });

```

The following exception appears in logs:
```
FATAL EXCEPTION: main
    com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed
        at com.facebook.react.bridge.WritableNativeMap.putString(Native Method)
        at com.reactnative.googlefit.SleepHistory.processDataSet(SleepHistory.java:132)
        at com.reactnative.googlefit.SleepHistory.access$000(SleepHistory.java:67)
        at com.reactnative.googlefit.SleepHistory$2.onSuccess(SleepHistory.java:110)
        at com.reactnative.googlefit.SleepHistory$2.onSuccess(SleepHistory.java:90)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
```

Could you please guide me to successfully use this functionality? Appreciate any suggestion.

**Comment by dethell** [comment]
I will take a look at the sleep data crashes and see what is happening. The "map already consumed" exception should only occur if we invoke the success or error callback and then after invocation we try to put something to the map. I don't see that being able to happen in the code, but I'll go through it again and see.

**Comment by dethell** [comment]
I have created a PR (https://github.com/StasDoskalenko/react-native-google-fit/pull/166) that fixes this issue.

**Comment by dethell** [comment]
@eszlerbianca If you need to get sleep hours working before the above PR is merged you'll just need a two line fix to SleepHistory.java which you can see in the above PR. This line:
`WritableMap sleepMap = Arguments.createMap();`
Needs to be moved inside the for loop in `processDataSet`.

**Comment by eszlerbianca** [comment]
Excellent, thanks for the suggestion @dethell. Tried it today, the app it's not crashing anymore and it seems to retrieve correctly the sleep data.

**Comment by dethell** [comment]
This issue can be closed now that PR 166 has merged.
