### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by agnieszkabugla** [StasDoskalenko/react-native-google-fit#164]
`    
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-google-fit": "^0.10.0",
`

The build on Android fails:

```
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':react-native-google-fit:compileReleaseJavaWithJavac'.
```

when i run build with `--warning-mode all `, i can see many errors, all of them look like that:
```
node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/RecordingApi.java:116: error: cannot find symbol
        String eventName, @Nullable WritableMap params) {
                           ^
  symbol:   class Nullable
  location: class RecordingApi
```

I have tried upgrading react-native-google-fit version to 0.11.0, but did not help. 

i also tried with different gradle versions, but still no luck.
My current gradle version:
in `android/gradle/wrapper/gradle-wrapper.properties` i have `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`

in `android/build.gradle` i have `classpath("com.android.tools.build:gradle:3.5.0")`

Anyone that had the same or similar problem and fixed it?

**Comment by vescogma** [comment]
@agnieszkabugla Did you figure this one out?

**Comment by philipusmartin9** [comment]
currently I have the same problem, still searching for solutions

**Comment by agnieszkabugla** [comment]
it appeared it was not a problem with react-native-google-fit. 
We use app center for app building in production and it updates minor versions of different packages from package.json. 
It updated react-native-keychain that we use in the project and this update caused build fails. The only thing that i had to change was remove caret from package.json:  `"react-native-keychain": "6.0.0",`
