### ISSUE TITLE
Unable to resolve module `moment`

### ISSUE THREAD

**Issue by Teogranberg** [StasDoskalenko/react-native-google-fit#165]
Since the addition of the moment.js package the module breaks unless you have moment added in your other dependencies.

Reproduction; install package without installing devdeppendencies or having moment already as a dependency.

![Screenshot_20200611-112047](https://user-images.githubusercontent.com/15192054/84368851-64294a00-abd6-11ea-94c1-b5bbab440481.jpg)

**Comment by StasDoskalenko** [comment]
Resolved in 0.12.1
