### ISSUE TITLE
how to get move minute and step.

### ISSUE THREAD

**Issue by patelrushabh** [StasDoskalenko/react-native-google-fit#167]
I use Get all activities, GoogleFit.getActivitySamples  method but getting a false response. 

i want to display like this in my app. this is google fit app screen shot

![IMG_20200630_183000](https://user-images.githubusercontent.com/30159099/86137561-0f109200-bb0b-11ea-891c-7a5d156779a8.jpg)

**Comment by jlgonzalezdev** [comment]
Hi @patelrushabh, did you find a way to get or calculate move minutes with this library?? I'm trying to implement a feature that needs to display move minutes from google fit. Thanks
