### ISSUE TITLE
getActivitySamples not returning quantity

### ISSUE THREAD

**Issue by marlene89** [StasDoskalenko/react-native-google-fit#168]
I am using getActivitySamples to try and filter out manually entered activities using the tracked flag. I am getting back the response with the tracked flag set to false for manually entered activities but the quantity field does not exist in the response.
Here is the request:
```
removeSteps = () => {
    let options = {
      startDate: new Date(2020, 6, 28).valueOf(), // simply outputs the number of milliseconds since the Unix Epoch
      endDate: new Date(2020, 6, 30).valueOf(),
    };
 
    return new Promise(function (resolve, reject) {
      var stepsToRemove = 0;
      GoogleFit.getActivitySamples(options, (err, res) => {
        if (err) {
          return resolve(stepsToRemove);
        }
        if (!res || res === false) {
          return resolve(stepsToRemove);
        }
        Log.info({ tag: 'HomeScreen', message: 'Google Fit getActivitySamples: ' + JSON.stringify(res) });
        let manualActivities = res.filter((x: any) => x.tracked === false);
        // we map on manualActivities to remove steps entered manually by the user.
        Log.info({
          tag: 'HomeScreen',
          message: 'Google Fit manualActivities: ' + JSON.stringify(manualActivities),
        });
        manualActivities.map((activity: any) => (stepsToRemove = stepsToRemove));
        Log.info({ tag: 'HomeScreen', message: 'Steps to remove: ' + stepsToRemove });
        return resolve(stepsToRemove);
      });
    });
  };
```

Logging shows that res is:
```
[{"tracked":false,"sourceId":"com.google.android.gms","sourceName":"","device":"","calories":2446.902099609375,"activityName":"unknown","end":1596060000000,"start":1595887200000}]
```
Quantity field does not exist in response, so i am unable to know how many steps were manually entered.
Any ides what is missing?

**Comment by aboveyunhai** [comment]
It should be fine.  It just mean you don't have any steps within your timestamp.

**Comment by marlene89** [comment]
> It should be fine. It just mean you don't have any steps within your timestamp.

But I do. that is the physical activity that i entered. I created 2 entries, each with a 1000 steps and I can see them being returned when i call GoogleFit.getDailySteps. this is the response:
```
[{"source":"com.google.android.gms:merge_step_deltas","steps":[{"date":"2020-06-29","value":2000}]},{"source":"com.xiaomi.hm.health","steps":[]},{"source":"com.google.android.gms:estimated_steps","steps":[{"date":"2020-06-29","value":2000}]}]
```
so shouldnt these steps get returned in the quantity field when I call ```getActivitySamples```?

**Comment by aboveyunhai** [comment]
`new Date(2020, 6, 28)`  is July not June, month starts from 0 instead of 1. You probably pass the wrong optionss.

**Comment by marlene89** [comment]
> `new Date(2020, 6, 28)` is July not June, month starts from 0 instead of 1. You probably pass the wrong params.
> Just check all the variables.
> `GoogleFit.getDailySteps.` has some weird behavior because of javascript `Date()` timezone issue. You probably don't want to rely on that functions before next fix,

Thank you so much for your help. I changed 6 to 5 in ```new Date(2020, 6, 28)``` and now i'm getting back the correct values.
Which method do you recommend I use to get daily steps?

**Comment by aboveyunhai** [comment]
Just the original `GoogleFit.getDailyStepCountSamples`,  both  `get Daily/weekly Steps` is just a shortcut version to utilize it. Or You can still use it, just wait for my next PR to fix it. But before that you might aware of the steps is changing during special time span depending on your timezone.

**Comment by marlene89** [comment]
Thank you so much for all your help. I really appreciate it. I will close the issue now 🙌🏼
