### ISSUE TITLE
Build failed with an exception: cannot find symbol getName()

### ISSUE THREAD

**Issue by HumbleBeck** [StasDoskalenko/react-native-google-fit#176]
Build failed on new RN project
```
/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/StepHistory.java:211: error: cannot find symbol
            if (dataSource.getName() != null) {
                          ^
  symbol:   method getName()
  location: variable dataSource of type DataSource
/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/StepHistory.java:212: error: cannot find symbol
                source.putString("name", dataSource.getName());
                                                   ^
  symbol:   method getName()
  location: variable dataSource of type DataSource
/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/RecordingApi.java:56: error: cannot find symbol
                return DataType.TYPE_ACTIVITY_SAMPLES;
                               ^
  symbol:   variable TYPE_ACTIVITY_SAMPLES
  location: class DataType
```

to fix that you need explicitly set 
`rootProject.ext.set("fitnessVersion", "18.0.0")` in your build.gradle config, there is [breaking changes](https://developers.google.com/android/guides/releases#august_10_2020)  in v19

**Comment by lemonkey** [comment]
Thanks this just started happening when a build was fine on Friday.

**Comment by saitejamalapati** [comment]
Can I know where exactly to set the "rootProject.ext.set("fitnessVersion", "18.0.0")" in build.gralde?

**Comment by KaviduAloka** [comment]
As @HumbleBeck says, put it in node-modules/react-native-google-fit/android/build-gradle

`def safeExtGet(prop, fallback) {
    rootProject.ext.set("fitnessVersion", "18.0.0")
}`

**Comment by HumbleBeck** [comment]
@saitejamalapati android/app/build.gradle next to project.ext.react

**Comment by mohsinulhaq** [comment]
@KaviduAloka not in the node_modules, but in your OWN project's build.gradle, https://github.com/StasDoskalenko/react-native-google-fit/blob/master/android/build.gradle#L17
this will take the version from your project then

**Comment by agnieszkabugla** [comment]
works! 
in android/app/build.gradle

<img width="534" alt="Screenshot 2020-08-11 at 10 32 10" src="https://user-images.githubusercontent.com/31632526/89875814-07d6ac80-dbbe-11ea-85a6-bb5e02645380.png">

**Comment by Hesowcharov** [comment]
or, you can put in your root gradle file at `app-name/android/build.gradle`:
```
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"

        // react-native-google-fit
        fitnessVersion = "18.0.0"
    }
    repositories {
    ...
```

**Comment by saitejamalapati** [comment]
We were actually using an old version of the node module which was not taking the dependency version from the rootProject. We have upgraded the version to 0.13.0 and then tried to set the version of fitnessVersion to 18.0.0 as mentioned by @HumbleBeck and it works fine.
Thanks a lot everyone :)

**Comment by mohsinulhaq** [comment]
Hi guys need some help,
in root project's `build.gradle`:
ext {
  googlePlayServicesVersion = "17.0.0"
}

but the [pom.xml](https://maven.google.com/web/index.html?q=gms#com.google.android.gms:play-services-fitness:18.0.0) of google fitness says that it depends on play-service-base `17.1.0`
So my question is, can I not use v18 because my play service version is older?

**Comment by qlereboursBS** [comment]
This is due to a recent release of Google play fitness service: https://developers.google.com/android/guides/releases#august_10_2020

@agnieszkabugla fix is working for me, but I think that this library shouldn't use the most recent version of Google services, but a fixed version

**Comment by mkwforaus** [comment]
Hi everyone, 

I tried to add the `rootProject.ext.set("fitnessVersion", "18.0.0")` to the root project's `app/build.gradle` suggested by @HumbleBeck and add `fitnessVersion = "18.0.0"` to the `android/build.gradle` suggested by @Hesowcharov, the compiling error is gone. However, when I try to get the daily steps:
```
       const stepOptions = {
          startDate: moment().add(-1, 'day').format(),
          endDate: moment().format(),
        };
        GoogleFit.authorize(options).then(async authResult => {
          if (authResult.success) {
            const stepOptions = {
              startDate: moment().add(-1, 'day').format(),
              endDate: moment().format(),
            };
            GoogleFit.getDailyStepCountSamples(stepOptions)
              .then(result => console.log(result))
              .catch(error => console.error(error));
          }})

```

The following errors is displayed:
![bug](https://user-images.githubusercontent.com/35763121/90007729-da792400-dccd-11ea-9ecb-515b4267ffd1.png)

It seems that even though I set the fitnessVersion to 18.0.0, the deprecated methods still cannot be used. Do you know any solutions for this. 

Thanks

**Comment by mkwforaus** [comment]
> Hi everyone,
> 
> I tried to add the `rootProject.ext.set("fitnessVersion", "18.0.0")` to the root project's `app/build.gradle` suggested by @HumbleBeck and add `fitnessVersion = "18.0.0"` to the `android/build.gradle` suggested by @Hesowcharov, the compiling error is gone. However, when I try to get the daily steps:
> 
> ```
>        const stepOptions = {
>           startDate: moment().add(-1, 'day').format(),
>           endDate: moment().format(),
>         };
>         GoogleFit.authorize(options).then(async authResult => {
>           if (authResult.success) {
>             const stepOptions = {
>               startDate: moment().add(-1, 'day').format(),
>               endDate: moment().format(),
>             };
>             GoogleFit.getDailyStepCountSamples(stepOptions)
>               .then(result => console.log(result))
>               .catch(error => console.error(error));
>           }})
> ```
> 
> `package-lock.json`
> 
> ```
>       "version": "0.13.0",
>       "resolved": "https://registry.npmjs.org/react-native-google-fit/-/react-native-google-fit-0.13.0.tgz",
>       "integrity": "sha512-fFS/6DBrMdwWbun0hwrtROlM2uSwrsFmNyT+/FKwVmza4kl55TLEYjosmvSnwmewcLsvDOIwjOBUMiogwvgDLQ==",
>       "requires": {
>         "moment": "2.20.1"
>       },
>       "dependencies": {
>         "moment": {
>           "version": "2.20.1",
>           "resolved": "https://registry.npmjs.org/moment/-/moment-2.20.1.tgz",
>           "integrity": "sha512-Yh9y73JRljxW5QxN08Fner68eFLxM5ynNOAw2LbIB1YAGeQzZT8QFSUvkAz609Zf+IHhhaUxqZK8dG3W/+HEvg=="
>         }
>       }
>     },
> ```
> 
> `android/build.gradle`
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 18
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
>         fitnessVersion = "18.0.0"
>     }
>     repositories {
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath('com.android.tools.build:gradle:3.5.3')
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> ```
> 
> The following errors is displayed:
> ![bug](https://user-images.githubusercontent.com/35763121/90007729-da792400-dccd-11ea-9ecb-515b4267ffd1.png)
> 
> It seems that even though I set the fitnessVersion to 18.0.0, the deprecated methods still cannot be used. Do you know any solutions for this?
> 
> Thanks

Fixed by adding `implementation "com.google.android.gms:play-services-fitness:18.0.0"` to the `/app/build.gradle` => dependencies. However, the GoogleFit.getDailyStepCountSamples failed to return any responses (both success and failure response)

**Comment by mkwforaus** [comment]
> > Hi everyone,
> > I tried to add the `rootProject.ext.set("fitnessVersion", "18.0.0")` to the root project's `app/build.gradle` suggested by @HumbleBeck and add `fitnessVersion = "18.0.0"` to the `android/build.gradle` suggested by @Hesowcharov, the compiling error is gone. However, when I try to get the daily steps:
> > ```
> >        const stepOptions = {
> >           startDate: moment().add(-1, 'day').format(),
> >           endDate: moment().format(),
> >         };
> >         GoogleFit.authorize(options).then(async authResult => {
> >           if (authResult.success) {
> >             const stepOptions = {
> >               startDate: moment().add(-1, 'day').format(),
> >               endDate: moment().format(),
> >             };
> >             GoogleFit.getDailyStepCountSamples(stepOptions)
> >               .then(result => console.log(result))
> >               .catch(error => console.error(error));
> >           }})
> > ```
> > 
> > 
> > `package-lock.json`
> > ```
> >       "version": "0.13.0",
> >       "resolved": "https://registry.npmjs.org/react-native-google-fit/-/react-native-google-fit-0.13.0.tgz",
> >       "integrity": "sha512-fFS/6DBrMdwWbun0hwrtROlM2uSwrsFmNyT+/FKwVmza4kl55TLEYjosmvSnwmewcLsvDOIwjOBUMiogwvgDLQ==",
> >       "requires": {
> >         "moment": "2.20.1"
> >       },
> >       "dependencies": {
> >         "moment": {
> >           "version": "2.20.1",
> >           "resolved": "https://registry.npmjs.org/moment/-/moment-2.20.1.tgz",
> >           "integrity": "sha512-Yh9y73JRljxW5QxN08Fner68eFLxM5ynNOAw2LbIB1YAGeQzZT8QFSUvkAz609Zf+IHhhaUxqZK8dG3W/+HEvg=="
> >         }
> >       }
> >     },
> > ```
> > 
> > 
> > `android/build.gradle`
> > ```
> > buildscript {
> >     ext {
> >         buildToolsVersion = "28.0.3"
> >         minSdkVersion = 18
> >         compileSdkVersion = 28
> >         targetSdkVersion = 28
> >         supportLibVersion = "28.0.0"
> >         fitnessVersion = "18.0.0"
> >     }
> >     repositories {
> >         google()
> >         jcenter()
> >     }
> >     dependencies {
> >         classpath('com.android.tools.build:gradle:3.5.3')
> > 
> >         // NOTE: Do not place your application dependencies here; they belong
> >         // in the individual module build.gradle files
> >     }
> > }
> > ```
> > 
> > 
> > The following errors is displayed:
> > ![bug](https://user-images.githubusercontent.com/35763121/90007729-da792400-dccd-11ea-9ecb-515b4267ffd1.png)
> > It seems that even though I set the fitnessVersion to 18.0.0, the deprecated methods still cannot be used. Do you know any solutions for this?
> > Thanks
> 
> Fixed by adding `implementation "com.google.android.gms:play-services-fitness:18.0.0"` to the `/app/build.gradle` => dependencies. However, the GoogleFit.getDailyStepCountSamples failed to return any responses (both success and failure response)

Error is due to "The user must be signed in to make this API call.". However, the authResult is {"success":true}, not sure why it says the user is not logged in. It worked fine before with react-native-google-fit 10.0.0

**Comment by mkwforaus** [comment]
> > > Hi everyone,
> > > I tried to add the `rootProject.ext.set("fitnessVersion", "18.0.0")` to the root project's `app/build.gradle` suggested by @HumbleBeck and add `fitnessVersion = "18.0.0"` to the `android/build.gradle` suggested by @Hesowcharov, the compiling error is gone. However, when I try to get the daily steps:
> > > ```
> > >        const stepOptions = {
> > >           startDate: moment().add(-1, 'day').format(),
> > >           endDate: moment().format(),
> > >         };
> > >         GoogleFit.authorize(options).then(async authResult => {
> > >           if (authResult.success) {
> > >             const stepOptions = {
> > >               startDate: moment().add(-1, 'day').format(),
> > >               endDate: moment().format(),
> > >             };
> > >             GoogleFit.getDailyStepCountSamples(stepOptions)
> > >               .then(result => console.log(result))
> > >               .catch(error => console.error(error));
> > >           }})
> > > ```
> > > 
> > > 
> > > `package-lock.json`
> > > ```
> > >       "version": "0.13.0",
> > >       "resolved": "https://registry.npmjs.org/react-native-google-fit/-/react-native-google-fit-0.13.0.tgz",
> > >       "integrity": "sha512-fFS/6DBrMdwWbun0hwrtROlM2uSwrsFmNyT+/FKwVmza4kl55TLEYjosmvSnwmewcLsvDOIwjOBUMiogwvgDLQ==",
> > >       "requires": {
> > >         "moment": "2.20.1"
> > >       },
> > >       "dependencies": {
> > >         "moment": {
> > >           "version": "2.20.1",
> > >           "resolved": "https://registry.npmjs.org/moment/-/moment-2.20.1.tgz",
> > >           "integrity": "sha512-Yh9y73JRljxW5QxN08Fner68eFLxM5ynNOAw2LbIB1YAGeQzZT8QFSUvkAz609Zf+IHhhaUxqZK8dG3W/+HEvg=="
> > >         }
> > >       }
> > >     },
> > > ```
> > > 
> > > 
> > > `android/build.gradle`
> > > ```
> > > buildscript {
> > >     ext {
> > >         buildToolsVersion = "28.0.3"
> > >         minSdkVersion = 18
> > >         compileSdkVersion = 28
> > >         targetSdkVersion = 28
> > >         supportLibVersion = "28.0.0"
> > >         fitnessVersion = "18.0.0"
> > >     }
> > >     repositories {
> > >         google()
> > >         jcenter()
> > >     }
> > >     dependencies {
> > >         classpath('com.android.tools.build:gradle:3.5.3')
> > > 
> > >         // NOTE: Do not place your application dependencies here; they belong
> > >         // in the individual module build.gradle files
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > > The following errors is displayed:
> > > ![bug](https://user-images.githubusercontent.com/35763121/90007729-da792400-dccd-11ea-9ecb-515b4267ffd1.png)
> > > It seems that even though I set the fitnessVersion to 18.0.0, the deprecated methods still cannot be used. Do you know any solutions for this?
> > > Thanks
> > 
> > 
> > Fixed by adding `implementation "com.google.android.gms:play-services-fitness:18.0.0"` to the `/app/build.gradle` => dependencies. However, the GoogleFit.getDailyStepCountSamples failed to return any responses (both success and failure response)
> 
> Error is due to "The user must be signed in to make this API call.". However, the authResult is {"success":true}, not sure why it says the user is not logged in. It worked fine before with react-native-google-fit 10.0.0

Works fine when revert back to react-native-google-fit 10.0.

**Comment by mattyx96** [comment]
> // react-native-google-fit
>         fitnessVersion = "18.0.0"

WORKS

**Comment by aboveyunhai** [comment]
Just want to mention that I go through the `datasource#getName()` function, there is not particular user case besides general `log.i()` functions for debug purpose only.  Neither `setName()` is used for any data aggregation. I can create PR later to safely remove all of  them as well as changing the `activity type`. 
I believe the type was already deprecated when this package was first initial. I can't guarantee how it will affect the activity data fetching or people who are using old google service?

**Comment by aboveyunhai** [comment]
@mkwforaus  do you try to clean cache and rebuild/reinstall your project? any sign out or sign in mechanism? 
Note that version 10 use deprecated api to fetch data, v13 uses the standard one.

**Comment by c-goettert** [comment]
I also noticed our Android Project wasn't compiling anymore a few days ago. I just wanted to paste my error-output from the console, in case anyone is searching for it. After `running react-native run-android` I got the generic build error:

`* What went wrong:
Execution failed for task ':react-native-google-fit:compileDebugJavaWithJavac'.
`

The solution from above (setting a fitness version to 18) worked for me as well.

**Comment by mkwforaus** [comment]
> @mkwforaus do you try to clean cache and rebuild/reinstall your project? any sign out or sign in mechanism?
> Note that version 10 use deprecated api to fetch data, v13 uses the standard one.

Many thanks. I tried gradle clean, react-native start --reset-cache, rebuild and reinstall the project, as well as remove the whole node_modules folder and Remove the Google Account and Sign in again. However, all of these do not work. I called the GoogleFit.isAuthorized before invoking the getDailyStepSamples method, and GoogleFit.isAuthorized returns true actually. I try to call other methods like (getCalorie and getDistance), all these methods work fine except for methods related to getting steps and sleeps. 

The SOLUTION turns out to be calling GoogleFit.disconnect() once then sign-in again. After that getDailyStepSamples work now.

Thanks for your help.

BTW, just try the commit eb3ce25, it works fine for me in v13, build process can be finished without errors and getting steps work fine without the needs to specify fitnessVersion = "18.0.0" in build.gradle files. But not guarantee other functions work fine.

**Comment by aboveyunhai** [comment]
There are some "breaking changes" (is working now but will break in the near future) again in 20.0.0.
I guess it's good to continue on this thread and probably someone of you might want to be notified.
https://developers.google.com/fit/improvements
