### ISSUE TITLE
error: package android.support.annotation does not exist

### ISSUE THREAD

**Issue by hmazer** [StasDoskalenko/react-native-google-fit#179]
I'm having this issue when building the app after installing this module.
`error: package android.support.annotation does not exist`.
The error appear in multiple files, such as this:
`...java/com/reactnative/googlefit/CalorieHistory.java:14: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;`

Later on on the log, a few of these appear:
`java/com/reactnative/googlefit/StepCounter.java:128: error: cannot find symbol
                           @Nullable WritableMap params) {`

I've tried to import this dependency:
`implementation "androidx.annotation:annotation:1.1.0"`
and
`implementation "com.android.support:support-annotations:28.0.0"`

These variables are set to true:
`android.useAndroidX=true
android.enableJetifier=true`

How can I fix this issue?

**Comment by JoelOnGithub** [comment]
@hmazer do you have any update? We're experiencing this as well since three days ago

**Comment by hmazer** [comment]
> @hmazer do you have any update? We're experiencing this as well since three days ago

Yes, I fixed it by replacing the mentioned imports with AndroidX equivalents
