### ISSUE TITLE
Cant get any data in release - Android

### ISSUE THREAD

**Issue by losheredos** [StasDoskalenko/react-native-google-fit#180]
The package works fine in debug and release apk, like I can get steps data of the user without any problem. I also added debug and release SHA1 keys to google console also activated oath2 and filled the required information.

The problem is when we upload the app bundle to google play and release it for users, then its not working. It initializes and asks for permission but we cant get any value.. I really cant understand and solve it for few weeks already, so decided to ask here if anyone would have some idea why would it be happening?

In case it may be connected here is some files from the project:

```
`"dependencies": {
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/cli-platform-ios": "^4.10.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/push-notification-ios": "^1.2.0",
    "@react-native-community/viewpager": "^4.1.0",
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/messaging": "^7.1.0",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
    "axios": "^0.19.2",
    "dayjs": "^1.8.33",
    "firebase": "^7.14.6",
    "localized-strings": "^0.2.4",
    "react": "16.9.0",
    "react-native": "^0.61.5",
    "react-native-device-info": "^5.5.7",
    "react-native-document-picker": "^3.5.4",
    "react-native-dots-pagination": "^0.1.9",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-get-random-values": "^1.3.1",
    "react-native-gifted-chat": "^0.16.1",
    "react-native-google-fit": "^0.13.0",
    "react-native-image-picker": "^2.3.1",
    "react-native-onesignal": "^3.9.0",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.3.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^4.4.5",
    "react-native-webview": "^9.1.4",
    "react-navigation": "^4.2.2",
    "react-navigation-stack": "^2.2.3",
    "react-navigation-tabs": "^2.8.13",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",
    "rn-apple-healthkit": "^0.8.0"`
```

> build.gradle

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath('com.google.gms:google-services:4.3.3')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
`

```

> app/build.gradle

```
`apply plugin: "com.android.application"

import com.android.build.OutputFile
project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId xxx"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 28
        versionName "1.4.16"
        multiDexEnabled true 
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation project(':react-native-webview')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-fs')
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
googleServices { disableVersionCheck = true }
`
```

> android.xml

```
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.xxx"
  android:versionCode="23"
  android:versionName="1.4.16">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTask">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      
    </application>


</manifest>
`
```

**Comment by aboveyunhai** [comment]
I feel like your problem comes from the release key configuration, Even though the permission panel is promoted, you can still fail to sign in if the key is not correctly config. 
Just for debugging suggestion, you can try something to indicate your current sign in status, to check if you are signed after the permission panel, then decided to call any other functions upon the sign-in status.

**Comment by losheredos** [comment]
@aboveyunhai Oh I didnt even know about the signing SHA1 key because as I understood it as we should just use debug and release. So thank you very much, I just added signing key to oauth panel and I think it will start to work.. 

Will let you know.

**Comment by YahiaJabeur** [comment]
@losheredos 
could you please check if you are only facing the issue in Huawei devices ???

**Comment by losheredos** [comment]
@YahiaJabeur Hmm I just checked and asked our clients/testers who has this issue, so their devices are Huawei and Samsung. So means its not connected with devices?

**Comment by aboveyunhai** [comment]
@losheredos I highly suggest you read Doc regarding the library or functions you used, and some of the closed issues, even StackOverflow to find any relevances. Not to the offend, I just felt like you randomly guessed things without search around based on your previous comments, this wouldn't help as we always likely encounter some issues in the future. 

Fewer things to be noticed, do they all install `google fit app` in their own devices? `google fit android API` primarily requires you to install the App in your device so it can communicate with the App. If not, you should call `recording` function to subscribe services without the App. Those information all can be found from past closed issues and google fit API websites.

Huawei new devices have some problems with google service (if you ever heard about the Huawei trade ban news), this might be a problem but I cannot confirm.

**Comment by losheredos** [comment]
@aboveyunhai I read docs, did all as required expect the release key stuff. Yes there are much information about it but still I cant exactly understand why some devices can get this steps data and some cant, so dont blame me please cuz if it would be so clear to understand I wouldnt be here asking right?

Probably many people dont have this google fit api, also anyway in my case recording function is triggered every time. 

In IOS it works so clean cuz this data is already in device itself but for android.. Ok looks like this issue cant be resolved by questioning and probably cant and wont work good as in IOS.

**Comment by aboveyunhai** [comment]
> @aboveyunhai I read docs, did all as required except the release key part. Yes there are much information about it but still I cant exactly understand why some devices can get this steps data and some cant, so dont blame me please cuz if it would be so clear to understand I wouldnt be here asking right?
> 
> Probably many people dont have this google fit api, also anyway in my case recording function is triggered every time.
> 
> In IOS it works so clean cuz this data is already in device itself but for android.. Ok looks like this issue cant be resolved by questioning and probably cant and wont work good as in IOS.

I understand your frustration with android devices, just sometimes if you provided a little bit more specific information can help communications easier, otherwise we have to assume you had hadn't done something. Don't take my word too personally that's why I specifically mention `not to offend`. I apologised if you felt it's somehow offense to you.

**Comment by losheredos** [comment]
@aboveyunhai Thanks for understanding.

So currently I implemented bugsnag to log the every step of this getting steps data process. When it dont work this process stucks in API part, no exception or error occurs just feels like this process hangs in google fit API connection and cant get next logs after that step.

I added also extra android support libraries like these, also some extra permissions but still same. ;

```
implementation "com.android.support:support-core-utils:28.0.0"
implementation "com.android.support:appcompat-v7:28.0.0"


<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>
```

Will try your suggestion to reboot. Just looks like I cant get why process stops after google fit API..

**Comment by losheredos** [comment]
Well I solved the issue.. Still its very weird issue but, first of course its my fault to not check documentation again. Seconds its bad documentation and naming.. Like how you can write READ_WRITE and it can only mean WRITE?
```
scopes: [
    Scopes.FITNESS_ACTIVITY_READ_WRITE,
    Scopes.FITNESS_BODY_READ_WRITE,
  ],
```
 Its very wrong documentation because just after these example it shows how to retrieve steps(as I just followed those). So instead of top I added two extra permissions and the problem is solved.

```
 scopes: [
            Scopes.FITNESS_ACTIVITY_READ,
            Scopes.FITNESS_ACTIVITY_READ_WRITE,
            Scopes.FITNESS_BODY_READ,
            Scopes.FITNESS_BODY_READ_WRITE,
],
```
So this small issue cost me like few weeks which is actually still unlogical because it worked with only two permissions in half of the devices.. Also I google-fit API has problem because in this case this API could fail and we could catch the error and understand that its the problem of lack of permissions.

**Comment by aboveyunhai** [comment]
Good to know, the naming indeed makes no sense.
Maybe we can propose this and make it to the next major changes (breaking changes) along with others?

**Comment by losheredos** [comment]
Yeah right, from this mistake/problem we can create nice suggestions as you mean. Definitely this naming needs to be changed to avoid these kind of pitfalls.

**Comment by aboveyunhai** [comment]
I want to simply/remove a lot of dupe codes even get rid of old code as well so to unite it all callable functions into one common standard, but it will definitely break a lot of old uses.
since you used in prod environment. I just wonder how do you felt about 
```
const callback = somefunction(){}
result = await googlefit.function(options, callback);
```
```
googlefit.function(options, (err, result) => { 
//handle your own 
})
```
VS.

```
result = await googlefit.functions(options);
//completely handle your own
console.log(result)
```
``` 
googlefit.functions(options).then((result) => {} )
```

I want to remove the callback (some functions take it as requirement, some take as options) thing since it does not offer any user debug info except some custom true/false error flag.

**Comment by losheredos** [comment]
@aboveyunhai Yeah I agree with your suggestion, promises are more modern and useful also easier to debug comparetely to callbacks. Yeah it can cause much issues, in this case you need to explain it with nice tutorials to developers in README. 

By the way you are not owner but contributer for this package right?

**Comment by aboveyunhai** [comment]
> @aboveyunhai Yeah I agree with your suggestion, promises are more modern and useful also easier to debug comparetely to callbacks. Yeah it can cause much issues, in this case you need to explain it with nice tutorials to developers in README. 
> 
> By the way you are not owner but contributer for this package right?

the current callback doesn't bring any information from native side, can't even distinguish between empty data and error. I want it at least can return some errors from native side if not crush. 

I'm not, just a random active nerd for this  package.
