### ISSUE TITLE
How to stop step counting when app is Close

### ISSUE THREAD

**Issue by patelrushabh** [StasDoskalenko/react-native-google-fit#184]
Google fit counting steps when app is close can we stop that ? I want steps count only when app is in Background and Open.

**Comment by xuananpham93** [comment]
Do you have any suggestions?

**Comment by mhashim6** [comment]
Use `GoogleFit.removeListeners` in `componentWillUnmount`.

**Comment by patelrushabh** [comment]
@mhashim6 i tried with this but not working it is still counting steps when app is close.
 `componentWillUnmount(){`
      GoogleFit.unsubscribeListeners()
      GoogleFit.removeListeners()
    }`

**Comment by mhashim6** [comment]
> @mhashim6 i tried with this but not working it is still counting steps when app is close.
> 
>  `componentWillUnmount(){
> 
>       GoogleFit.unsubscribeListeners()
> 
>       GoogleFit.removeListeners()
> 
>     }`

Do you mean you want to stop Google Fit itself from counting, or just your app from listening?

If it's the former then it's not possible. Maybe you want to use a _pedometer_ package instead to count live steps when your app is being used.
