### ISSUE TITLE
RNGooglefit.getdailystepcountsamples got 4 arguments, expected 5

### ISSUE THREAD

**Issue by mattyx96** [StasDoskalenko/react-native-google-fit#185]
I upgraded the version to 0.14.0 from the 0.10.0

When I try to call the getdailystepcountsamples function

```
                const options = {
                    startDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), 
                    endDate: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
                };

                this.setState({status: 'loading'});

                GoogleFit.getDailyStepCountSamples(options)
                    .then((res) => {
                 
                    ....
```

I got this error:
<img src="https://user-images.githubusercontent.com/29901828/91369238-975d9b80-e80b-11ea-81a2-5d1443376a16.png" width="500">

I saw that are available also some other methods that I could use for the same result: getWeeklySteps() and getDailySteps() but if try to call one of them a warning says: "_reactNativeGoogleFit.default.getDailySteps is not a function".

I tried also to reset cache, do a gradlew clean, uninstall and reinstall the library. Am I missing something?

**Comment by rodriigovieira** [comment]
I'm having the same isue. The `getDailySteps` and `getWeeklySteps` aren't working for me.

**Comment by mattyx96** [comment]
Seems that now works after a `react-native link`
