### ISSUE TITLE
getBloodPressureSamples failing  to retrieve data  and  throwing HeartRate error !!

### ISSUE THREAD

**Issue by wafa7abbes** [StasDoskalenko/react-native-google-fit#189]
getBloodPressureSamples is failing  to retrieve data  and  throwing HeartRate error saying that : "
There is no any heart rate data for this period"

going through the java module  of  this library shows that  the bloodPressure  is calling  for heartRate methods and modules everywhere.

but even  so this call is not  coming back  with the heartRate  results, but the  the heartRate error.

anyone is  facing this error ??? 
any suggestions  or fixes  for that ?

thank you ,

**Comment by 007486215** [comment]
Same issue, any suggestions

thank you

**Comment by aboveyunhai** [comment]
@wafa7abbes @007486215  you are missing the scope to access the blood data
add to your current scope should fix it.
![image](https://user-images.githubusercontent.com/35160613/94326654-6a6be800-ff73-11ea-9a31-00628fb0618a.png)
I was able to read the data after adding the scope.

The heartrate response from `getBloodPressureSamples` is definitely an issue
