### ISSUE TITLE
con.google.step_count.delta requires android.permission.ACTIVITY_RECOGNITION

### ISSUE THREAD

**Issue by marcoautiero** [StasDoskalenko/react-native-google-fit#191]
The issue is on Android 10, on Android => 9 doesn't appear

This is the code that I'm using, I'm calling `GoogleFit.onAuthorize`, `GoogleFit.observeSteps`, `GoogleFit.startRecording` and `GoogleFit.getDailyStepCountSamples`
```
const options = {
                scopes: [
                    Scopes.FITNESS_ACTIVITY_READ_WRITE,
                    Scopes.FITNESS_BODY_READ_WRITE,
                ],
            }

            GoogleFit.authorize(options)
                .then(authResult => {
                    if (authResult.success) {
                        GoogleFit.onAuthorize(() => {
                            GoogleFit.observeSteps((steps)=>{
                                Reactotron.log("observe steps")
                            });
                        });
                        GoogleFit.startRecording((callback) => {
                            const options = {
                                startDate: dbGetResult.stepDataAuthDate, // required ISO8601Timestamp
                                endDate: new Date().toISOString() // required ISO8601Timestamp
                            };
                            GoogleFit.getDailyStepCountSamples(options, (err, res) => {
                                if (err) {
                                    reject("Error here")
                                }
                                const steps = res[0].steps.length != 0 ? res[0].steps : res[1].steps.length != 0 ? res[1].steps : res[2].steps.length ? res[2].steps : "/";
                                console.log(steps);
                                let updatedData = stepsInObject(steps);
                                resolve(updatedData);
                            });
                        })
                    } else {
                        console.log(authResult)
                    }
                })
                .catch(() => {
                    console.log(authResult)
                })
```

**Comment by MyroslavVikhot** [comment]
Same problem, any idea?

**Comment by olafur-andri-hr** [comment]
I had a similar problem with another fit package I was using. Here are the steps I took to fix them:

1. Added `<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>` to `android/app/src/main/AndroidManifest.xml` and `android/app/src/debug/AndroidManifest.xml`. I'm not sure if the debug one is necessary or not, however. I'll have to check on that.
2. Installed a package called `react-native-permissions` and used that to request permissions for ACTIVITY_RECOGNITION. [You can find information about the package here](https://www.npmjs.com/package/react-native-permissions). The reason I didn't use `PermissionsAndroid`, the native permissions handler in react native, is that it didn't include ACTIVITY_RECOGNITION for some reason.

And that's all. Hope this helps!

**Comment by marcoautiero** [comment]
> I had a similar problem with another fit package I was using. Here are the steps I took to fix them:
> 
> 1. Added `<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>` to `android/app/src/main/AndroidManifest.xml` and `android/app/src/debug/AndroidManifest.xml`. I'm not sure if the debug one is necessary or not, however. I'll have to check on that.
> 2. Installed a package called `react-native-permissions` and used that to request permissions for ACTIVITY_RECOGNITION. [You can find information about the package here](https://www.npmjs.com/package/react-native-permissions). The reason I didn't use `PermissionsAndroid`, the native permissions handler in react native, is that it didn't include ACTIVITY_RECOGNITION for some reason.
> 
> And that's all. Hope this helps!

How the ACTIVITY_RECOGNITION permission request is handled on Android <= 9 ?

**Comment by olafur-andri-hr** [comment]
> How the ACTIVITY_RECOGNITION permission request is handled on Android <= 9 ?

I'm not sure. I've currently only tested my solution on a phone running Android 10. I have another phone with Android 9 on it and will test it either today or tomorrow. I'll let you know about how it goes, but I strongly suspect my solution to work on Android 9 as well. As for earlier versions of Android, I have to say I'm not sure..

**Comment by aboveyunhai** [comment]
@marcoautiero  You are probably missing the scopes.  Those scopes you are using are actually `WRITE` only. I temp to fix them in next merge. Add these should fix your issues.
```
    Scopes.FITNESS_ACTIVITY_READ,
    Scopes.FITNESS_BODY_READ,
```

**Comment by marcoautiero** [comment]
> FITNESS_ACTIVITY

I'm using read and write scopes, not only write.

**Comment by aboveyunhai** [comment]
> @aboveyunhai 
> 
> I'm using read and write scopes, not only write.

add recognition permission to manifest file for Android 10. Android 9 or below is auto guaranteed.

**Comment by fancydevpro** [comment]
> How the ACTIVITY_RECOGNITION permission request is handled on Android <= 9?

ACTIVITY_RECOGNITION is unavailable on Android 9 or below, so you need to check the Android API level.
You can use [getApiLevel](https://github.com/react-native-device-info/react-native-device-info#getapilevel) from react-native-device-info.

```es6
const apiLevel = await getApiLevel();
if (apiLevel >= 10) {
 // check ACTIVITY_RECOGNITION permission and init google fit on grant
} else {
 // init google fit
}
```

**Comment by swizes** [comment]
> > How the ACTIVITY_RECOGNITION permission request is handled on Android <= 9?
> 
> ACTIVITY_RECOGNITION is unavailable on Android 9 or below, so you need to check the Android API level. You can use [getApiLevel](https://github.com/react-native-device-info/react-native-device-info#getapilevel) from react-native-device-info.
> 
> ```js
> const apiLevel = await getApiLevel();
> if (apiLevel >= 10) {
>  // check ACTIVITY_RECOGNITION permission and init google fit on grant
> } else {
>  // init google fit
> }
> ```

The api level to check is 29

https://developer.android.com/studio/releases/platforms

Android 9 -> Api Level 28
Android 10 -> Api Level 29

So if api level is 29 or above, ask for permission. Else skip asking permission

Api Level is different than Android version
