### ISSUE TITLE
I have empty array with all data from google fit

### ISSUE THREAD

**Issue by MyroslavVikhot** [StasDoskalenko/react-native-google-fit#192]
useEffect(() => {
        checkNotification()
    }, [])

    const checkNotification = async () => {
        const options = {
            scopes: [
                Scopes.FITNESS_ACTIVITY_READ,
                Scopes.FITNESS_ACTIVITY_READ_WRITE,
                Scopes.FITNESS_BODY_READ,
                Scopes.FITNESS_BODY_READ_WRITE,
             ],
        }

        // if (GoogleFit.isAuthorized === false) {
      return  GoogleFit.authorize(options.scopes)
            .then(authResult => {
                if (authResult.success) {
                    test()
                } else {
                    console.log('error')
                }
            })
            .catch((error) => {
                console.log('error2', error)
            })

    }

    const test = () => {
        // request(PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION).then((result) => {
            const options = {
                startDate: "2017-01-01T00:00:17.971Z", // required ISO8601Timestamp
                endDate: new Date().toISOString(), // required ISO8601Timestamp
                bucketUnit: "DAY",  
                bucketInterval: 1,
              };
              
              GoogleFit.getDailyStepCountSamples(options)
               .then((res) => {
                   console.log('Daily steps >>> ', res)
               })
               .catch((err) => {console.warn(err)})
        // });
    }

this code or any another all time return me empty arrays!

**Comment by MyroslavVikhot** [comment]
Help, any idea? this code or another return me data with empty arrays
![image](https://user-images.githubusercontent.com/69626892/96111968-96cbb200-0eea-11eb-8a59-f7af745ba832.png)

**Comment by aboveyunhai** [comment]
Everything looks good to me. Do you have any data on your googlefit app or install the Google fit app? Note that the api is to get data from the app unless you call the record function to start tracking data from local device.

**Comment by HugoChengMyC** [comment]
im not gettin any data back either, i have google fit installed on my actual device and this is the log i get
`021-02-05 09:45:19.213 31679-31806/com.molecularyou.actionplan.v1 D/OpenGLRenderer:   HWUI Binary is  enabled
2021-02-05 09:45:19.214 31679-31806/com.molecularyou.actionplan.v1 D/OpenGLRenderer:   HWUI Binary is  enabled
2021-02-05 09:45:20.716 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: onSuccess()
2021-02-05 09:45:20.716 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit:   +++ Number of buckets: 1
2021-02-05 09:45:20.724 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: onSuccess()
2021-02-05 09:45:20.724 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit:   +++ Number of buckets: 1
2021-02-05 09:45:20.726 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 	Data point:
2021-02-05 09:45:20.726 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		Type : com.google.step_count.delta
2021-02-05 09:45:20.729 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		Start: 2021-02-05T07:10:09.713-0800
2021-02-05 09:45:20.732 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		End  : 2021-02-05T07:58:27.561-0800
2021-02-05 09:45:20.732 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		Field: steps Value: 374
2021-02-05 09:45:20.733 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: onSuccess()
2021-02-05 09:45:20.734 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit:   +++ Number of buckets: 1
2021-02-05 09:45:20.735 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 	Data point:
2021-02-05 09:45:20.735 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		Type : com.google.step_count.delta
2021-02-05 09:45:20.737 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		Start: 2021-02-05T07:10:09.713-0800
2021-02-05 09:45:20.739 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		End  : 2021-02-05T08:38:16.561-0800
2021-02-05 09:45:20.739 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: 		Field: steps Value: 431
2021-02-05 09:45:20.780 31679-31838/com.molecularyou.actionplan.v1 I/ReactNativeJS: 'DAYIL STEP RESULT ANDROID:', { source: 'com.xiaomi.hm.health', steps: [], rawSteps: [] }`

**Comment by aboveyunhai** [comment]
> im not gettin any data back either, i have google fit installed on my actual device and this is the log i get
> `021-02-05 09:45:19.213 31679-31806/com.molecularyou.actionplan.v1 D/OpenGLRenderer: HWUI Binary is enabled 2021-02-05 09:45:19.214 31679-31806/com.molecularyou.actionplan.v1 D/OpenGLRenderer: HWUI Binary is enabled 2021-02-05 09:45:20.716 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: onSuccess() 2021-02-05 09:45:20.716 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: +++ Number of buckets: 1 2021-02-05 09:45:20.724 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: onSuccess() 2021-02-05 09:45:20.724 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: +++ Number of buckets: 1 2021-02-05 09:45:20.726 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Data point: 2021-02-05 09:45:20.726 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Type : com.google.step_count.delta 2021-02-05 09:45:20.729 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Start: 2021-02-05T07:10:09.713-0800 2021-02-05 09:45:20.732 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: End : 2021-02-05T07:58:27.561-0800 2021-02-05 09:45:20.732 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Field: steps Value: 374 2021-02-05 09:45:20.733 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: onSuccess() 2021-02-05 09:45:20.734 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: +++ Number of buckets: 1 2021-02-05 09:45:20.735 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Data point: 2021-02-05 09:45:20.735 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Type : com.google.step_count.delta 2021-02-05 09:45:20.737 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Start: 2021-02-05T07:10:09.713-0800 2021-02-05 09:45:20.739 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: End : 2021-02-05T08:38:16.561-0800 2021-02-05 09:45:20.739 31679-31679/com.molecularyou.actionplan.v1 I/RNGoogleFit: Field: steps Value: 431 2021-02-05 09:45:20.780 31679-31838/com.molecularyou.actionplan.v1 I/ReactNativeJS: 'DAYIL STEP RESULT ANDROID:', { source: 'com.xiaomi.hm.health', steps: [], rawSteps: [] }`

If you check your log, there are indeed some fitness step data. There are 3 sources, one of them should include your data.

**Comment by HugoChengMyC** [comment]
yeah thereis from the device, which means theres an issue with the React-native call , the promise returns empty arrays  'DAYIL STEP RESULT ANDROID:', { source: 'com.xiaomi.hm.health', steps: [], rawSteps: [] } 

here is what i did on my end`   if (platform == 'android' && GoogleFit.isAuthorized) {
                let today = new Date();
                GoogleFit.getDailySteps(today.toISOString()).then((result) => {
                    if (result) {
                        console.log('DAYIL STEP RESULT ANDROID:', result[0]);
                        //setDailySteps(result[0].steps.length ? result[0].steps : 0)
                    }

                }).catch((error) => {
                    console.log('daily step count error', error);
                    Alert.alert('daily step android failed', error.toString());
                })
                //use android api for step count
                return;
            }`

**Comment by aboveyunhai** [comment]
@HugoChengMyC There are 3 data sources, you might want to check other two sources. `"Xiaomi"` seems like a specific solution for Xiaomi devices and I am not sure it still works nowadays without a real device, So you should expect it's empty all the time. 
Try to `console.log(result)` to check the entire result;
