### ISSUE TITLE
Are there any plans to migrate away from using the deprecated GoogleApiClient and adopting the newer GoogleApi-based APIs?

### ISSUE THREAD

**Issue by lemonkey** [StasDoskalenko/react-native-google-fit#196]
I'm trying to track down a rare crash and it seems to be related to disconnecting from Google Fit but it's not easily reproduced.

When the crash occurs, I'm seeing:

```
11-06 15:27:49.240 23911 26801 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zag(com.google.android.gms.common.ConnectionResult)' on a null object reference
```

I've already tried wrapping the disconnect() call that happens in the GoogleFitManager class (v0.14.0) in a try/catch and a few other defensive coding additions and it's not getting caught.

I have to wonder if it might not be caused by the fact that the latest version of react-native-google-fit is using a deprecated way of interacting with the GoogleAPIs.

See:
* https://android-developers.googleblog.com/2017/11/moving-past-googleapiclient_21.html

**Comment by aboveyunhai** [comment]
The reason why I made a big rewrite to the current codes is to migrate all the deprecated apis eventually. 
I have to understand the current auth logic and why some of "trivial" codes exists before I do any migrations,  since I am not an android dev or java expert . 
If you desperately want to fix the issue probably you can make a PR to help improve this lib.

**Comment by lemonkey** [comment]
@aboveyunhai thanks for the explanation

**Comment by gel-prog** [comment]
I am getting this error every time the app is freshly installed. 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult(android.content.IntentSender, int, android.content.Intent, int, int, int)' on a null object reference
    at com.google.android.gms.common.ConnectionResult.startResolutionForResult
    at com.reactnative.googlefit.GoogleFitManager$1.onConnectionFailed(GoogleFitManager.java:172)
    at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionFailure
    at com.google.android.gms.common.api.internal.zzav.zzc
    at com.google.android.gms.common.api.internal.zzaj.zze
    at com.google.android.gms.common.api.internal.zzaj.zza
    at com.google.android.gms.common.api.internal.zzaj.zza
    at com.google.android.gms.common.api.internal.zzar.zzaq
    at com.google.android.gms.common.api.internal.zzbe.zzc
    at com.google.android.gms.common.api.internal.zzbf.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
