### ISSUE TITLE
  Error: 4: The user must be signed in to make this API call. getSleepSamples()

### ISSUE THREAD

**Issue by Ransoy** [StasDoskalenko/react-native-google-fit#198]
Hi I encounter this error 'The user must be signed in to make this API call', using the given sample regarding with the sleep method . However, the authResult is {"success":true}, not sure why it says the user is not logged in.  but when I use the other function it returns ok. 

`const options = {
  scopes: [
    Scopes.FITNESS_ACTIVITY_READ,
    Scopes.FITNESS_ACTIVITY_WRITE,
    Scopes.FITNESS_BODY_READ,
    Scopes.FITNESS_BODY_WRITE,
    Scopes.FITNESS_SLEEP_READ,
  ],
}
GoogleFit.authorize(options)
  .then(authResult => {
    if (authResult.success) {
      const opt = {
        startDate: '2020-01-01T12:33:18.873Z', // required, timestamp or ISO8601 string
        endDate: new Date().toISOString(), // required, timestamp or ISO8601 string
      };

      GoogleFit.getSleepSamples(opt).then((res) => {
        console.log(res)
      });
    } else {
        console.log(authResult.message);
    }
  })
  .catch(() => {
     console.log("AUTH_ERROR");
  })`

thanks for updates

**Comment by aboveyunhai** [comment]
@Ransoy  Can you test this merge with only fitness and sleep scope to see if it works?

**Comment by Ransoy** [comment]
@aboveyunhai ok  thanks for the updates, will test

**Comment by Ransoy** [comment]
@aboveyunhai  thank you for the updates the issue is now fix, it works without the nutrition scope, but I have another concerned, the result of granulity is empty .

![empty granulatiry](https://user-images.githubusercontent.com/11657977/98893428-5bb6a180-24dd-11eb-9ee1-6e033627fabb.png)

but when I tested it to oauth playground i got this result.it display the sleep stages


![sleep stages](https://user-images.githubusercontent.com/11657977/98893593-b05a1c80-24dd-11eb-97c3-2a30b0d65d3c.png)

**Comment by aboveyunhai** [comment]
`granulity` should be empty as expect because it can be added via `addSleep()` function which it's not implemented currently. It is just a reserved field for the future,

**Comment by Ransoy** [comment]
i see currently the implementation by default the granulity is empty for now.
@aboveyunhai from the example above I'm using [Sleep as Android](https://play.google.com/store/apps/details?id=com.urbandroid.sleep&hl=en&gl=US) app for data simulation but you can added manually using there rest api.

https://developers.google.com/fit/scenarios/write-sleep-data

**Comment by aboveyunhai** [comment]
@Ransoy  I just successfully implement the `saveSleep()` function and able to get data from `granulity` with the current function. It's a little bit weird for me that you can get the start and end date but empty for `granulity`.

**Comment by Ransoy** [comment]
cool can you commit the changes so I can implement on my end.
I using this https://developers.google.com/oauthplayground/ to verify data.
thanks

**Comment by aboveyunhai** [comment]
I was able to read the data from the playground after data sync. So you are probably missing something.

**Comment by Ransoy** [comment]
hi @aboveyunhai  I  was able to use the saveSleep() and get Data from granulity,Yeah I probably missed something using there rest api. but I wonder why there is no granulity data using the actual app like Sleep as Android but I was able to read the data from the playround after I sync it from the app.

**Comment by aboveyunhai** [comment]
You need to read google fit doc by yourself, it's just a trivial option even Google does not include that data in its own fit app. 
I just included it in case if someone needs it as I rewrote the sleep function.

**Comment by danutz30** [comment]
Hello @aboveyunhai I'm using in my react-native app this library. When I request data from GoogleFit.getDailyStepCountSamples(opt)
.then((res) => {
console.log('Daily steps >>> ', res)
}). In the then part nothing is executed. Basically the promise is not reacting anyway

**Comment by danutz30** [comment]
and also for GoogleFit.getSleepSamples(opt).then((res) => {
  console.log(res)
});

**Comment by sudheer-autumn** [comment]
> Hello @aboveyunhai I'm using in my react-native app this library. When I request data from GoogleFit.getDailyStepCountSamples(opt)
> .then((res) => {
> console.log('Daily steps >>> ', res)
> }). In the then part nothing is executed. Basically the promise is not reacting anyway

@danutz30 
Me also facing same issue with below warning.

Possible Unhandled Promise Rejection (id: 2):
Error: 4: The user must be signed in to make this API call.
Error: 4: The user must be signed in to make this API call.
    at Object.promiseMethodWrapper [as getSleepSamples] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2255:36)
    at _callee15$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:383003:61)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43186:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43359:24)
    at Generator.next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43229:23)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43186:19)
    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43259:22)
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43289:13
    at tryCallTwo (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27071:7)
    at doResolve (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27235:15)

**Comment by sudheer-autumn** [comment]
> and also for GoogleFit.getSleepSamples(opt).then((res) => {
> console.log(res)
> });

@danutz30 
Me also facing same issue with below warning. Please update here if there any fix, i am stuck at here since 3 days.

Possible Unhandled Promise Rejection (id: 2):
Error: 4: The user must be signed in to make this API call.
Error: 4: The user must be signed in to make this API call.
at Object.promiseMethodWrapper [as getSleepSamples] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2255:36)
at _callee15$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:383003:61)
at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43186:19)
at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43359:24)
at Generator.next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43229:23)
at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43186:19)
at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43259:22)
at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:43289:13
at tryCallTwo (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27071:7)
at doResolve (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27235:15)

**Comment by sudheer-autumn** [comment]
> and also for GoogleFit.getSleepSamples(opt).then((res) => {
> console.log(res)
> });

@danutz30 
I followed the provided documentation and now i am able to retrieve the steps, just posting logs for your reference. refer last object to get steps value.

Daily steps >>>  
(3) [{…}, {…}, {…}]
0:
source: "com.google.android.gms:merge_step_deltas"
steps: Array(0)
length: 0
__proto__: Array(0)
rawSteps: []
__proto__: Object
1:
source: "com.xiaomi.hm.health"
steps: Array(0)
length: 0
__proto__: Array(0)
rawSteps: []
__proto__: Object
2:
source: "com.google.android.gms:estimated_steps"
steps: Array(1)
0: {date: "2020-11-21", value: 66}
length: 1
__proto__: Array(0)
rawSteps: [{…}]
__proto__: Object
length: 3
__proto__: Array(0)

**Comment by aboveyunhai** [comment]
@sudheer-autumn npm package does not include the latest fix for sleep. The temporary fix is to add `nutrition scope` when you call sleep function, or you can just directly install the package from github.

**Comment by danutz30** [comment]
@aboveyunhai when do you think the sleep part will be fixed with the right scope ? 

also I've encountered an issue with infinite loading indicator dialog  when requesting access to fit data in release mode apk 
Do you know something about this ?
