### ISSUE TITLE
Attempt to Invoke virtual method - Error

### ISSUE THREAD

**Issue by GroupXTech** [StasDoskalenko/react-native-google-fit#20]
Hello,
I'm sure it's something I'm overlooking, but I am getting this error and Not sure how to resolve it.
Exception in native call  java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnative.googlefit.StepHistory com.reactnative.googlefit.GoogleFitManager.getStepHistory()' on a null object reference
 at com.reactnative.googlefit.GoogleFitModule.getDailySteps(GoogleFitModule.java:105)
at java.lang.reflect.Method.invoke(Native Method)

My code:
      let dayStart = "2017-01-01T00:00:17.971Z"; //ISO Time String
      let dayEnd = "2017-01-01T23:59:17.971Z"; //ISO Time String
      GoogleFit.getSteps(dayStart, dayEnd);

Any help is much appreciated

**Comment by StasDoskalenko** [comment]
Hi @GroupXTech !
Could you please try 0.3.2 version? Is it resolved for you?

**Comment by GroupXTech** [comment]
I get this error now
Error:(22, 8) error: GoogleFitPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

React-native-svg had this same error and had to implement the 5 lines of code your deleted in this commit...

I wish I new Java a little better to help.

Let me know if there is any more info I can provide.

I'm using RN 0.46.2

Thank you

**Comment by raihanabbas232** [comment]
@GroupXTech I am having exactly the same issue...any suggestions???

**Comment by GroupXTech** [comment]
No problem, 
On my parent component 
I use this method:
                    let dayStart = moment(date).startOf('day').toISOString(); //ISO Time String
                    let dayEnd = moment(date).endOf('day').toISOString();//ISO Time String
                    GoogleFit.getDailyStepCountSamples(dayStart, dayEnd, (errr, res) => {
                        if (res[0].steps[0] === undefined) {
                            steps = 0
                        } else {
                            steps = res[0].steps[0].value
                        }
                        this.setState({ steps: steps });
                    });

Then on the androidAPI.js 
I had to rework your method a little: 
     getDailyStepCountSamples(startDate, endDate, callback) {
       googleFit.getDailyStepCountSamples(Date.parse(startDate), Date.parse(endDate),
           (msg) => {
               callback(msg, false);
           },
           (res) => {
               if (res.length>0) {
                   callback(false, res.map(function(dev) {
                       var obj = {};
                       obj.source = dev.source.appPackage + ((dev.source.stream) ? ":" + dev.source.stream : "");
                       obj.steps = this.buildDailySteps(dev.steps);
                       return obj;
                       }, this)
                   );
               } else {
                   callback("There is no any steps data for this period", false);
               }
           });
     }

    }


Hope that helps???? Let me know.

**Comment by StasDoskalenko** [comment]
Yes, guys all should work fine. Have you followed all official google installation guide?
And maybe some of Readme.md was outdated.

**Comment by platonish** [comment]
@GroupXTech hey, I tried your solution, but I still get the same error. I get the proper value the first time I build the app, but every subsequent time I get this error. In both cases I'm passing the ISO string generated using moment's `toISOString()` method. 
Any suggestions? I know it's been ages since your comment, but any help would be appreciated.

**Comment by platonish** [comment]
IDK if this is necessary, but calling `GoogleFit.onAuthorize()` every time seems to do the trick. I have a dashboard screen that calls 3 GoogleFit methods, so I call `GoogleFit.onAuthorize()` every time the Dashboard component mounts and I no longer face the error.

**Comment by StasDoskalenko** [comment]
@platonish try to use plain JS Date() class?
What error have you got from onAuthorize(err)?

**Comment by sykenrussel** [comment]
`const opt = {
  startDate: "2017-01-01T00:00:17.971Z", // required ISO8601Timestamp
  endDate: new Date().toISOString(), // required ISO8601Timestamp
  bucketUnit: "DAY", // optional - default "DAY". Valid values: "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "SECOND" | "MINUTE" | "HOUR" | "DAY"
  bucketInterval: 1, // optional - default 1.
};
async function fetchData() {
  const res = await GoogleFit.getDailyStepCountSamples(opt);
  console.log(res);
}
fetchData();`

This is just my code but I also get the same error. Is the documentation not updated to show how it really is supposed to be done?

**Comment by mhisham** [comment]
I think the issue appear when the user ignore the permission and your app try to get any data so `mGoogleFitManager` will be always null and crash the app
I added this condition before `mGoogleFitManager`
`if(mGoogleFitManager != null ) {`
