### ISSUE TITLE
Activity start time is wrong.

### ISSUE THREAD

**Issue by krakz999** [StasDoskalenko/react-native-google-fit#201]
When using `getActivitySamples()`, if we set the `startDate` option to higher than the returned activity's actual start date, the start date in the entry will become what we defined in the `startDate` option.

**For example**: we want to get an activity that started in 1PM and ended in 5PM.
If I call `getActivitySamples({startDate: 3PM})`, the returned activity will contain `{start: 3PM, end: 5PM}` instead of `{start: 1PM, end: 5PM}`.

Is there a way to get the actual start date of the activity, or only return activities that are "whole activities"?

**Comment by aboveyunhai** [comment]
As far as I know, google fit will chuck down your data into small interval so once you change the `bucketunit` and `bucketInterval` it can always provide the precise results from any spans. 
If you want to return whole, the only way is to change your `startDate` to 1PM, so you probably need to write your own algorithm and database if you want to achieve something like this.
