### ISSUE TITLE
Real time data

### ISSUE THREAD

**Issue by priyanka4477-ppp** [StasDoskalenko/react-native-google-fit#202]
Not able to fetch real time data for activity using getActivitySample method

let sDate = moment(new Date()).subtract(1, 'day'); //.format('YYYY,MM,D');
    let eDate = moment(new Date()); //.format('YYYY,MM,D');
    console.log(new Date(sDate) + '-----------' + eDate);

    let options = {
      startDate: new Date(
        sDate.get('year'),
        sDate.get('month'),
        sDate.get('date'),
      ).valueOf(), // required
      endDate: new Date(
        eDate.get('year'),
        eDate.get('month'),
        eDate.get('date'),
      ).valueOf(), // required

      //startDate:new Date(2020,11, 1).valueOf(),
      //endDate:new Date().valoueOf()
    };
    console.log('option=====', JSON.stringify(options));
    console.log('inBetween-----------------');
    GoogleFit.getActivitySamples(options, (err, res) => {
      console.log(err, res);
      this.saveData(res);
    });

by using this code

**Comment by aboveyunhai** [comment]
please read the documentation regarding the function, `callback` argument is not longer available.

**Comment by priyanka4477-ppp** [comment]
8 Get all activities

  let opt = {
    startDate: "2017-01-01T00:00:17.971Z", // required
    endDate: new Date().toISOString(), // required
    bucketUnit: "DAY", // optional - default "DAY". Valid values: "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "SECOND" | "MINUTE" | "HOUR" | "DAY"
    bucketInterval: 1, // optional - default 1. 
  };

  **GoogleFit.getActivitySamples(opt).then((res)=> {
    console.log(res)
  });**
  // or with async/await syntax
  async function fetchData() {
    const res = await GoogleFit.getActivitySamples(opt)；
    console.log(res);
  }

as given in this documentation i am using this highlighted method but its not giving real time data

**Comment by davidguerrerolopez** [comment]
@priyanka4477-ppp  after some debugging I was able to determine whats going on with your activity samples, looks like previously it was setup to use bucketInterval as 1 by default and bucketUnit as "SECOND" by default, now its different, not bucketUnit is "DAY" as default, so you could easily fix this by setting bucketUnit: "SECOND" in your opt object

**Comment by aboveyunhai** [comment]
@davidguerrerolopez  I believe his issue related to authentication like many other general issues if he cannot get data from other functions as well. 
bucket unit and interval only affect the result and numbers of data chunk, and has nothing to do with getting empty data.
I gonna close it for now until he has any follow-up.

**Comment by IronTony** [comment]
@aboveyunhai I did some test too and @davidguerrerolopez is right.
If I change the `bucketUnit` to `HOUR` or something else I have back the data, instead if I use `DAY` nothing works

**Comment by aboveyunhai** [comment]
> @aboveyunhai I did some test too and @davidguerrerolopez is right.
> If I change the `bucketUnit` to `HOUR` or something else I have back the data, instead if I use `DAY` nothing works

Glad you can sort it out! Just want to further note that Javascript date is extremely tricky and fitness data also has a start date and end date from each data. That might be the reason sometimes you didn't get the data you want due to timezone,etc. 
The current package has a `moment.js` dependency which i believe it's overkill and too large for our case, and I believe it should be replaced by another smaller date library in the future. But currently you can use the package to set your date for best result.
