### ISSUE TITLE
Google fit sleep datatype is missing from Android.Gms.Fitness.Data.DataType

### ISSUE THREAD

**Issue by wafa7abbes** [StasDoskalenko/react-native-google-fit#206]
Google fit sleep datatype is missing from Android.Gms.Fitness.Data.DataType
  TYPE_SLEEP_SEGMENT is  not recognized  in the dataType  object,  as result  the build is  failing  when  using the google  fit  library  and I can  not fetch  sleep  data !

any clue for this  please ?

**Comment by aboveyunhai** [comment]
Just from personal debug experience, you can download Android studio and use it to open your android folder as project.
Usually you can get the idea why your build failed because it will highlight some incompatible codes with your current compile version.

**Comment by wafa7abbes** [comment]
hello again, 

Thank you for your reply,  the thing is the new update that came on 19 October 2020 brought some radical changes  in the data types and scopes.
so  for the sleep data now it has its own scope and its own data type that is not recognized, it  is unkown  during  compiling  and  building the system.

**Comment by aboveyunhai** [comment]
#204 do you manually set your fitness version?

**Comment by wafa7abbes** [comment]
Not for the begging,  but I tried later  to turn it into many different versions, but as well  it didn't work.

**Comment by Aurangempire** [comment]
Getting below error: 
Cannot resolve symbol 'TYPE_SLEEP_SEGMENT'

But here: 
[https://developers.google.com/fit/datatypes/sleep?hl=en#android](url)

Data type object | TYPE_SLEEP_SEGMENT

Mentioned in the DOC.

Any Solution?
