### ISSUE TITLE
Support for writing activities to Google Fit

### ISSUE THREAD

**Issue by egorshulga** [StasDoskalenko/react-native-google-fit#208]
Hey @StasDoskalenko, it's a great library! I'm considering to use it in my current project.

However, I would need write functionality for activities, I guess that's a missing part. I've seen PR #85, could you give me a clue, what is the difference between activities and workouts?

**Comment by aboveyunhai** [comment]
Activity is basically everything including workouts. 
https://developers.google.com/fit/datatypes/activity
In terms of implementation, add/write functionality for activities might include all physical activities except sleep and nutrient data which I believed it's already implemented.

**Comment by egorshulga** [comment]
Thanks @aboveyunhai! Will take a look at it
