### ISSUE TITLE
getSleepSamples causes the app to crash 

### ISSUE THREAD

**Issue by jaikantshikray** [StasDoskalenko/react-native-google-fit#213]
java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

**Comment by aboveyunhai** [comment]
it seems like a java version issues. Can you provide your `android/build.gradle` in case if you change anything.

**Comment by jaikantshikray** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
         classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.28.1'
        classpath 'com.google.firebase:perf-plugin:1.3.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 29
                buildToolsVersion "29.0.3"
            }
        }
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            url  "https://adcolony.bintray.com/AdColony"
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
// apply plugin: "io.fabric"
// apply plugin: "com.google.firebase.firebase-perf"

**Comment by jaikantshikray** [comment]
do i need to update my JAVA version ?

**Comment by aboveyunhai** [comment]
@jaikantshikray  It looks good to me. Stream is included in api 24,
I am not sure if you need to change it to `minSdkVersion = 24` but then some of devices you have to give up

**Comment by jaikantshikray** [comment]
yes i am testing on sdk 23

**Comment by jaikantshikray** [comment]
is there any solution either by downgrading the google fit version so i can get that working ?

**Comment by jaikantshikray** [comment]
i just need sleep data for google fit

**Comment by aboveyunhai** [comment]
I believe `version 14.1` can get sleep data with lower version but the implementation is different than the latest so I am not sure unless someone came out some compatible build for different version.

**Comment by jaikantshikray** [comment]
ok thank you for your help
