### ISSUE TITLE
androidx issue

### ISSUE THREAD

**Issue by yahyamokaied** [StasDoskalenko/react-native-google-fit#214]
can you please update all files in 
android/src/main/java/com/reactnative/googlefit/

from
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
to
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

**Comment by aboveyunhai** [comment]
@yahyamokaied Good catch. Does it cause any compiler issues explicitly.
It seems like a lot of problems has to do with different version of android. So I can take a peek at them,

**Comment by yahyamokaied** [comment]
its working well when I update imports to androidx
but I need to update them manually on every npm install
and many bugs in android studio if I didn't update them)
also when I uploade the app to AppCenter facing same issue

**Comment by aboveyunhai** [comment]
inside your `android/gradle.properties`
check if you have this line 
```
android.useAndroidX=true
```
Try if it can automate process without change the code.
Of course I will change them later since some of files were already migrated to androidX

**Comment by aboveyunhai** [comment]
@yahyamokaied  actually I hadn't found any lines you mentioned from latest version, So I assume you are using some old version. 
Without breaking your app, just try out my suggestion to auto the process instead of upgrading your npm version.
