### ISSUE TITLE
Showing null is not an object googleFit.isAuthorized when authorizing

### ISSUE THREAD

**Issue by jitendrahpatwa** [StasDoskalenko/react-native-google-fit#215]
Integrated this plugin to use google fit auth but fails when connecting it return following output.
 Object {
    "message": "null is not an object (evaluating 'googleFit.isAuthorized')",
  "success": false,
}
Using following code.

const connectgooglefit = async () => {
        const options = {
            scopes: [
              Scopes.FITNESS_ACTIVITY_READ,
              Scopes.FITNESS_ACTIVITY_WRITE,
              Scopes.FITNESS_BODY_READ,
              Scopes.FITNESS_BODY_WRITE,
              Scopes.FITNESS_SLEEP_READ,
              Scopes.FITNESS_SLEEP_WRITE,
            ],
        }
        // console.log('GoogleFitGoogleFitGoogleFitGoogleFit',GoogleFit, GoogleFit.isAuthorized)
        GoogleFit.authorize(options)
        .then((res) => {
          console.log('authorized >>>', res)
          alert(""+GoogleFit.isAuthorized + " Response received:\n" + JSON.stringify(res));
        })
        .catch((err) => {
          console.log('err >>> ', err)
          alert("Error connecting:\n" + err);
        })
        // GoogleFit.checkIsAuthorized().then((d) => {
        //     console.log('GFit', d) // Then you can simply refer to `GoogleFit.isAuthorized` boolean.
        // }).catch(e=>{
        //     console.log('err',e)
        // })
    }

Please suggest what is missing here.

**Comment by denishgcirklestudio** [comment]
Getting same issue here too. I hope lib doc. will get updated ASAP with full details. Also we are not aware from what kind of error it will throw in authorization so please update lib with specific error message so i can update my code and check.

Thanks.

**Comment by aboveyunhai** [comment]
It seems like you don't config the authentication correctly. That's why you get the null object.
For `React Native`, the `debug.keystore`  is located in `android\app`.
Then you should follow instruction link https://developers.google.com/fit/android/get-api-key#find_your_apps_certificate_information to setup your development. Whatever files mentioned by Google instructions are all located inside the `android` folder. For production and upload onto app store, you need to search React Native production build from RN official website.

**Comment by denishgcirklestudio** [comment]
> It seems like you don't config the authentication correctly. That's why you get the null object.
> For `React Native` project, the `debug.keystore` locates in `your_project\android\app`.
> Then you should follow instruction link https://developers.google.com/fit/android/get-api-key#find_your_apps_certificate_information to setup your development. Whatever files mentioned by Google instructions are all locate inside the `android` folder. For production and upload onto app store, you need to search React Native production build from RN official website because there are separated keystores for production and app store .

Let me recheck this.

**Comment by aboveyunhai** [comment]
> > It seems like you don't config the authentication correctly. That's why you get the null object.
> > For `React Native` project, the `debug.keystore` locates in `your_project\android\app`.
> > Then you should follow instruction link https://developers.google.com/fit/android/get-api-key#find_your_apps_certificate_information to setup your development. Whatever files mentioned by Google instructions are all locate inside the `android` folder. For production and upload onto app store, you need to search React Native production build from RN official website because there are separated keystores for production and app store .
> 
> Let me recheck this.
> 
> **Edited:**
> 
> I've tried this and got resolution for null somehow but the new problem is, i'm getting below response in return.
> `{"message": "Authorization cancelled", "success": false}`
> 
> Lib calls authorise function in which it returns `SIGN_IN_REQUIRED` message and start resolution activity which presents AUTH popup of google. When i select my account, it returns me above message.
> 
> I've checked `onActivityResult` response, which returns `resultCode` 0 and nothing in `data`
> 
> Am i missing something ?

Yes. The Popup doesn't mean your setup is all correct but close, You should have an OAuth 2.0 Client IDs inside your api console after the setup, I believe you can also add scopes during the setup, which will includes your package name and SHA-1.
SHA-1 is obtained from the keytool command that you called inside your `android/app` folder or whatever the `keystore` located;
Package name should be used inside `AndroidManifest.xml`. I pretty sure you are missing something. If you 100% sure you done all, maybe try to clean android cache and rebuild your project, but most of times I found it's that ppl always misconfig somewhere during the auth process. 
I used to have some hard time to set the package up, but the difficulty is really from the google instruction instead of the package itself. That's why you see a lot of issues related to the authentication but neither the maintainer and I were able to answer.

**Comment by denishgcirklestudio** [comment]
**Boom!!** I see. I got what is issue about. If you have `debug.keystore` then remove it first. Then if you have set debug keystore's creds in `build.gradle` file then remove it.

```
signingConfigs {
  /* debug {
    storeFile file('...')
    storePassword '...'
    keyAlias '...'
    keyPassword '...'
  } */
  ...
}
```

After completing those steps, uninstall app from device, clean project and run the app. It will be in working condition.

However, i have resolved this issue, after selecting account, i'm getting next dialog which takes forever to load. Still trying to resolution for the same.

I must check that in my real device rather than checking in Emulator. **(Will update you about this too when get back to work.)**

**Comment by jitendrahpatwa** [comment]
> > > It seems like you don't config the authentication correctly. That's why you get the null object.
> > > For `React Native` project, the `debug.keystore` locates in `your_project\android\app`.
> > > Then you should follow instruction link https://developers.google.com/fit/android/get-api-key#find_your_apps_certificate_information to setup your development. Whatever files mentioned by Google instructions are all locate inside the `android` folder. For production and upload onto app store, you need to search React Native production build from RN official website because there are separated keystores for production and app store .
> > 
> > 
> > Let me recheck this.
> > **Edited:**
> > I've tried this and got resolution for null somehow but the new problem is, i'm getting below response in return.
> > `{"message": "Authorization cancelled", "success": false}`
> > Lib calls authorise function in which it returns `SIGN_IN_REQUIRED` message and start resolution activity which presents AUTH popup of google. When i select my account, it returns me above message.
> > I've checked `onActivityResult` response, which returns `resultCode` 0 and nothing in `data`
> > Am i missing something ?
> 
> Yes. The Popup doesn't mean your setup is all correct but close, You should have an OAuth 2.0 Client IDs inside your api console after the setup, which will includes your package name and SHA-1. I believe you can also add scopes during the setup.
> SHA-1 is obtained from the keytool command that you called inside your `android/app` folder or whatever the `keystore` located;
> Package name should be used inside `AndroidManifest.xml`. I pretty sure you are missing something. If you 100% sure you done all, maybe try to clean android cache and rebuild your project, but most of times I found it's that ppl always misconfig somewhere during the auth process.
> I used to have some hard time to set the package up, but the difficulty is really from the google instruction instead of the package itself. That's why you see a lot of issues related to the authentication but neither the maintainer and I were able to answer.


Tried with approach in Expo, I've added google configuration appkey/clientid in app.json using following node in android or ios
"googleServicesFile": "./google-services.json",
and included this file in app root directory.
And/or also kept google client secret file in the root directory but there is remain same issue in Expo environment as well as in artifact build.

**Moreover,** I then Used with Oauth of google service with appId/clientid. I have enable Fit API from google console and authorize with Google including FIT services/api calls.

Here is the code that I have used to authenticate Google FIT using import * as GoogleSignIn from 'expo-google-sign-in';.
`
...
**try {
    console.log('Google async');
    await GoogleSignIn.initAsync({
    	clientId: AppConfig.keys.google, // '<YOUR_IOS_CLIENT_ID>',
    	scopes: [
    		'https://www.googleapis.com/auth/fitness.activity.read',
            'https://www.googleapis.com/auth/fitness.activity.write',
            'https://www.googleapis.com/auth/fitness.body.read',
            'https://www.googleapis.com/auth/fitness.body.write',
            'https://www.googleapis.com/auth/fitness.nutrition.read',
            'https://www.googleapis.com/auth/fitness.nutrition.write'
    	]
    });
    await GoogleSignIn.askForPlayServicesAsync();
    const { type, user } = await GoogleSignIn.signInAsync();
    if (type === 'success') {
      const user = await GoogleSignIn.signInSilentlyAsync();
      console.log('user',user);
      alert('connected\n'+JSON.stringify(user))
    }
} catch ({ message }) {
  alert('login: Error:' + JSON.stringify(message));
}**
`
And its successfully get authenticate in app asking following permission that in scopes that have mentioned.

But now, main pinpoint is , this is right approach that I've implemented. Also if  we want user activity detail such as daily step count, sleep hours, nutrition , etc that then only be able to fetch through fitness API's by async fetch?

Its good to have if this react-native-google-fit plugin will do this.

Please suggest here.

**Comment by denishgcirklestudio** [comment]
> However, i have resolved this issue, after selecting account, i'm getting next dialog which takes forever to load. Still trying to resolution for the same.
> 
> I must check that in my real device rather than checking in Emulator. **(Will update you about this too when get back to work.)**

![This is the issue](https://user-images.githubusercontent.com/59468606/108840278-23565180-75fc-11eb-9456-4a8adab64b43.png)

I have this dialog on screen after selection of account for forever. Can someone help me with this ?

**Comment by jitendrahpatwa** [comment]
> > However, i have resolved this issue, after selecting account, i'm getting next dialog which takes forever to load. Still trying to resolution for the same.
> > I must check that in my real device rather than checking in Emulator. **(Will update you about this too when get back to work.)**
> 
> ![This is the issue](https://user-images.githubusercontent.com/59468606/108840278-23565180-75fc-11eb-9456-4a8adab64b43.png)
> 
> I have this dialog on screen after selection of account for forever. Can someone help me with this ?

If the scopes were configured appropriately it might may not affect this kind of issue, post must have Fitness API enabled from console.

**Comment by aboveyunhai** [comment]
I think you have to opt out from expo if you want to use any native module unless something is changed.

**Comment by denishgcirklestudio** [comment]
**Hurrah...!!** Now it's finally resolved. Issue was when i added my app in `OAuth consent screen`, i missed to add **test user** and also forgot to add what api should be allowed in `OAuth consent screen` section. So whenever you get this kind of issue, please check it from start to end.

 If you have already created app inside console and want to update, go inside `API & Services > OAuth consent screen` where you'll see button to edit app besides `Application Name`. Click that, read each steps instruction and pursue further. At last it will ask you to add api which you want to access from the application using google fit api. So add those by searching it. 

[Adding Test User](https://user-images.githubusercontent.com/59468606/108961530-7e8c5080-769d-11eb-92aa-1326a3a188fc.png)

**Comment by aboveyunhai** [comment]
highly don't suggest the above solution by removing `debugkeystore` file and manually add into `build.gradle`.
You should be able to generate the SHA-1 from `debug.keystore` from Google instruction and use the `sha-1` in google console without need to change the particular section in `build.gradle`, and even adding test user,
and OP clearly missed the section. 
In meantime it might work on development mode, but you will likely encounter same problem on production.

**Comment by OshedheMunasinghe** [comment]
Sorry @aboveyunhai I need to open this post. 
This is way too complex to fix the problem.
So I have read carefully steps from your installation and I must say it needs to refresh some text.
I have generated SHA-1 , I did as you written that we should *not* delete debug.keystore if expo has generated automatic one. 

In the installation document you wrote on the last step "there is a two way"
two way what? .... You just explain one way. 
You didn't explain what to add test user so I tried to add my own email adress.

So I have went to your example code and it is 3 years old.....
`
import {AppRegistry, StyleSheet, Text, View} from 'react-native';
import GoogleFit, {Scopes} from 'react-native-google-fit'
import {useEffect} from "react";

export default function App() {
    useEffect(() => {

        const options = {
            scopes: [
                Scopes.FITNESS_ACTIVITY_READ,
                Scopes.FITNESS_ACTIVITY_WRITE,
                Scopes.FITNESS_BODY_READ,
                Scopes.FITNESS_BODY_WRITE,
            ]
        }
        GoogleFit.authorize(options)
            .then(authResult =>{
               if (authResult.success){
                   console.log('AUTH SUCESS')
               }else {
                   console.error('AUTH DENIED', authResult)
               }
            })
            .catch(() => {
                console.log('AUTH_ERROR')
            })
    });



    return (
        <View style={styles.container}>
            <Text style={styles.welcome}>
                Welcome to React Native!
            </Text>
            <Text style={styles.instructions}>
                To get started, edit index.js
            </Text>
            <Text style={styles.instructions}>
                Double tap R on your keyboard to reload,{'\n'}
                Shake or press menu button for dev menu
            </Text>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
    },
});
`

Still, **it denied Auth.**

So I tried to publish the app
didn't work it either.

So I went to OAuth consent screen -> Edit App -> Scrope and then add scopes almost everything

it didn't even show a sign of the app.....

So my question is 
does it really work in Expo 
is it a problem with React native 0.64?
do I need to link?
what does test users do? If I add my own mail address shall I go to Gmail and check?

I am confused.

**Comment by aboveyunhai** [comment]
@OshedheMunasinghe  No, it does not work in Expo because it's an `native module`, you had to eject from Expo in order to use it. 
If you still want to use it, check this: https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md#demo-walkthrough-development-setup
