### ISSUE TITLE
I am getting empty arrray for getActivity , getDistance, getSleep and Heart

### ISSUE THREAD

**Issue by shraddha242** [StasDoskalenko/react-native-google-fit#216]
const distance = await GoogleFit.getDailyDistanceSamples(opt);
const floors = await GoogleFit.getActivitySamples(opt);
const heartrateaverage = await GoogleFit.getHeartRateSamples(opt);
const sleep = await GoogleFit.getSleepSamples(opt);

let opt = {
startDate: '2021-02-12}00:00:17.971Z', // required
endDate: new Date().toISOString(), // required
bucketUnit: 'DAY', // optional - default "DAY". Valid values: "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "SECOND" | "MINUTE" | "HOUR" | "DAY"
bucketInterval: 15, // optional - default 1.
};

**Comment by enestatli** [comment]
Try adding `basalCalculation: false` to your options

**Comment by aboveyunhai** [comment]
Google Fit api does not support `Day` more than `1` . 
So the only valid `bucketInterval` for `Day` is `1`, which means if you want to have data like 1month or 15day.
You will get a lot of one day datas then combine them by yourself.

**Comment by Pankti16** [comment]
I am getting empty with
const options = {
      startDate: "2021-01-01T00:00:17.971Z", // required
      endDate: new Date().toISOString(), // required
      bucketUnit: "DAY", // optional - default "DAY". Valid values: "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "SECOND" | "MINUTE" | "HOUR" | "DAY"
      bucketInterval: 1, // optional - default 1. 
    }
