### ISSUE TITLE
googleFit.authorize does not fire its callback

### ISSUE THREAD

**Issue by tizzyapunkt** [StasDoskalenko/react-native-google-fit#22]
It tested it using just this snippet:  
```
googleFit.authorize(() => console.log('Callback fired'))
```
It did not log that.

I already checked the index.android.js and tried something like this:
```
authorize(callback) {
        googleFit.authorize(
          msg => callback(msg, false),
          res => callback(false, res)
        );
callback('I should never get here.)
    }
```
and 'I should never get here' got logged to the console.

As I am not a Java dev, I did not dig deeper into the native code. It seems that the problem is on the Java side because `googleFit.authorize`from the index.android.js calls a native method right?

**Comment by Fehler40** [comment]
same problem here. any solutions?

**Comment by tizzyapunkt** [comment]
The problem was that the BuildConfig.APPLICATION_ID was not the same that I configured in the Google API Console.
