### ISSUE TITLE
Native module RNGoogleFit tried to override GoogleFitModule

### ISSUE THREAD

**Issue by blamont33** [StasDoskalenko/react-native-google-fit#221]
Hi, I got this error message after trying to build my application, here some screenshots of the message and my code.

I followed those steps for installation:

$ react-native link react-native-google-fit
then pass your package name to the module in MainApplication.java (google fit requires package name to save data)
new GoogleFitPackage(BuildConfig.APPLICATION_ID) Note: Do not change BuildConfig.APPLICATION_ID - it's a constant value.

Thank you

![Capture d’écran 2021-04-10 095329](https://user-images.githubusercontent.com/78203040/114406361-c4e33380-9ba7-11eb-8cec-b9e4cd7f5200.png)
![image](https://user-images.githubusercontent.com/78203040/114406456-d7f60380-9ba7-11eb-9c54-90da70ff36ee.png)

**Comment by aboveyunhai** [comment]
You don't need to link the package if your react native version is above ^0.60.
Unlink it first and try it again.

**Comment by blamont33** [comment]
Hi, thank you for your reply, I can start my app removing the link, but I keep getting "Authorization cancelled". Maybe I did something wrong (I'm learning code) so here are all the steps I followed :

1- npm install react-native-google-fit --save
2- I enabled Google Fit API on my Google API console et generated a new client ID (tested with debug and release SHA keys)
![Capture d’écran 2021-04-14 090859](https://user-images.githubusercontent.com/78203040/114668511-1eab4100-9d01-11eb-933b-d5d79cccbeab.png)
3- Configured the consent screen with external users (adding my gmail address)
4- Activated my SDK
![image](https://user-images.githubusercontent.com/78203040/114669152-ddfff780-9d01-11eb-9e2c-2f187d08ce4a.png)
5- I made a signed APK (I don't know if I had to)
6- react-native link react-native-google-fit (I didn't add the GoogleFitPackage and I tried without linking)
7- My code :
![image](https://user-images.githubusercontent.com/78203040/114669814-9d54ae00-9d02-11eb-8562-813520896920.png)
8- I also tried to add these lines in my build.gradle : 
![image](https://user-images.githubusercontent.com/78203040/114671398-59fb3f00-9d04-11eb-9b22-b9c034f4852c.png)

I must missing something but I don't know what...
(I'm working on AVD)
I generated a Client ID but I never use it anywhere, do I need to use it in my app?

**Comment by RaunakIaaps** [comment]
hi @blamont33 did you find something useful?
I am also stuck on the same error.

**Comment by tq-bao** [comment]
> You don't need to link the package if your react native version is above ^0.60.
> Unlink it first and try it again.

It work for me. Thanks !

**Comment by tq-bao** [comment]
@blamont33 
just remove 
`import com.reactnative.googlefit.GoogleFitPackage;`
`packages.add(new GoogleFitPackage(BuildConfig.APPLICATION_ID));`
in MainApplication.java
