### ISSUE TITLE
AUTH_DENIED Authorization cancelled

### ISSUE THREAD

**Issue by oguzhan18m** [StasDoskalenko/react-native-google-fit#229]
Hi everyone,

**_I need immediate help about Authorization._**

I cannot Authorize to Google Fit. I get **_AUTH_DENIED Authorization cancelled_** in my console. Here is what I did step by step. I am going to get crazy about it.

This is my function where I am trying to Authorize:

```
  const onCheckGoogleFit = () => {
    const options = {
      scopes: [
        Scopes.FITNESS_ACTIVITY_READ,
        Scopes.FITNESS_ACTIVITY_WRITE,
        Scopes.FITNESS_BODY_READ,
        Scopes.FITNESS_BODY_WRITE,
      ],
    };
    GoogleFit.authorize(options)
      .then((authResult) => {
        if (authResult.success) {
          console.log("AUTH_SUCCESS", authResult);
        } else {
          console.log("AUTH_DENIED", authResult.message);
        }
      })
      .catch(() => {
        console.log("AUTH_ERROR");
      });
  };
```

I did all the steps in this documentation:
[](https://developers.google.com/fit/android/get-api-key#find_your_apps_certificate_information)

To get SHA-1 Key, I ran this command in my RN project directory **myProject/android/app** :  
`keytool -list -v -keystore ./debug.keystore -alias androiddebugkey -storepass android -keypass android`

**OUTPUT:**

```
Alias name: androiddebugkey
Creation date: May 18, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=...
Issuer: CN=...
Serial number: ...
Valid from: Tue May 18 11:29:52 TRT 2021 until: Sat Oct 03 11:29:52 TRT 2048
Certificate fingerprints:
         SHA1: [I got the key here.]
         SHA256: ...
Signature algorithm name: ...
```
Then in `console.cloud.google.com`:

1.  I enabled Google Fitness API 
2. I created new credentials for OAuth2 (selected User Data.)
3. Skipped Scopes(optional)
4. Application Type:Android
5. Package Name founded from AndroidManifest.xml file. (com.example)
6. Pasted SHA-1 Key which is taken from RNProject/android/app/debug.keystore(like in output above)
7. Successfully got Client ID.

**My RNProject/_android/build.gradle_ I have this:**
```
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
```

**And I added this:**
```
        maven {
            url 'https://maven.google.com'
        }
```

**My RNProject/_android/app/build.gradle_**
```
dependencies{
    // for google-fit
    implementation 'com.google.android.gms:play-services-fitness:20.0.0'
    implementation 'com.google.android.gms:play-services-auth:19.0.0'
    implementation "com.google.android.gms:play-services-base:+"
}
```

**Comment by oguzhan18m** [comment]
By the way, I dont have debug.keystore in my Macbook ` Users/mycomputer/.android/ ` directory like in the docs. 

<img width="711" alt="Screen Shot 2021-05-18 at 16 12 12" src="https://user-images.githubusercontent.com/62189492/118657710-60de0b80-b7f4-11eb-9024-b8d93da3b57e.png">

**I just have it in my` RNProject/android/app` directory. I got the SHA-1 key from there.**

**Comment by denisvely** [comment]
Don't forget to add Testing user.

**Comment by oguzhan18m** [comment]
@denisvely  yessir. I added my google account as a test user and also I changed my Package name as `com.example.app` like in `android/app/buildgradle` file in` defaultConfig(applicationId)`.  Now it works.

**Comment by aboveyunhai** [comment]
Tutorial is added now.
https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md#demo-walkthrough

**Comment by chamile** [comment]
> Don't forget to add Testing user.

Is this mandatory? inst it working without a test user?

**Comment by hiroyaiizuka** [comment]
> By the way, I dont have debug.keystore in my Macbook `Users/mycomputer/.android/` directory like in the docs.
> 
> <img alt="Screen Shot 2021-05-18 at 16 12 12" width="711" src="https://user-images.githubusercontent.com/62189492/118657710-60de0b80-b7f4-11eb-9024-b8d93da3b57e.png">
> 
> **I just have it in my` RNProject/android/app` directory. I got the SHA-1 key from there.**

Thank you very much for this comment.

I failed authentication because i did'nt use debug.keystore in which had already existed in `~/.android`.
(created new debug.keystore in android/app directory...😰)

After changed original debug.keystore, everything went well!
