### ISSUE TITLE
installation guide for iOS?

### ISSUE THREAD

**Issue by nikita-zot-1408** [StasDoskalenko/react-native-google-fit#231]
Sorry if my questions sounds silly or basic but I could not find guide for iOS installation. All I see is guide for android. any suggestions please?

**Comment by aboveyunhai** [comment]
Unfortunately, this package only works for android only right now. 
I am not sure how exactly Google Fit work in IOS. So my assumption is that using another existing package like HealthKit to get data dedicated for IOS platform.
Then sync data together into GoogleFit or some custom databases.
There is a universal package works for both platform but it lacks of functionalities.
