### ISSUE TITLE
How to get active minutes(move minutes) ?

### ISSUE THREAD

**Issue by uday169** [StasDoskalenko/react-native-google-fit#232]
How can I get active minutes ..please help.

**Comment by aboveyunhai** [comment]
@uday169  what exactly is active minutes? examples?

**Comment by uday169** [comment]
active Minutes, which you earn through doing activities that get you moving like walking, running...It also called move minutes.
![gfit](https://user-images.githubusercontent.com/31014665/119225258-538c8e00-bb20-11eb-8084-dddc78489400.jpeg)

**Comment by aboveyunhai** [comment]
It seems like there is a data type relates to it. So it need to be implemented as a new feature. 
There are so many datatype from the Api, I wish I could make an universal way to get the data depends on user input datatype. But I'm currently busy on other stuffs.

**Comment by uday169** [comment]
Actually, it's important to us to get that data. I'm trying to fix this.. If you suggest me something. 
Thank you so much for your help...

**Comment by aboveyunhai** [comment]
> Actually, it's important to us to get that data. I'm trying to fix this.. If you suggest me something.
> Thank you so much for your help...

I believe you can either add a `getActitity` or `getActivityByType`  function from this file

https://github.com/StasDoskalenko/react-native-google-fit/blob/365de230b6114316688e41404e177cc82b288275/android/src/main/java/com/reactnative/googlefit/ActivityHistory.java#L36

I hadn't look at the file in details, feel free to ask any question.

**Comment by nabarun1995** [comment]
How I get active minutes .help please...

**Comment by uday169** [comment]
> > Actually, it's important to us to get that data. I'm trying to fix this.. If you suggest me something.
> > Thank you so much for your help...
> 
> I believe you can either add a `getActitity` or `getActivityByType` function from this file
> 
> https://github.com/StasDoskalenko/react-native-google-fit/blob/365de230b6114316688e41404e177cc82b288275/android/src/main/java/com/reactnative/googlefit/ActivityHistory.java#L36
> 
> https://developers.google.com/fit/datatypes/activity#move_minutes
> 
> I hadn't look at the file in details, feel free to ask any question.

Hii @aboveyunhai, Any status of this feature or when you will be working on it...

**Comment by aboveyunhai** [comment]
@uday169  Just figure out how to get move minute via rest api. So I can verify the Android Api implementation .
You need to be patient for this one since the Documentation from Google Fit was somehow confusing.

**Comment by uday169** [comment]
Thank you @aboveyunhai for the update...
I found an error on move minutes documentation in the readme file, instead of getMoveMinutes() there is getSleepSamples(). Please check it, and thank you so much again for the update.

**Comment by DanielCarrascoFalcon** [comment]
Hello! First of all thanks for your amazing work guys!!
I tried to use this function but got an 'undefined error':
```
TypeError: _reactNativeGoogleFit.default.getMoveMinutes is not a function. 
(In '_reactNativeGoogleFit.default.getMoveMinutes(opt)', '_reactNativeGoogleFit.default.getMoveMinutes' is undefined)
```
My code is:
``` 
const test = () => {
    let opt = {
      startDate: new Date(moment().startOf('day')).toISOString(),
      endDate: new Date(moment().endOf('day')).toISOString(),
      // bucketUnit: 'DAY', // optional - default "DAY". Valid values: "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "SECOND" | "MINUTE" | "HOUR" | "DAY"
      bucketUnit: 'MINUTE', // optional - default "DAY". Valid values: "NANOSECOND" | "MICROSECOND" | "MILLISECOND" | "SECOND" | "MINUTE" | "HOUR" | "DAY"
      // bucketInterval: 1, // optional - default 1.
      bucketInterval: 15, // optional - default 1.
    };
    GoogleFit.getMoveMinutes(opt).then((res) => {
      console.log('debug', res);
    });
  }; 
```
All other functions are working properly, I guess it could be an export issue or something like that but was checking the pull request and everything look fine...
Any idea of the problem source? 

Version: 0.16.2
React: 16.3.1
React Native: 0.63.4

**Comment by aboveyunhai** [comment]
@DanielCarrascoFalcon  version is just bumped. It needed be published to latest version by @StasDoskalenko
