### ISSUE TITLE
How can i submit meditaiton minutes to google fit ?

### ISSUE THREAD

**Issue by SiddhiBlackLotus** [StasDoskalenko/react-native-google-fit#236]
How i can save the meditation minutes to Google fit ?

**Comment by aboveyunhai** [comment]
duplicated #208

**Comment by SiddhiBlackLotus** [comment]
@aboveyunhai  I went through  #208, I can't seem to find save generic activity api

**Comment by aboveyunhai** [comment]
> @aboveyunhai  I went through  #208, I can't seem to find save generic activity api

Good catch, i will take a look at it.

**Comment by aboveyunhai** [comment]
> @aboveyunhai  I went through  #208, I can't seem to find save generic activity api

because it's not yet implemented
