### ISSUE TITLE
To get calories from activities like yoga, jogging, etc

### ISSUE THREAD

**Issue by jitendrahpatwa** [StasDoskalenko/react-native-google-fit#238]
Hi Team,

Have used this plugin to explore google fit in terms of finding steps and calories for the at least some of the activities like walking sleep and other metrics like health and nutrition's. 
At some point, need to find the calories burn through Yoga, Swimming, Jogging & Zumba activities how can I found that. Please suggest any feedback to achieved through this plugin, it will be helpful.

**Comment by aboveyunhai** [comment]
I believe get activity sample return all activities with calories. Then you just filter out activity based on the name by yourself.
