### ISSUE TITLE
Can any google-fit library works for ios also in React-Native?

### ISSUE THREAD

**Issue by navigarg91** [StasDoskalenko/react-native-google-fit#242]
Hello, I am working on React-Native project and this library "react-native-google-fit" suits for android but incapable to work for ios for health app. Can you please provide some solution.

**Comment by jlongev** [comment]
I am using this successfully for HealthKit.  https://github.com/agencyenterprise/react-native-health

**Comment by aboveyunhai** [comment]
Take @jlongev suggest and execute different code for different system,
