### ISSUE TITLE
How to get steps between two times

### ISSUE THREAD

**Issue by reboss** [StasDoskalenko/react-native-google-fit#25]
Hi there, is there a way to get the steps taken between two times?  I'm trying the getDailyStepSamples function as in the documentation but I keep getting three empty arrays.

Any help would be appreciated, thanks!

**Comment by StasDoskalenko** [comment]
Hey!
Seems like you're trying to get data from the online google fit?

**Comment by reboss** [comment]
No I'm trying to get data directly from the android device.  I'm working on an app that tracks users steps and every time the app is started/refreshed, I want to poll the device for the steps taken between a start time and the current time.  Can I do that with this package?

**Comment by StasDoskalenko** [comment]
It should work. Have you followed google fit authentication steps? (eg SHA fingerprint generation, oAuth installation, etc?)

**Comment by reboss** [comment]
Yea I believe I set all that up correctly.  When I first started the app it asked me what email account I wanted to use for the tracking.  Do I have to install another app for this to work?

Here's my code.  Maybe you can see the problem.   Do I have to do something extra when I authorize?

```
GoogleFit.authorize((err, result) => {
     if(err) {
         // dispatch('AUTH ERROR');
         return;
     }
     // dispatch('AUTH SUCCESS');
});

....

GoogleFit.getDailyStepCountSamples(options, (err, res) => {
                if(err) {
                    console.log(err);
                }
                // this is where I hope to retrieve the step count
                console.log(res);
            });
```

**Comment by StasDoskalenko** [comment]
What is your options object?

**Comment by reboss** [comment]
This is how I initialize options.  I've already checked that both are ISOStrings.

```
const options = {
                startDate: new Date (response.last_synch).toISOString(),
                endDate: (new Date()).toISOString()
            };
```

I took a second look at the response object and I am receiving this response outlined in the projects README:

```
[ 
   {source: "com.google.android.gms:estimated_steps", steps: []},
   {source: "com.google.android.gms:merge_step_deltas", steps: []},
   {source: "com.xiaomi.hm.health", steps: []}
]
```
But the steps are always empty arrays and don't actually retrieve steps for me.

**Comment by StasDoskalenko** [comment]
Do you have google fit app installed on your phone? Is it showing some steps for you?

**Comment by reboss** [comment]
I did not have it installed.  I installed it and now I'm getting steps.  Thank you.

The Google Fit app isn't installed by default on most android devices so I don't want to have to tell users that they have to download a second app in order for mine to work.  Is there any way to use this without having users manually install the Google Fit app?  Maybe I could package their API with my app somehow?

I'm a bit new to Android development so I'm not sure what my options are.

**Comment by dozel** [comment]
@reboss unfortunately Android doesn't have a baked-in app like Apple does. One way you can go about this is offer multiple options (Google Fit, Fitbit, Garmin, etc.) for Android users. They will eventually have to choose one though.

**Comment by reboss** [comment]
Ok thanks for your guys' help! @dozel @StasDoskalenko

**Comment by StasDoskalenko** [comment]
@dozel thanks!

@reboss you are welcome :)
