### ISSUE TITLE
Distance is empty

### ISSUE THREAD

**Issue by shraddha242** [StasDoskalenko/react-native-google-fit#252]
getDailyDistanceSamples() API gives empty array. Using the below OPT: 
  const opt = {
    startDate: moment(startDate).startOf('D'), // required ISO8601Timestamp
    endDate: new Date().toISOString(),
    configs: {
      bucketTime: 1,
      bucketUnit: 'MINUTE',
    },
  };

**Comment by szymonrybczak** [comment]
Hey, the solution for this is to get permissions for the android.permission.ACTIVITY_RECOGNITION and android.permission.ACCESS_FINE_LOCATION before calling this function. I hope this helps ;)
