### ISSUE TITLE
Manifest change required for android 11 support 

### ISSUE THREAD

**Issue by moulie415** [StasDoskalenko/react-native-google-fit#255]
I think this needs to be added your projects manifest to support android 11, might be worth adding to the readme

```xml
<queries>
    <package android:name="com.google.android.apps.fitness" />
</queries>
````

**Comment by aboveyunhai** [comment]
> I think this needs to be added your projects manifest to support android 11, might be worth adding to the readme
> 
> ```
> <queries>
>     <package android:name="com.google.android.apps.fitness" />
> </queries>
> ```

Thanks for the info, May you share what happen if you don't include the tag?
Will it prevent you from open google fit, or completely block all google fit services.

**Comment by moulie415** [comment]
> > I think this needs to be added your projects manifest to support android 11, might be worth adding to the readme
> > ```
> > <queries>
> >     <package android:name="com.google.android.apps.fitness" />
> > </queries>
> > ```
> 
> Thanks for the info, May you share what happen if you don't include the tag? Will it prevent you from open google fit, or completely block all google fit services.

It will prevent you from opening Google fit and the isAvailable will also not work

**Comment by aboveyunhai** [comment]
@moulie415 Thx! It's added into Doc!
