### ISSUE TITLE
OAuth Error in production. White Pop up with infinite loading.

### ISSUE THREAD

**Issue by hiroyaiizuka** [StasDoskalenko/react-native-google-fit#258]
Hello!

I am in trouble with production OAuth error.
Although in development,  everything is ok (with debug.keystore and SHA1.)

What i am doing is

- copy SHA1 from my-release-key.keystore which is now using for production

- follow the [installation.md](md) 

After selecting a Google Account, an empty white popup is shown, just with a loader at the top. And it stuck in this place.

<img width="575" alt="62033503-0C1E-47C2-94F7-4711DD6EB287" src="https://user-images.githubusercontent.com/39001773/136354019-37a5b5ec-4dfa-463c-8dfd-d5a14f47dfaa.png">

I thought SHA1 gained with this command `keytool -list -keystore my-release-key.keystore` was wrong but this my-release-key.keystore is surely used in production build(in Bitrise; CI/CD tools).

In my OAuth ConsentScreen, publish status is published.

Please give me some advices:pray:

## Related urls

[StepCounterKotlin stuck on empty white popup after selecting Google Account](https://github.com/android/fit-samples/issues/58)

**Comment by aboveyunhai** [comment]
your reference link states the issue, your app need to be verified by Google.
Also, I had noticed that the infinite loading is caused by using sensitive scopes like `location`. 
It used to work in the past without verification but it seems like Google no longer allows you  to do that.

**Comment by hiroyaiizuka** [comment]
@aboveyunhai 
Thank you for your reply.
As you said, it seems to me that my app is not verified by Google properly...
(and I do not use location)

@jsriganesh 
Oh, really? That's nice!
Could you tell me your solution??

**Comment by aboveyunhai** [comment]
@sotgame1234  you don't need sensitive scope for step history. Please check the link from OP, they claimed your app need to be verified by google.

**Comment by hiroyaiizuka** [comment]
I finally get a solution by this [issue](https://github.com/StasDoskalenko/react-native-google-fit/issues/260). (thank you very much guys🙏)

- go to oauth consent screen in gcp
- edit app at the top of screen next to our project
- add scope 
- move on verify process with google

hope it helps.
