### ISSUE TITLE
Authorization cancelled

### ISSUE THREAD

**Issue by imariic** [StasDoskalenko/react-native-google-fit#259]
Hello, I need some help :D 
When I try to authorize with `GoogleFit.authorize(options)` I'm getting the following response `{"message": "Authorization cancelled", "success": false}`.  Could you please help or tell me what I need to do before using react-native-google-fit?

**Comment by ilyalezhnev** [comment]
> @jsriganesh Finally I've managed to fix it. The problem was in my SHA-1. In order to create a proper SHA-1 fingerprint you need to use global keystore saved here ~/.android/debug.keystore. (follow these steps -> https://developers.google.com/fit/android/get-api-key#find_your_apps_certificate_information). Then, make sure that your Google Account's email is added to Tests Users on Google Cloud Platform. After that, everything should work as expected :D

What about production mode when users not included in testers? I am using the same keystore for both dev and prod builds. But I have the same problem only when I install my app from Play Store. It works good with Google Fit in dev mode (local development), but it doesn't when I install the app from store. Any thoughts?

**Comment by arpitfm** [comment]
@ilialezhnev i'm also stuck, so anyone have any idea if my app is in release mode its working perfect in debug mode
