### ISSUE TITLE
Help with going to production (infinite loading popups, and inability to request user permission)

### ISSUE THREAD

**Issue by csotiriou** [StasDoskalenko/react-native-google-fit#260]
First of all, let me mention that I have read the guide about the demo setup (here: https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md#demo-walkthrough), and I also read the responses at #258 

I have the same issue as with #258, but only in **Production** (while waiting for Google to verify my OAuth Consent Screen). 

Even if Google has granted access to my account as a test user so that I can create a YouTube video showing how I am using the scopes (yes, they ask for that!), I am stuck in #258, which should work (but with a warning for production users that the application is not verified yet by Google).

I know that this problem may fall out of scope, but I do have some questions regarding the use of `react-native-google-fit`

- Regarding the guide, don't we need to give Google the appropriate scopes that we use, to complete the verification? The guide seems to indicate that we can go to production without those scopes provided.
- Regarding the library, for Android 10+, should we ask for the user's permission first like here: https://developers.google.com/fit/android/authorization before asking the `react-native-google-fit` to authorize the application, from here? https://developers.google.com/fit/android/authorization
- In here: https://developers.google.com/fit/android/get-started#build_and_test_your_app in the "Resulting user authorization flow" it states that part of the flow is to request for permissions first, and THEN call for Oauth scopes - does `react-native`google-fit` cover that part for later versions of Android?

Thank you.

**Comment by stratosEft** [comment]
Just a note for everyone that may make their review process more difficult. As mentioned in installation instructions:

docs/INSTALLATION.md

> Create credentials
> 
> 1). Credential Type
> Fitness API, check userdata
> 2). OAuth Consent Screen
> Add your App name (it can be any but it will show up the name when asking authentication in your app)
> Add email
> 3). **Scopes (optional)
> Skip this part since we can ask permission in App.**
> ...

No need to add scopes! The OAuth works as expected in production

**Comment by csotiriou** [comment]
> Just a note for everyone that may make their review process more difficult. As mentioned in installation instructions:
> 
> docs/INSTALLATION.md
> 
> > Create credentials
> > 1). Credential Type
> > Fitness API, check userdata
> > 2). OAuth Consent Screen
> > Add your App name (it can be any but it will show up the name when asking authentication in your app)
> > Add email
> > 3). **Scopes (optional)
> > Skip this part since we can ask permission in App.**
> > ...
> 
> No need to add scopes! The OAuth works as expected in production

Actually, this may not work. This is what google tells you when setting up the Oauth Consent Screen without any scopes setup; 

![Screenshot 2022-08-02 at 10 07 43](https://user-images.githubusercontent.com/1228484/182313813-3f2ae0f6-ca3b-42b3-bf36-e1ec01efc5a4.png)

the application may be in production, but Google mentions that not all features will be available. And indeed, this is what happens:

![Screenshot_20220802_100750](https://user-images.githubusercontent.com/1228484/182314082-6021ef8d-96cc-48f9-aba1-f9ee6efb9abf.png)

So google evaluates your OAuth screen setup at Runtime, checks if your consent screen has the authority to request those scopes, and shows a warning if it hasn't. I don't believe there is a way around this.

I have requested the scopes: `fitness.activity.read`, and `fitness.heartrate.read`, which have both been made `restricted` lately (they were previously `sensitive`.

If you have managed to do this, and request permissions for `fitness.activity.read`, can you please share your configuration that also works in production without a warning from Google?

**Comment by stratosEft** [comment]
From your screenshots I can see that your app is not verified ( I guess in Google play store ) so complete this step too. I have provided policy links and logo icon in google console as a setup. Review process took about 2 weeks. When a user wants to use the app, it is required to give access to scopes through the OAuth consent screen. 

![Screenshot 2022-08-02 at 10 44 36 AM](https://user-images.githubusercontent.com/47448183/182320573-f6300095-4048-4581-8936-088dd9862204.png)

If I find any problem with this setup I will inform you.

**Comment by csotiriou** [comment]
Hello @stratosEft,

To test this theory, I passed the google verification with an application containing only a logo and the title.

Google, however **still** shows the screen about an unverified application. And indeed, they clarified in the email that getting approval for the brand does not meant that they give approval to the entire Oauth screen and the scopes. The scopes inside the Oauth consent screen must match the scopes requested by your application during runtime.



![Screenshot 2022-08-06 at 09 40 18](https://user-images.githubusercontent.com/1228484/183237690-298c29d8-d603-4e20-aebe-fe298283ed8b.png)

**Comment by stratosEft** [comment]
Hi @csotiriou ,

this message will always be present for testing tracks in google play store (such as internal testing). Have you tried an open testing track or production? No issues for me with the setup described above.

**Comment by nilesh-simform** [comment]
> > Just a note for everyone that may make their review process more difficult. As mentioned in installation instructions:
> > docs/INSTALLATION.md
> > > Create credentials
> > > 1). Credential Type
> > > Fitness API, check userdata
> > > 2). OAuth Consent Screen
> > > Add your App name (it can be any but it will show up the name when asking authentication in your app)
> > > Add email
> > > 3). **Scopes (optional)
> > > Skip this part since we can ask permission in App.**
> > > ...
> > 
> > 
> > No need to add scopes! The OAuth works as expected in production
> 
> Actually, this may not work. This is what google tells you when setting up the Oauth Consent Screen without any scopes setup;
> 
> ![Screenshot 2022-08-02 at 10 07 43](https://user-images.githubusercontent.com/1228484/182313813-3f2ae0f6-ca3b-42b3-bf36-e1ec01efc5a4.png)
> 
> the application may be in production, but Google mentions that not all features will be available. And indeed, this is what happens:
> 
> ![Screenshot_20220802_100750](https://user-images.githubusercontent.com/1228484/182314082-6021ef8d-96cc-48f9-aba1-f9ee6efb9abf.png)
> 
> The above screenshop is from within the Android application. Therefore google evaluates your OAuth screen setup at **runtime**, checks if your consent screen has the authority to request the scopes that you are asking for, and shows a warning if it doesn't. I don't believe there is a way around this.
> 
> In this example I have requested the scopes: `fitness.activity.read`, and `fitness.heartrate.read`, which have both been made `restricted` lately (they were previously `sensitive`).
> 
> If you have managed to do this, and request permissions for `fitness.activity.read`, can you please share your configuration that also works in production without a warning from Google?

Hey did you found any workaround for this??

**Comment by stratosEft** [comment]
Now that scope "sensitivity" has changed, you cannot avoid following google's OAuth evaluation and comply with their terms. You may even need a legal team to help you with the policies to be submitted, depending your project's complexity.
