### ISSUE TITLE
GoogleFit.observeSteps is not works i already saw issue #119

### ISSUE THREAD

**Issue by nain93** [StasDoskalenko/react-native-google-fit#262]
```
  useEffect(() => {
    const options = {
      scopes: [
        Scopes.FITNESS_ACTIVITY_READ,
        Scopes.FITNESS_ACTIVITY_WRITE,
        Scopes.FITNESS_BODY_READ,
        Scopes.FITNESS_BODY_WRITE,
      ],
    };
    const fetch = async () => {
      const auth = await GoogleFit.authorize(options);
      console.log(auth, "auth");
      if (auth.success) {
        GoogleFit.startRecording((res) => {
          console.log(res, "res1");
          GoogleFit.observeSteps((res) => {
            console.log(res "res2");
          });
        });
      }
    };
    fetch();
  }, []);
```
my console
![image](https://user-images.githubusercontent.com/73378472/139531615-ce8c5102-22d3-4da9-bd1a-40ca186e0bed.png)

#119 
i already saw this issue

and my StepCounter.java
```
 if(type.equals(DataType.TYPE_STEP_COUNT_DELTA)) {
                WritableMap map = Arguments.createMap();
                map.putDouble("steps", value.asInt());
                sendEvent(this.mReactContext, "StepChangedEvent", map);
            }
```

**Comment by pankaj-ag** [comment]
He @nain93  were you able to resolve this issue?

**Comment by nain93** [comment]
@pankaj-ag 
yes can't see console in the emulator,  have to shake phone to see it

**Comment by pankaj-ag** [comment]
So it is working on the emulator as well. 
Can you please share what callback you are getting? 

In my case GoogleFit.startRecording(response1 => {
    console.log("startRecording", response1);
    GoogleFit.observeSteps(response2=> {
      console.log( "Hello" + response2);
    });
  });

return 
 {"recording": true, "type": "STEP_RECORDING"}

and then the next callback does not start.

**Comment by pankaj-ag** [comment]
Do I need to perform ant step ?

**Comment by pankaj-ag** [comment]
I tried your code and got these logs.

![image](https://user-images.githubusercontent.com/10670690/141682348-299e223c-0950-4e1a-9121-70b10dead00c.png)

**Comment by nain93** [comment]
@pankaj-ag 
Console doesn't work in emulator
If you want to see the res2 console, you have to connect your phone and shake it

**Comment by pankaj-ag** [comment]
Ohh I got that now, It was taking some time.

**Comment by malikhamza0546** [comment]
> @nain93
> 
> So it is working on the emulator as well. Can you please share what callback you are getting?
> 
> In my case GoogleFit.startRecording(response1 => { console.log("startRecording", response1); GoogleFit.observeSteps(response2=> { console.log( "Hello" + response2); }); });
> 
> return {"recording": true, "type": "STEP_RECORDING"}
> 
> and then the next callback does not start.

I am Facing the same issue can anyone please help
