### ISSUE TITLE
Get the null is not an object googleFit.isAuthorized when authorizing

### ISSUE THREAD

**Issue by Niuecl** [StasDoskalenko/react-native-google-fit#263]
Try to follow the installation guideline to setup, but the google fit oauth2 always return following output
AUTH_DENIED null is not an object (evaluating 'googleFit.isAuthorized')

======= And the coding ======
useEffect(() => {
    // The list of available scopes inside of src/scopes.js file
    const options = {
      scopes: [
        Scopes.FITNESS_ACTIVITY_READ,
        Scopes.FITNESS_ACTIVITY_WRITE,
        Scopes.FITNESS_BODY_READ,
        Scopes.FITNESS_BODY_WRITE,
      ],
    }
    GoogleFit.authorize(options)
      .then(authResult => {
        if (authResult.success) {
          console.log("AUTH_SUCCESS");
        } else {
          console.log("AUTH_DENIED", authResult.message);
        }
      })
      .catch(() => {
        console.log("AUTH_ERROR");
      })
    });

======= the setup step is follow below ======
1. `npx react-native init AuthExampleTS --template react-native-template-typescript` to create a RN project
2. go to AuthExampleTS folder
3. `npm install react-native-google-fit --save` to install the module
4. `keytool -list -v -keystore android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android` to get the SHA1
5. goto https://developers.google.com/fit/android/get-api-key to create credentials
![Screenshot 2021-11-03 at 10 03 25](https://user-images.githubusercontent.com/93630141/140000978-296a5d0e-77aa-4a2c-aed8-ade65a01395c.png)

![Screenshot 2021-11-03 at 10 11 38](https://user-images.githubusercontent.com/93630141/140001152-f22dcef4-7a12-45a3-a037-37a4c84e4520.png)

Here is the react-native info output
<img width="817" alt="Screenshot 2021-11-03 at 10 14 53" src="https://user-images.githubusercontent.com/93630141/140001399-8e59efc2-13f7-4d56-9eaa-7c07cbf83cf6.png">

Please suggest what is missing here.

**Comment by aboveyunhai** [comment]
try to add your testing email/account into the email section as instruction says

**Comment by Niuecl** [comment]
> try to add your testing email/account into the email section as instruction says

Added a testing, developer and account emails in consent screen, but both not work.
And try to run in simulator and mobile device same result.

**Comment by aboveyunhai** [comment]
> > try to add your testing email/account into the email section as instruction says
> 
> Added a testing, developer and account emails in consent screen, but both not work.
> And try to run in simulator and mobile device same result.
> 

Usually you want to double check your SHA, or recreate debug.keystore file.
I assume the sha in your screeningshot is just a sample.

**Comment by Niuecl** [comment]
> > > try to add your testing email/account into the email section as instruction says
> > 
> > 
> > Added a testing, developer and account emails in consent screen, but both not work.
> > And try to run in simulator and mobile device same result.
> 
> Usually you want to double check your SHA, or recreate debug.keystore file. I assume the sha in your screeningshot is just a sample.

Thanks for your big help, auth success after recreate the debug.keystore
However, it does not work in `expo start`, need work on `npx react-native run-android`

Is it any method to work on expo project?

**Comment by aboveyunhai** [comment]
@Niuecl  
No. in short, if a RN application need to use a lot of native functionalities or made into large scale, you will always end up ejecting expo, but I haven't check expo for a long time. maybe there are some breaking upgrades.

**Comment by Niuecl** [comment]
@aboveyunhai 
Try using async/await syntax to call getDailyDistanceSamples, getDailyStepCountSamples, getActivitySamples and getMoveMinutes method, but both all get the empty.

Is it missing some setting?
or this module need to install another module to function?  or need to connect/signup google fit app or account first?

Using the following OPT and script:
import GoogleFit, { Scopes } from 'react-native-google-fit'
...
const options = {
  scopes: [
    Scopes.FITNESS_ACTIVITY_READ,
    Scopes.FITNESS_ACTIVITY_WRITE,
    Scopes.FITNESS_BODY_READ,
    Scopes.FITNESS_BODY_WRITE,
    Scopes.FITNESS_LOCATION_READ,
    Scopes.FITNESS_LOCATION_WRITE,
  ],
}

GoogleFit.authorize(options)
  .then(authResult => {
    console.log("debug 1")
    if (authResult.success) {
      console.log("AUTH_SUCCESS");
    } else {
      console.log({ status: JSON.stringify(authResult) });
    }
  })
  .catch(() => {
    console.log("AUTH_ERROR");
  })
...
const opt = {
  startDate: startTime ? startTime : moment().toISOString(),
  endDate: moment().toISOString(),
  bucketUnit: "DAY",
  bucketInterval: 1,
};
async function fetchDailyDistanceSamplesData() {
  const res = await GoogleFit.getDailyDistanceSamples(opt);
  console.log("fetchDailyDistanceSamplesData:" + JSON.stringify(res));
}
async function fetchDailyStepCountSamplesData() {
  const res = await GoogleFit.getDailyStepCountSamples(opt);
  console.log("fetchDailyStepCountSamplesData:" + JSON.stringify(res));
}
async function fetchActivitySamplesData() {
  const res = await GoogleFit.getActivitySamples(opt);
  console.log("fetchActivitySamplesData:" + JSON.stringify(res));
}
async function fetchMoveMinutesData() {
  const res = await GoogleFit.getMoveMinutes(opt);
  console.log("fetchMoveMinutesData:" + JSON.stringify(res));
}
fetchDailyDistanceSamplesData();
fetchDailyStepCountSamplesData();
fetchActivitySamplesData();
fetchMoveMinutesData();

And the output result
<img width="1039" alt="Screenshot 2021-11-05 at 10 20 27" src="https://user-images.githubusercontent.com/93630141/140448526-5fcc0b9c-ab0a-4506-812c-938832a32e7b.png">


Sorry for the poor english.

**Comment by aboveyunhai** [comment]
@Niuecl  This will only retrieve data existing in app. 
You need to record step by yourself.
call this at the start of app.
```javascript
if (auth) {
      // Recording API (no google fit app needed)
    GoogleFit.startRecording( callback => {
     }, ['step']);
}
```
