### ISSUE TITLE
build fails all of a sudden with Deprecated Gradle errors 

### ISSUE THREAD

**Issue by charithreddyv** [StasDoskalenko/react-native-google-fit#269]
Hai there, 
i have a React Native app configured with react-native-google-fit version `^0.16.2` which used build fine earlier, after a week here i am build fails saying `Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.` i am attaching whole log below.

```
> Task :react-native-google-fit:compileDebugJavaWithJavac FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
337 actionable tasks: 2 executed, 335 up-to-date
/Users/Work/avos/avosnewclone/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java:199: error: cannot find symbol
        GoogleSignInAccount gsa = GoogleSignIn.getAccountForScopes(mReactContext, new Scope(Scopes.FITNESS_ACTIVITY_READ));
                                                                                                  ^
  symbol:   variable FITNESS_ACTIVITY_READ
  location: class Scopes
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-google-fit:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
I am using node version 13 tried out almost all tricks found and exhausted .

Thanks in advance.

**Comment by denis0324** [comment]
same issue with `^0.17.0`

**Comment by denis0324** [comment]
the latest version (`v0.18.2`) seems to work.

**Comment by charithreddyv** [comment]
Thanks for the super fast ⚡  response.
yes updating to version `0.18.2` worked like a charm but the question still stays the same why did it break all of sudden, i think i worked like 10-15 days with `^0.16.2`.
and does `0.18.2` breaks/deprecates any functionalities for from `^0.16.2`?

**Comment by PadraicPairceir** [comment]
Seems to be related to com.google.android.gms:play-services-basement:18.0.0 getting pulled in, but I've no idea why this update has occurred.

**Comment by PadraicPairceir** [comment]
There are suggested fixes in https://github.com/StasDoskalenko/react-native-google-fit/issues/268

**Comment by aboveyunhai** [comment]
> Thanks for the super fast ⚡ response. yes updating to version `0.18.2` worked like a charm but the question still stays the same why did it break all of sudden, i think i worked like 10-15 days with `^0.16.2`. and does `0.18.2` breaks/deprecates any functionalities for from `^0.16.2`?

https://github.com/StasDoskalenko/react-native-google-fit/issues/268#issuecomment-991304855

**Comment by charithreddyv** [comment]
Thanks for the quick response and awesome support, upgrading the package worked fine and i did not see any side effects as of now.
so closing this issue.
