### ISSUE TITLE
Calorie Data Mismatch

### ISSUE THREAD

**Issue by dozel** [StasDoskalenko/react-native-google-fit#27]
**_this issue is most likely not related to this library, but probably due to the Google Fit API_**

Has anyone encountered a data mismatch of the calorie data coming from Google Fit API and the calorie data shown in the Google Fit app? Is Google Fit adding extra inactive calorie data based on demographics? How is everyone's experience with calorie data?

**Comment by StasDoskalenko** [comment]
@dozel Hey! I'm sorry but I'm not sure what to do with that.

**Comment by dozel** [comment]
Me neither haha. I was wondering if anyone encountered a similar problem.

I also tried separating active calories from inactive ones, by filtering through the bucket activity type  (filtering out any IN_VEHICLE ones), but all the calorie buckets I got back were IN_VEHICLE ones.

**Comment by StasDoskalenko** [comment]
@dozel if you find some solution please let me know :D

**Comment by StasDoskalenko** [comment]
@dozel hey man! Any updates with this? :)

**Comment by dozel** [comment]
Not yet, I have taken some time away from this part of the project. I will come back to it soon. I can close it until I come back to it if that'd be better.
