### ISSUE TITLE
Auth Denied : Authorization failed 

### ISSUE THREAD

**Issue by supriya15248** [StasDoskalenko/react-native-google-fit#272]
I have added the client secret.json file , but still while connecting the email acc I m getting the error saying authorization cancelled. Any idea what's the issue ?

I am running the app in test mode

**Comment by aboveyunhai** [comment]
These is no need for `secret.json`, not sure where you get the tutorial from.
Please check installation guide: https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md#demo-walkthrough-development-setup

**Comment by supriya15248** [comment]
I was same tutorial. So after generating the client id where I shall use it in code ?

**Comment by aboveyunhai** [comment]
> I was using the same tutorial. So after generating the client id where I shall use it in code ?

No, the way your app got verified was done by `SHA-1` in your `debug.keystore`. Please follow the tutorial step one by one.

**Comment by supriya15248** [comment]
Yes I followed all the steps as mentioned one by one still authentication is failing.. there can be any other reason for it to fail?

**Comment by aboveyunhai** [comment]
> Yes I followed all the steps as mentioned one by one still authentication is failing.. there can be any other reason for it to fail?

Based on the past experiences, most people failed to get the correct sha-1 from keystore. You can delete the debug.keystore and create a new one with the new sha-1 to see if it works. Just don't forget to add/change the new sha-1 in the Google auth dashboard.

**Comment by supriya15248** [comment]
Okay I'll try this and see if it works.. Thanks a lot

**Comment by supriya15248** [comment]
> > Yes I followed all the steps as mentioned one by one still authentication is failing.. there can be any other reason for it to fail?
> 
> Based on the past experiences, most people failed to get the correct sha-1 from keystore. You can delete the debug.keystore and create a new one with the new sha-1 to see if it works. Just don't forget to add/change the new sha-1 in the Google auth dashboard.

Okay I'll try this and see. Thanks a lot
