### ISSUE TITLE
Resting Heart Rate?

### ISSUE THREAD

**Issue by shmkane** [StasDoskalenko/react-native-google-fit#274]
Is there currently a way to get resting heart rate from GFit that I'm missing? I don't see a function for it, but I also noticed Google doesn't have a separate scope for it. I looked at the data being returned and there's no meta data indicating that the data is HR vs RHR. 

Any ideas?

**Comment by shmkane** [comment]
Didn't see this as an option with this package https://stackoverflow.com/questions/58714865/is-there-a-way-to-read-daily-resting-heart-rate-from-the-google-fit-api

**Comment by AaronDsilva97** [comment]
https://github.com/StasDoskalenko/react-native-google-fit/pull/325
This might help you

**Comment by aboveyunhai** [comment]
Solved by #325

**Comment by VictorGarcia** [comment]
@aboveyunhai Can we please get a new version that incorporates Resting Heart Rate? The current 0.19.0 doesn't seem to have it yet and I'd prefer not to point my dependencies to master.

Thanks!

**Comment by aboveyunhai** [comment]
@VictorGarcia  npm@0.19.1 is out

**Comment by VictorGarcia** [comment]
@aboveyunhai Thanks!
