### ISSUE TITLE
observeHistory only working once & observeSteps is not working

### ISSUE THREAD

**Issue by imspikey** [StasDoskalenko/react-native-google-fit#28]
Hello
observeHistory is only working once and when the device move it dose not update.

observeSteps is not working at all ??!

although getDailyStepCountSamples is working fine?

any help please?

**Comment by StasDoskalenko** [comment]
@imspikey could you please share some code and more details?

**Comment by imspikey** [comment]
I am using react native 4.9 and samsung s7 api 24
      here is the code.
   
       import React, { Component } from 'react'
       import Styles from './styles'
       import GoogleFit from 'react-native-google-fit'
       import Reactotron from 'reactotron-react-native'
       import  jsonFormat from 'json-format'

      import {
	View,
	Text,
     } from 'react-native'
     
     class Walking extends Component {

   
    timer:number = 0;
    
	constructor(props)
	{
		super(props);
   
            GoogleFit.authorize((err, result) => {
            if(err) {

		alert('olla')
            }
            else {
             
                GoogleFit.observeHistory((steps)=>{
                    Reactotron.log(steps)
                });

                const options = {
                    startDate: "2017-01-01T00:00:17.971Z",  // required ISO8601Timestamp
                    endDate: (new Date()).toISOString()     // required ISO8601Timestamp
                };

                GoogleFit.getDailyStepCountSamples(options, (err, res) => {
                    if (err) {
                        throw err;
                    }
                    Reactotron.log(steps)

                })
			}

        });

        this.state ={
        	steps:0
		}
	
	}

	render() {

		return (
			<View style={Styles.container}>
				<Text>{this.state.steps+""}</Text>
			</View>
		)
	}
}

export default Walking

**Comment by StasDoskalenko** [comment]
@imspikey hey! COuld you please try new recording API?

**Comment by imspikey** [comment]
Thank you the problem is resolved 👍
