### ISSUE TITLE
"We noticed that the sensitive scopes you submitted for review aren't the same as the scopes that your app requests:"

### ISSUE THREAD

**Issue by Waltari10** [StasDoskalenko/react-native-google-fit#292]
I submitted my app for review that is using Android Google Fit API. I got the following response from Google.

> Hi,
> 
> Thanks for applying for OAuth App verification your response reaching
> out.
> 
> We noticed that the sensitive scopes you submitted for review aren't
> the same as the scopes that your app requests:
> 
> **Scopes Submitted for Review​**
> 
> https://www.googleapis.com/auth/fitness.activity.read 
> 
> https://www.googleapis.com/auth/fitness.activity.write 
> 
> **Requested by your App**
> 
> https://www.googleapis.com/auth/fitness.activity.read  
> 
> with the verification process, please update either of the following:
> 
> The request for scopes in your app's codebase so that the scopes
> requested by your app match the scopes {in your Console/in review} or
> The scopes you submitted for review using the scope picker in your
> Console. If you're adding scopes to your Google Cloud project, make
> sure you provide a detailed Scope Justification for each additional
> scope you submit for review. You can find more information in the
> OAuth Application Verification FAQ. If you have other questions,
> please reply to this email to continue

Thing is in GCP I clearly only request read access:

[![sensitive scopes img in GCP][1]][1]

  [1]: https://i.stack.imgur.com/rabPf.png

And then using React-Native-Google-Fit library in code I request:

     const options = {
         scopes: [Scopes.FITNESS_ACTIVITY_READ, Scopes.FITNESS_LOCATION_READ],
     };
    
     const authResponse = await GoogleFit.authorize(options);

Where does Google get the idea that I'm requesting write access? Is it something to do with the library? How do I fix this? I only need to read the exercises from Google Fit.

**Comment by Waltari10** [comment]
I sent them an email requesting explanation. I hope something else than a bot answers, but I kinda doubt it.

**Comment by aboveyunhai** [comment]
@Waltari10  if I understand the reply message correctly. It states that your app only requests read permission only, which correctly matches your code. It looks like a misconfiguration on the google management panel, or something wrong from Google side.

**Comment by Waltari10** [comment]
As you can see from the screenshot though I only have fitness.activity.read there :/ I really don't know where else in the configuration in GCP I would be asking for write access. I sent them an email asking about it and they just sent the same canned email...

**Comment by aboveyunhai** [comment]
@Waltari10  if you are still getting same garbage message at the end, maybe just add the read scope into your app no matter what, so they wouldn't bother you about the mismatch usage, So you can still process whatever you want.

**Comment by Waltari10** [comment]
I guess it was complaining about the missing `fitness.location.read` scope. I added that and it stopped complaining about `fitness.activity.write`. Seems Google just misidentified the missing scope.
