### ISSUE TITLE
Observe History returns empty Array always

### ISSUE THREAD

**Issue by MJ0826** [StasDoskalenko/react-native-google-fit#3]
I am trying to get the history for steps count, but every time  it returns an empty array, as i am using it since the morning, it should return the steps i walked till now. 
Below is my code: 
`  const dayStart = '2017-01-01T00:00:17.971Z';
    const dayEnd = (new Date()).toISOString();

    GoogleFit.getSteps(dayStart, dayEnd);
    GoogleFit.observeHistory((results) => {
      console.log(results);
    });`

results is an empty array

**Comment by StasDoskalenko** [comment]
@MJ0826 hello! Do you have google fit installed on the device to ensure that array is not empty?
Which react native version do you use?
Anyway module now in beta, so I'll check out what is going on.

Thanks for acitivity!

**Comment by MJ0826** [comment]
What i figured out is you are not saving the data which we get in the observe Steps, so no data is being saved through the api, that is why it is returning empty data when i try to retrieve it.

**Comment by StasDoskalenko** [comment]
@MJ0826 I'm stuck with this. The strange is weights method works fine.

**Comment by StasDoskalenko** [comment]
@MJ0826 I guess you experienced some problems with access level because almost all users told they have no problems like this.
For example:
https://github.com/StasDoskalenko/react-native-google-fit/issues/4

**Comment by dozel** [comment]
I encountered the same issue on the emulator, but once I debugged using an android phone, I got results. Why would that happen on the emulator @StasDoskalenko ?

**Comment by MJ0826** [comment]
@dozel google play services doesn't work on emulator, you need to test it on the device for that.

**Comment by MJ0826** [comment]
@StasDoskalenko I think i can get the steps only when i use google fit app and save some data through that, If i use this module and try retrieving the steps it will return an empty array, because you are not saving the data you get when one walks, so when you try to get the history it will return an empty array.

**Comment by StasDoskalenko** [comment]
@dozel @MJ0826 hi guys! Thanks for testing. I guess google has changed their policy. Because less than few weeks ago the app worked fine on the emulator. Maybe we can find out some information how to turn google services on emulator again? Thanks!

**Comment by adamgrossman** [comment]
I have genymotion setup and was able to install Google Play Services on my emulator. I've also added Google Fit on the emulator, however even after adding step data into Google Fit, I'm always receiving 0. I was able to get results with a physical device. It'd be a shame if it didn't work with an emulator. Hope someone here has better luck!

**Comment by adamgrossman** [comment]
@StasDoskalenko Could you (or anyone else) help me understand how these API requests work? When making a request, in my case for step data, does it read just the steps taken using the device you're on? Or will it read data from your Google account? 

For example, I went to fit.google.com and I entered step data for 1 hour ago. I can see that data is accurately entered on the website. When I make the request through my JS code with the same time frame however, I receive 0 steps. 

Is this a problem with making the request? Or because I am using an emulator? If it's the same emulator issue as above, I'm confused because the data should be associated with my Google account and not only my device.

**Comment by StasDoskalenko** [comment]
@all check again. New version is out.

**Comment by buddhishan** [comment]
Hi @StasDoskalenko , Any update on saving the steps to Google Fit?
