### ISSUE TITLE
getDailyCalorieSamples and BMR

### ISSUE THREAD

**Issue by adcuz** [StasDoskalenko/react-native-google-fit#32]
I've been looking at this great library, so far so good. I have a question regarding `getDailyCalorieSamples`. It appears in the source code that BMR is being deducted from the calorie values, but actually it isn't. Some very brief research suggests that the `AGGREGATE_BASAL_METABOLIC_RATE_SUMMARY` data does not work, and by logging some additional data to console verifies this, it just returns empty datasets. Is it worth removing this from the source? It could cause future confusion if it gets fixed unexpectedly.

**Comment by adcuz** [comment]
Update: it appears it may be unique to my account that`AGGREGATE_BASAL_METABOLIC_RATE_SUMMARY` was not working, I have now got it returning a value for the current day somehow. Unfortunately this seems to have caused the total calorie burn to become negative, as the current day is an instantaneous value (`723.4156`) and the BMR value is for the entire day (`1588.25`), so the calories for today is reported by the getDailyCalorieSamples as `-864.8344`. 

This seems a good reason to not subtract BMR from the values, or at least have an option to disable that.

**Comment by StasDoskalenko** [comment]
Hey, @adcuz thank you for this report. Is this data was collected on the local device or web google fit?

**Comment by adcuz** [comment]
The data is all collected from the device. I don't think my initial post is a problem with this library, although I had all my height/weight etc set Google Fit was not returning anything for BMR, but after logging a new weight it has started to report BMR correctly. It's just by chance that I noticed afterwards that the current day ends up as a negative number. I'm not sure how that could be solved beyond some way of knowing how many minutes into the day we are and calculating the BMR so far for today.

**Comment by StasDoskalenko** [comment]
Hey @adcuz any updates?

**Comment by adcuz** [comment]
I moved onto using the data from activities instead of the `getDailyCalorieSamples` method. I don't have enough knowledge of java to understand what is going on.

**Comment by StasDoskalenko** [comment]
@adcuz I believe it's happening because of Google's documentary inconsistency and unpredictable results :( Not only you meet these troubles.

**Comment by adcuz** [comment]
@StasDoskalenko it's a shame, it's a good product but with problems, even their own app suffers from weird bugs.
