### ISSUE TITLE
AUTH_DENIED Authorization cancelled

### ISSUE THREAD

**Issue by faisalur-rehman** [StasDoskalenko/react-native-google-fit#322]
When I click one the account on Consent Screen, I face this error `AUTH DENIED: Authorization Cancelled`. 
Below are the steps I performed for getting the client id:
1. Selected Application Type: Android
2. Added package name from AndroidManifest.xml
3. For SHA-1, I went into android/app folder. There was a debug.keystore file already present. I got the SHA-1 key by running this command `keytool -list -v -keystore your_keystore_name -alias your_alias_name`
I downloaded the client_secret.json file that got created once the Credentials were setup and placed it in app/android/app/src/main/resources as specified here [https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/FAQ.md](https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/FAQ.md) . There was no `resources` folder in `main` so I created it myself. 

I setup the consent screen and added test users as well.
In `app/build.gradle`, I added these dependencies as well
`

    implementation 'com.google.android.gms:play-services-auth:19.0.0'
    implementation "com.google.android.gms:play-services-base:+"`
    implementation 'com.google.android.gms:play-services-fitness:20.0.0'

Am I missing something or doing something wrong? Any help would be appreciated

**Comment by faisalur-rehman** [comment]
I got this issue fixed by deleting the previous debug.keystore file and creating a new one. Also updated my credential as per SHA-1 of new debug.keystore

**Comment by aboveyunhai** [comment]
https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md#demo-walkthrough-development-setup
It's in the 3rd step.
