### ISSUE TITLE
isAvailable() doesn't work on Android 11+ without change to AndroidManifest.xml

### ISSUE THREAD

**Issue by rblakesley** [StasDoskalenko/react-native-google-fit#324]
Very nice module – thanks!  It's perhaps worth mentioning in the documentation that, from Android 11 onwards, you need to add this to AndroidManifest.xml, otherwise the isAvailable() function will always return false:

```
    <queries>
      <package android:name="com.google.android.apps.fitness" />
    </queries>
```

See https://developer.android.com/training/package-visibility/declaring for more information.

**Comment by aboveyunhai** [comment]
@rblakesley we did. https://github.com/StasDoskalenko/react-native-google-fit#android-11
