### ISSUE TITLE
What is APPLICATION_ID ?

### ISSUE THREAD

**Issue by vah7id** [StasDoskalenko/react-native-google-fit#33]
Hey Man,

Good job for this well done library. I want to use it in my android project but at first I want to know what is the APPLICATION_ID that you mentioned in your documentation ?
Is that CLIENT_ID that we can get it with your link which mentioned in usage doc section ?

* Dude please reform your documentation and usage instructions. Because I think it is not complete yet and this is only repository which exist in the community yet. Please take care of it ;)

**Comment by StasDoskalenko** [comment]
Application ID is your "com.example.myapp". But you don't need to change it. It's a global constant value.

**Comment by StasDoskalenko** [comment]
@vah7id thanks for the feedback!
You're welcome for PR's ;)
