### ISSUE TITLE
onAuthorizeFailure always triggered when authorizing google fit

### ISSUE THREAD

**Issue by PierreCavalet** [StasDoskalenko/react-native-google-fit#34]
Hi, 

It seems like the event `onAuthorizeFailure` is always triggered.

I'm using the README code:

```js
GoogleFit.onAuthorize(() => {
  console.log('success');
});

GoogleFit.onAuthorizeFailure(() => {
  console.log('failure');
});

GoogleFit.authorize();
```

When I am authorizing Google fit, either on simulator or real device, the failure event is always triggered, right after calling authorize (while there is still the account selection modal).

Note that onAuthorize is triggered when I select my account, so the success case is handled. I was wondering if I am doing something wrong, or if the error handling has an issue.

**Comment by StasDoskalenko** [comment]
@PierreCavalet it's common issue when you miss something from here 

1) In order for the library to work correctly, you'll need following SDK setups:

Android Support Repository
Android Support Library
Google Play services
Google Repository
Google Play APK Expansion Library

2) In order for your app to communicate properly with the Google Fitness API, you need to provide the SHA1 sum of the certificate used for signing your application to Google. This will enable the GoogleFit plugin to communicate with the Fit application in each smartphone where the application is installed. https://developers.google.com/fit/android/get-api-key

**Comment by PierreCavalet** [comment]
@StasDoskalenko I already provided the SHA1 sum to generate the clientID of the certificate which I directly put in the `MainApplication.java` like so:

```java
...
new GoogleFitPackage("clientID....apps.googleusercontent.com"),
...
```

I've used the following command to generate it (mac OS):
```
keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
```

I then created new credentials for an Oauth client ID and submitted the SHA1 fingerprint and package name which gave me the clientID that I used in the `MainApplication.java`. Is there something wrong with my procedure ? Note that I can retrieve my google fit data on my phone (in debug) which seems to indicate that it's somehow working, but maybe I missed something else.

Any idea ?

**Comment by StasDoskalenko** [comment]
@PierreCavalet yes. You shouldn't pass clientID to GoogleFitPackage constructor.
Just use it like in installation guide. ```new GoogleFitPackage(BuildConfig.APPLICATION_ID)```

**Comment by StasDoskalenko** [comment]
In any case you can see the reason within:
`GoogleFit.onAuthorizeFailure((error) => {
  console.log('failure', error);
});
`

**Comment by PierreCavalet** [comment]
I get the error: 
`"ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{f40b858: android.os.BinderProxy@6ca86bc}, message=null}"`

Which seems to be an error when the user did not authorized the application, but what is weird is that I'm in the authorization process.

**Comment by StasDoskalenko** [comment]
Actually, it means that you missed something from Google Docs. Please try to follow these instructions https://developers.google.com/fit/android/get-api-key really carefully.

**Comment by PierreCavalet** [comment]
I'm no android expert, I don't really understand what I did wrong.

(Note that I didn't do the release key part since I'm in debug, is there something wrong with that ?)

I got my SHA-1 fingerprint from the ~/.android/debug.keystore and generated my clientID with the fingerprint and package name.

What am I supposed to do with my clientID ?

**Comment by PierreCavalet** [comment]
Hi again,

I just wanted to provide more information in case this can help. Maybe I am wrong, but it seems that the api-key process works, because with an other keystore, it was not working (which is normal).

I went through the process again for the new keystore and I can now retrieve my data with this one. So it seems to work. The authorization also works normally on the "success scenario". The only thing which is not working seems to be the `onAuthorizeFailure` which is still trigger even when it works.

**Comment by ernestasromeika** [comment]
I have the exact same issue, GoogleFit.onAuthorize() is triggered at the exact same time as GoogleFit.authorize() is called, before user even selects his google profile. Results in an error message: `ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{2438a5: android.os.BinderProxy@d4c947a}, message=null}`.

**Comment by StasDoskalenko** [comment]
@ernestasromeika ```statusCode=SIGN_IN_REQUIRED``` means that you've missed something from https://developers.google.com/fit/android/get-api-key

**Comment by PierreCavalet** [comment]
@ernestasromeika did you solve your problem ?

**Comment by platonish** [comment]
I have no idea of how, but for some reason the following seems to work for me:
Inside `node_modules > react-native-google-fit > android > build.gradle`, scroll all the way to the bottom and replace the version numbers of `play-services-auth` and `play-services-fitness` to `+`, similar to how it is for react-native. Here's what it'll look like in the end:
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-auth:+'
    compile 'com.google.android.gms:play-services-fitness:+'
}
```
