### ISSUE TITLE
How to allow access to our react native mobile app without mandatory Google OAuth sign in blocking users progressing (is it possible to easily skip)?

### ISSUE THREAD

**Issue by marzhill** [StasDoskalenko/react-native-google-fit#345]
Using this library, means that the current implementation mandates new users to sign into our app using their Google login, or they get blocked and cannot access our app. They MUST sign into the google oauth screen when they are new users. note: our users log in with their email - we don't use the Google OAuth as the way for our users to sign in at login - our users only use the google oauth for one part of our app to activate their health data to sync after they've already logged in with email. This opt in to Google OAuth should be OPTIONAL.

This mandatory login (with no option for users to skip) is a terrible user experience for our users - they should be able to opt in or out of sharing their health data with us, when they are new users  - and if hey do skip/opt out then they should still be able to access our app and not be blocked from progressing through the app (which is the current user experience = they get blocked).

Is there a way our users can "skip" this Google OAuth screen in the current library as it is? or would there need to be code update to add in a 'skip' button on the Google OAuth screen?
Not sure if we're missing something here... Would appreciate all help possible!! 

Thank you!!  🤸 🤾‍♀️🥇

Tagging  @StasDoskalenko @aboveyunhai  @matiaskorhonen

**Comment by matiaskorhonen** [comment]
I'm no longer working on a project that uses Google Fit but you need to only call the `authorize` function once the user has indicated that they want to share their data. What form user onboarding takes is up to you.

Also, tagging anyone who has ever contributed to the repo is pretty bad form and very rude.
