### ISSUE TITLE
UnsubscribeListeners serious issue

### ISSUE THREAD

**Issue by eyeCU113** [StasDoskalenko/react-native-google-fit#36]
The method for unsubscribing to the listeners has two issues:

1. Name is misspelled (usubscribe -> unsubscribe)
2. SERIOUS: the method removes ALL of the DeviceEventEmitter listeners - this leads to tons of issues with the development process - hot reloading stops working, navigation events are lost, etc. A lot of React Native code depends on these listeners so they should not be removed. 

Our proposal is to keep all listener instances and use the .remove() method on all of them when the method is called. 
We will try to provide a PR in the next days to fix this.

**Comment by StasDoskalenko** [comment]
@eyeCU113 thanks for this reporting! I'll try to fix it ASAP

**Comment by StasDoskalenko** [comment]
@eyeCU113 hey! This should work for you: https://github.com/StasDoskalenko/react-native-google-fit/commit/f1084874396f8bf7a081058422ad2a3b050622b8

If it's fine, I'll publish to the npm

**Comment by StasDoskalenko** [comment]
Published to the NPM
