### ISSUE TITLE
Question regarding the Xiao Mi Support

### ISSUE THREAD

**Issue by kh1990** [StasDoskalenko/react-native-google-fit#37]
With version 0.3 comes Xiao mi support, please help me understand how that is.

If I am understanding the code correctly, it seems like MiFit is added as a data source. [link to code]((https://github.com/StasDoskalenko/react-native-google-fit/blob/master/android/src/main/java/com/reactnative/googlefit/StepHistory.java) )
Thus the user still needs to authorize google fit before pulling activity data? 

THanks!

**Comment by StasDoskalenko** [comment]
Hi, @kh1990 ! Thanks for this question. Actually, as you can see from the name of this package Google Fit is **required** and used as data aggregator from all device within the account.
