### ISSUE TITLE
Filter manual entered data

### ISSUE THREAD

**Issue by AadGlasbergen** [StasDoskalenko/react-native-google-fit#39]
We are developing an App which give you "Coins" when you reached an achievement. You can manually enter steps in Google Fit. Is it possible to filter out this manual entered data.

**Comment by StasDoskalenko** [comment]
@AadGlasbergen I believe you can filter it by source type

**Comment by neogermi** [comment]
@StasDoskalenko and @AadGlasbergen yes, we have done that directly in the Java code. You can filter for 'user_input' inside `StepHistory.java`:

```
+            // check if was manually input
+            DataSource ds = dp.getOriginalDataSource();
+            String streamId = ds.getStreamIdentifier();
+
+            if (streamId.toLowerCase().indexOf("user_input") != -1) {
+              // exclude this from the set
+              Log.i(TAG, "\t\tOriginalSource  : " + streamId + " -> excluded as it was manually entered");
+              continue;
+            }
```

**Comment by EJohnF** [comment]
Now there is 'tracked' flag to check whether it was logged manually or recorded from sensors.

**Comment by StasDoskalenko** [comment]
Added TODO: in https://github.com/StasDoskalenko/react-native-google-fit/projects/1

**Comment by winardis** [comment]
Hi are there any updates to the filter on manually added entries for the package @StasDoskalenko ?

**Comment by ClementLANGENDORF** [comment]
Hi @StasDoskalenko when do you think this feature will arrive ?
@neogermi In the meantime could you please show me how and where you filter, that would be a great help.  🙏  🙏  🙏

**Comment by neogermi** [comment]
Hi @ClementLANGENDORF ,

sure. All I did was that I basically added the above mentioned code piece in `StepHistory.java` insice `processDtaSet`. This then filters for the stream where the data came from. We then filter out everything that was manually added by the user, hence `"user_input"`.

Not the best solution but my Android-code skills are limited :-) 

BTW: We then extracted this part with [patch-package](https://www.npmjs.com/package/patch-package) to apply only our changes on top of the official release. That was quite beneficial.

Hope that helps you.

**Comment by ClementLANGENDORF** [comment]
Thank you @neogermi I will try but I just saw that there was a metode `GoogleFit.getUserInputSteps` to allow to get the steps, it seems to work well I'll go on it.

my skills in android / java development are not the best for me either

**Comment by PhalugunaRao** [comment]
> @StasDoskalenko and @AadGlasbergen yes, we have done that directly in the Java code. You can filter for 'user_input' inside `StepHistory.java`:
> 
> ```
> +            // check if was manually input
> +            DataSource ds = dp.getOriginalDataSource();
> +            String streamId = ds.getStreamIdentifier();
> +
> +            if (streamId.toLowerCase().indexOf("user_input") != -1) {
> +              // exclude this from the set
> +              Log.i(TAG, "\t\tOriginalSource  : " + streamId + " -> excluded as it was manually entered");
> +              continue;
> +            }
> ```

FOR samsung device getting "Samsung Step Counter" it's not user_input
