### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by shaheem-khanzada** [StasDoskalenko/react-native-google-fit#40]
![image](https://user-images.githubusercontent.com/37620819/37861841-0279f6b0-2f64-11e8-9a2d-421f88207605.png)

hey i think this is google service error because it is updated yesterday was fine but today this is showing error  but i can not figure it out its seem like i need your help the error is defined in google-fit

And other thing why calories are comming in (-) negative example: -750

**Comment by StasDoskalenko** [comment]
@shaheem-khanzada Maybe It related to new release of Google Play services 12.0.0(released at March 20, 2018)

a pretty common issue for few last days

last stable play service is 11.6.0

**Comment by StasDoskalenko** [comment]
try this please:
```...
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
                force 'com.google.android.gms:play-services-auth:11.6.0'
                force 'com.google.android.gms:play-services-fitness:11.6.0'
                force 'com.google.android.gms.license:11.6.0'
            }
        }
    }
}```

**Comment by sujayjaju** [comment]
Adding the following to `android\build.gradle` fixed it for me:
```
allprojects {
    repositories {
        ....
        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '11.6.0'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '11.6.0'
                }
            }
        }
    }
}
```

**Comment by ernestasromeika** [comment]
@sujayjaju I'm still getting the same as my prev. comment. Which version of react-native-google-fit and which version of play-services-fitness + play-services-auth are you using? Could I take look at your repo if it's public?

**Comment by StasDoskalenko** [comment]
@ernestasromeika maybe you have some more conflicting modules
try to add in your build.gradle
```configurations.all {
   resolutionStrategy {
       force "com.google.android.gms:play-services-ads:11.8.0"
       force "com.google.android.gms:play-services-base:11.8.0"
       force "com.google.android.gms:play-services-gcm:11.8.0"
       force "com.google.android.gms:play-services-analytics:11.8.0"
       force "com.google.android.gms:play-services-location:11.8.0"
       force "com.google.android.gms:play-services-basement:11.8.0"
       force "com.google.android.gms:play-services-tagmanager:11.8.0"
       force 'com.google.firebase:firebase-core:11.8.0'
       force 'com.google.firebase:firebase-crash:11.8.0'
       force 'com.google.firebase:firebase-auth:11.8.0'
       force 'com.google.firebase:firebase-common:11.8.0'
       force 'com.google.firebase:firebase-config:11.8.0'
       force 'com.google.firebase:firebase-messaging:11.8.0'
   }
}
```

**Comment by sujayjaju** [comment]
@ernestasromeika You need to run `gradlew clean` once after making the update.

**Comment by AadGlasbergen** [comment]
All of the above didn't work for me. See the errors. 

react-native-google-fit:incrementalReleaseJavaCompilationSafeguard
:react-native-google-fit:compileReleaseJavaWithJavac
:react-native-google-fit:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/ProjectenReactnative/healthcoin/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java:40: error: GoogleFitManager is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class GoogleFitManager implements
       ^
/ProjectenReactnative/healthcoin/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java:199: error: method does not override or implement a method from a supertype
    @Override
    ^
/ProjectenReactnative/healthcoin/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java:214: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
:react-native-google-fit:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

BUILD FAILED

**Comment by StasDoskalenko** [comment]
@AadGlasbergen your error is not related to this issue.
What is yours react native version?
