### ISSUE TITLE
could not invoke RNGoogleFit.startFitnessRecording

### ISSUE THREAD

**Issue by shaheem-khanzada** [StasDoskalenko/react-native-google-fit#42]
![image](https://user-images.githubusercontent.com/37620819/37894807-dccd68d4-30f8-11e8-9f81-27d19c33cf89.png)

when i install module again my android studio make build and apk successfull but gives that error when app start before the google service issue it was fine

**Comment by StasDoskalenko** [comment]
Hey, could you please specify RN, and GoogleFIT module versions

**Comment by shaheem-khanzada** [comment]
![image](https://user-images.githubusercontent.com/37620819/37973002-f4449c9e-31f2-11e8-8573-2f5190546df8.png)
 "react-native": "^0.49.3"

**Comment by shaheem-khanzada** [comment]
hey what do i do tell me

**Comment by StasDoskalenko** [comment]
@shaheem-khanzada do other methods work for you? Like this:
```javascript
const options = {
  startDate: "2017-01-01T00:00:17.971Z", // required ISO8601Timestamp
  endDate: new Date().toISOString() // required ISO8601Timestamp
};

GoogleFit.getDailyStepCountSamples(options, (err, res) => {
  if (err) {
    throw err;
  }

  console.log("Daily steps >>>", res);
});```

**Comment by shaheem-khanzada** [comment]
yes it worked for me hey can i get current date or day data without map() and also which RN version is suitable for this error to be gone ?

**Comment by shaheem-khanzada** [comment]
hello ??????

**Comment by StasDoskalenko** [comment]
@shaheem-khanzada use latest react native

**Comment by shaheem-khanzada** [comment]
update to 0.52 still getting error

**Comment by shaheem-khanzada** [comment]
hey i am still getting an error

**Comment by shaheem-khanzada** [comment]
please solve this issue

**Comment by StasDoskalenko** [comment]
@shaheem-khanzada try
```javascript
componentDidMount() {
      GoogleFit.onAuthorize((response) => {
        console.log('response >>>', response)
        GoogleFit.startRecording((callback) => {
          console.log('callback >>>', callback) // u should call startRecording only after authorize
        })
      })

      GoogleFit.onAuthorizeFailure((res) => {
        console.log('response fail >>> ', res)
      })

      GoogleFit.authorize()
    }
```

**Comment by StasDoskalenko** [comment]
Also don't forget to add 
```        maven { url "https://maven.google.com" }
```
to yours projects build.gradle

**Comment by shaheem-khanzada** [comment]
@StasDoskalenko thanks man for help but the issue was solved when i remove node modules folder and try to reinstall

**Comment by StasDoskalenko** [comment]
@shaheem-khanzada 👍
