### ISSUE TITLE
Way to check if already authorized?

### ISSUE THREAD

**Issue by sujayjaju** [StasDoskalenko/react-native-google-fit#44]
Is there a way to check if the App is already authorized without calling `GoogleFit.authorize()`?
I want to let the user choose to enable access by clicking a button and not display that button if already authorized.

**Comment by StasDoskalenko** [comment]
@sujayjaju hi!
There are two methods to try:
```javascript
   GoogleFit.isAvailable(callback) // is Google Fit available for this device

    GoogleFit.isEnabled(callback) //is permission granted
```

**Comment by sujayjaju** [comment]
Both don't work if the app is reopened. Always returns false on start.

**Comment by StasDoskalenko** [comment]
@sujayjaju hm. The strange is. IF user already authorized, it shouldn't show the login screen.

**Comment by sujayjaju** [comment]
It does not. What I mean is that I need the app to know whether it is already authorized or not. Call "authorize" only if already authorized. Not sure if its even possible.

**Comment by shaheem-khanzada** [comment]
hi you just have to call authorize on componentWillMount() so when ever your app start it automatically check if you are login then authorize function check and move forward to application screen if user is not login then authorize function show login screen like that :]
Example:



 componentWillMount() {
        this.onAutherize(); // like that
            GoogleFit.observeSteps((step)=>{
                console.log('step', step);
                alert('i am alert step counter')
            })
    }

 onAutherize(){          /// call it on componentWill Mount 
        GoogleFit.onAuthorize(() => {
        });
        GoogleFit.onAuthorizeFailure(() => {
            alert('something went wrong')
        });
        GoogleFit.authorize()
        // Call when authorized
        GoogleFit.startRecording((callback) => {

        });
    }

**Comment by shaheem-khanzada** [comment]
just call it in a componentWillMount and what RN version you got
componentWillMount() {
        this.onAutherize();

            GoogleFit.observeSteps((step)=>{
                console.log('step', step);
                alert('i am alert step counter')
            })
    }
 
onAutherize(){
        GoogleFit.onAuthorize(() => {

        });
        GoogleFit.onAuthorizeFailure(() => {
            alert('something went wrong')
        });
        GoogleFit.authorize()
        // Call when authorized
        GoogleFit.startRecording((callback) => {

        });
    }

**Comment by StasDoskalenko** [comment]
@sujayjaju actually it checks on the native side whether user authorized or not. We can't call these methods without basic `.authorize()` method

**Comment by sujayjaju** [comment]
Got it. Thanks for looking into it.
