### ISSUE TITLE
GoogleFitManager.java override issue

### ISSUE THREAD

**Issue by AadGlasbergen** [StasDoskalenko/react-native-google-fit#45]
Hello,

I have tried to implement your library in react-native. I am using the following packages:

- react: 16.3.0
- react-native: 0.54.4
- react-native-google-fit: 0.5.2

When trying to compile the project the following issues occurred in GoogleFitManager.java
```

GoogleFitManager.java:40: error: GoogleFitManager is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener

GoogleFitManager.java:199: error: method does not override or implement a method from a supertype

GoogleFitManager.java:214: error: method does not override or implement a method from a supertype
```
It seems like the GoogleFItManager class is trying to override an older version of ActivityEventListener.

I have looked  into the library of react-native and was unable to identify why this error occurs, but it does seem to originate from there.

**Comment by AadGlasbergen** [comment]
@StasDoskalenko I deleted the node-modules folder and the gradle cache. Same problem occurs.

Here is my build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "https://maven.google.com"
        }
        configurations.all {
            resolutionStrategy {
       force "com.google.android.gms:play-services-ads:11.6.0"
       force "com.google.android.gms:play-services-base:11.6.0"
       force "com.google.android.gms:play-services-gcm:11.6.0"
       force "com.google.android.gms:play-services-analytics:11.6.0"
       force "com.google.android.gms:play-services-location:11.6.0"
       force "com.google.android.gms:play-services-basement:11.6.0"
       force "com.google.android.gms:play-services-tagmanager:11.6.0"
       force 'com.google.firebase:firebase-core:11.6.0'
       force 'com.google.firebase:firebase-crash:11.6.0'
       force 'com.google.firebase:firebase-auth:11.6.0'
       force 'com.google.firebase:firebase-common:11.6.0'
       force 'com.google.firebase:firebase-config:11.6.0'
       force 'com.google.firebase:firebase-messaging:11.6.0'
   }
         //   resolutionStrategy.eachDependency { DependencyResolveDetails details ->
         //       def requested = details.requested
          //      if (requested.group == 'com.google.android.gms') {
          //          details.useVersion '11.6.0'
         //       }
          //      if (requested.group == 'com.google.firebase') {
          //          details.useVersion '11.6.0'
         //       }
          //  }
        }
    }
}

**Comment by StasDoskalenko** [comment]
@AadGlasbergen oh guys you've removed local maven rn android path. Your repositories section should look like:
```
repositories {
        mavenLocal()
        jcenter()
        maven { url "https://maven.google.com" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
configurations.all {
            resolutionStrategy {
       force "com.google.android.gms:play-services-ads:11.6.0"
       force "com.google.android.gms:play-services-base:11.6.0"
       force "com.google.android.gms:play-services-gcm:11.6.0"
       force "com.google.android.gms:play-services-analytics:11.6.0"
       force "com.google.android.gms:play-services-location:11.6.0"
       force "com.google.android.gms:play-services-basement:11.6.0"
       force "com.google.android.gms:play-services-tagmanager:11.6.0"
       force 'com.google.firebase:firebase-core:11.6.0'
       force 'com.google.firebase:firebase-crash:11.6.0'
       force 'com.google.firebase:firebase-auth:11.6.0'
       force 'com.google.firebase:firebase-common:11.6.0'
       force 'com.google.firebase:firebase-config:11.6.0'
       force 'com.google.firebase:firebase-messaging:11.6.0'
   }
    }
```

**Comment by AadGlasbergen** [comment]
@StasDoskalenko It is compiling. Thanks

**Comment by StasDoskalenko** [comment]
@AadGlasbergen glad to hear that! :)
