### ISSUE TITLE
calories in negative 

### ISSUE THREAD

**Issue by shaheem-khanzada** [StasDoskalenko/react-native-google-fit#46]
hey i am having a problem why calories are comming in negative example : -750

**Comment by EJohnF** [comment]
can you share your code? 
But the problem seems out-of-date already...

**Comment by adcuz** [comment]
Possibly related: https://github.com/StasDoskalenko/react-native-google-fit/issues/32

Related code BMR is being subtracted: https://github.com/StasDoskalenko/react-native-google-fit/blob/009ecbfb12cf59c20a9d33986551f58c1fd27c54/android/src/main/java/com/reactnative/googlefit/CalorieHistory.java#L165

Not sure what exactly the cause is, as I gave up trying to track it down.

**Comment by StasDoskalenko** [comment]
Looks like we're gathering basal metabolic rate averaged over a week

**Comment by dj-8891** [comment]
Any way we can get the total calories, without BMR reduced from it, i.e., the total calories as showed in the Google Fit app?

**Comment by StasDoskalenko** [comment]
@dj-8891 sure, I believe we can include some parameter there. Do you have some desirable API?

**Comment by dj-8891** [comment]
For the application I will be working on, I can work with only activity related calories as far as analytics is concerned but when it comes to displaying the details to the user, it would look good if my values match(or are close) with that shown in user's Google Fit app/account.

**Comment by dj-8891** [comment]
> @dj-8891 sure, I believe we can include some parameter there. Do you have some desirable API?

I was also wondering the same, that parameter can be used to trigger if we need to call CalorieHistory - getBasalAVG() or not.

**Comment by vineeth-accolite** [comment]
@dj-8891 if you are not extracting the basal are you getting the same value which is showing in Google fit App  in your app ?
 stepMap.putDouble("calorie", dp.getValue(field).asFloat() );

**Comment by dj-8891** [comment]
@vineeth-accolite There is no impact on the results for calories, no matter if we include the basal subtraction or not. The calories values are approx matching with that of Google Fit app apart from current day's calories value.

**Comment by vineeth-accolite** [comment]
@dj-8891 try passing end date as current datetime and you will get exact value as shown in the google fit app

**Comment by dj-8891** [comment]
@vineeth-accolite Stupid of me.
Thanks, this worked!!
