### ISSUE TITLE
Get steps from Google Account without having the Google Fit App

### ISSUE THREAD

**Issue by ghost** [StasDoskalenko/react-native-google-fit#49]
Heya,

I've been implementing your library and I've noticed you've got a start recording functionality.
I was wondering: if you don't have the Google Fit app itself and you _are_ recording using:
```
GoogleFit.startRecording((callback) => {
  // Process data from Google Fit Recording API (no google fit app needed)
});
```
Will this pull all the steps from the associated Google Account using the API? Or just the steps recorded from the local device from this moment forwards? From my testing it seems the latter is the most likely.

**Comment by asvine-p** [comment]
Hello, any update on this ? 
I have a similar issue. 
I noticed that my app was not getting any results when installing on a new device without googleFit.
I am only using GoogleFit.getDailyStepCountSamples without any location autorisation.

Here is the result I get:
![Capture d’écran 2020-02-07 à 11 34 41](https://user-images.githubusercontent.com/4700582/74023036-032b0480-499f-11ea-814a-b007806d42ec.png)

When I add 
```GoogleFit.startRecording(callback);```

my app is crashing:

![Screenshot_20200207-115121_United H Dev](https://user-images.githubusercontent.com/4700582/74023834-ded02780-49a0-11ea-8801-ccd4082c2472.jpg)

I don't see any infos about the GPS authorisation in the doc.
Is it mendatory ?

**Comment by Sarathphd** [comment]
Use this function
import { View, Text, PermissionsAndroid } from 'react-native'
const runTime = async() => {
        try {
            const granted = await PermissionsAndroid.request(
              PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
              {
                'title': 'ReactNativeCode Location Permission',
                'message': 'ReactNativeCode App needs access to your location '
              }
            )
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        
              alert("Location Permission Granted.");
            }
            else {
        
              alert("Location Permission Not Granted");
        
            }
          } catch (err) {
            console.warn(err)
          }      
    }
