### ISSUE TITLE
getDailyStepCountSamples not works in release mode

### ISSUE THREAD

**Issue by yavand** [StasDoskalenko/react-native-google-fit#50]
hi guys, i have a problem and this is when i work with rn-google-fit in develop mode (node localserver) i have no problem and every thing is working. but when i release my app and generate signedApk, google auth modal is open but nothing occur and app crashes.
why?
please help me, 
sorry for my bad english :(

**Comment by StasDoskalenko** [comment]
@yavand hey! I believe you should generate **RELEASE CERTIFICATE** from google documentation

**Comment by StasDoskalenko** [comment]
@yavand glad to hear that! You're welcome :)
