### ISSUE TITLE
Can this module work without having the Google Fit app installed and without internet connection?

### ISSUE THREAD

**Issue by marcoautiero** [StasDoskalenko/react-native-google-fit#53]
I would like to know if it's possible to use this module, getting step counts:
1) without having the Google Fit app installed
2) without having an internet connection on the device in use.

Thank you

**Comment by skwidz** [comment]
Im not sure about needing an internet connection but the library works without having googleFit installed.  One of my projects uses it this way. 


I don't think the library makes any network requests so I'm fairly confident it'll run without internet

**Comment by StasDoskalenko** [comment]
Actually, the library requires the internet connection for the initial setup.
