### ISSUE TITLE
GoogleFit.authorize() calls first onAuthorizeFailure and afterwards onAuthorize

### ISSUE THREAD

**Issue by sebbu** [StasDoskalenko/react-native-google-fit#56]
On a recent project I saw that GoogleFit.authorize() 
immediately calls onAuthorizeFailure and later on when the connection is established onAuthorize

I took a look to the implementation. I saw that it uses the deprecated GoogleApiClient. Furthermore events are added to call the JavaScript callback and you might end up with multiple callbacks.

The addOnConnectionFailedListener is the native method which fires too early.

It might be possible to check on the ConnectionResult in method onConnectionFailed(ConnectionResult result) to find a workaround.

But it would also be good to implement a real callback and not listen to the native events.

**Comment by pkyeck** [comment]
I'm having the same problem - was this "fixed" in any way or why did you close this issue?
