### ISSUE TITLE
startRecording working but ObserveSteps not working 

### ISSUE THREAD

**Issue by ramki1979** [StasDoskalenko/react-native-google-fit#58]
After Authorize, I am able to get daily steps count data using getDailyStepCountSamples, But not able to get real-time steps count with observeSteps.

When I call startRecording, the callback is invoked with steps recording & inside the callback I am calling observeSteps. 

```
Pedometer.startRecording(this.startAndroidStepRecording)
startAndroidStepRecording(type) {
    if (type != 'steps') return
    this.dispatch({ type: 'RH.Pedometer.Live.Callback', payload: { type } })
    Pedometer.observeSteps(this.observeStepsCallback)
  }
```

I have been observing LOGs from the Native code as well and I see no step count data received. I only see 

> RecordingApi: RecordingAPI - Connected
> StepCounter: Register Fitness Listener: DataType{com.google.step_count.delta[steps(i)]}
> StepCounter: Register Fitness Listener: DataType{com.google.step_count.cumulative[steps(i)]}
> StepCounter: SensorApi successfully added
> StepCounter: SensorApi successfully added

**Comment by StasDoskalenko** [comment]
@ramki1979 hi! Have you resolved your issue?

**Comment by ramki1979** [comment]
Currently its working, but time to time it stop all of a sudden with the above scenario.

**Comment by saudahmed** [comment]
@ramki1979 , can you share your sample code here like how to getDailyStepCountSamples.

I am always getting empty []

**Comment by Dhaval240420** [comment]
with this example, user can get all recorded steps, when user opens the app again.

GoogleFit.authorize(option)
.then((res) => {
	if(res.success == true){
		GoogleFit.startRecording((object) => {
			if(object.recording == true && object.type === "STEP_RECORDING”){
				GoogleFit.observeSteps((response) => {
					console.log(response)
				})
			}
		})
	}	
})

But if I want steps in a background event, then, according to google fit documentation I have to use sensor api, and in that library when I was checking for it, I found one file at android/src/main/Java/com/reactnative/googlefit/StepSensor.java, but does not have any documentation for that so please tell me, how to use that sensor api function.
