### ISSUE TITLE
getDailyStepCountSamples() callback is called multiple times and it slows down the app

### ISSUE THREAD

**Issue by marcoautiero** [StasDoskalenko/react-native-google-fit#63]
When `getDailyStepCountSamples()` is called I see that its callback is called multiple times; a simple `console.log()` inside of it is executed three or four times

```
GoogleFit.isEnabled(() => {
                    GoogleFit.startRecording((callback) => {
                        const options = {
                            startDate: "2017-01-01T00:00:17.971Z", // required ISO8601Timestamp
                            endDate: (new Date(Date.now() - (new Date()).getTimezoneOffset() * 60000)).toISOString() // required ISO8601Timestamp
                        };
                        
                        GoogleFit.getDailyStepCountSamples(options, (err, res) => {
                            if (err) {
                                throw err;
                            }
                            console.log("GETDAILYSTEPCOUNT")
                            return
                        });
                    });
                });
```

It terribly slows down the app, in particular if you have inside `getDailyStepCountSamples()` some redux actions

**Comment by marcoautiero** [comment]
@StasDoskalenko for example, I have in one of the screens of my app a switch that when is off calls this function

```

    _requestGoogleFitPermission = async () => {
        try {
            const granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
            )
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                GoogleFit.authorize();

                GoogleFit.onAuthorize(() => {

                    GoogleFit.startRecording((callback) => {
                        console.log("startRecording")
                    });
                });

                GoogleFit.isEnabled(() => {
                    console.log("isEnabled")

                    const options = {
                        startDate: "2017-01-01T00:00:17.971Z", // required ISO8601Timestamp
                        endDate: (new Date(Date.now() - (new Date()).getTimezoneOffset() * 60000)).toISOString() // required ISO8601Timestamp
                    };
                    
                    GoogleFit.getDailyStepCountSamples(options, (err, res) => {
                        if (err) {
                            throw err;
                        }
                        console.log(res)
                        return
                    });
                });
            }
        } catch (err) {
            Reactotron.log("problemi")
        }
    }
```

in this case I can see the string `startRecording` two times in my debugger

**Comment by amarnathsdr** [comment]
Hello,  :) i have exactly the same problem... Did you find any solution for that ?

**Comment by StasDoskalenko** [comment]
Guys I'm planning to create a good example app. Any suggestions?

**Comment by amarnathsdr** [comment]
Hello again. The problem I have is like I have a toggle who can connect and disconnect this step tracker. When I connect and disconnect I have no problem. but when I connect it back the startRecording is called like more than 10 times ... :'(

**Comment by darioduarte** [comment]
alguien tiene una solución? es como si la función se propagara .
A mi tambíen me imprime en consola muchas veces el resultado

navigation.addListener('focus', () => {
  getStepsGoogleFit();
});

function getStepsGoogleFit() {

    if (GoogleFit.isAuthorized) {
        const options = {
          startDate: "2017-01-01T00:00:17.971Z", // required ISO8601Timestamp
          endDate: new Date().toISOString() // required ISO8601Timestamp
      };

      GoogleFit.getDailyStepCountSamples(options).then((response) => {
           const data = response.find(element => element.source === 'com.google.android.gms:estimated_steps');
           console.log(response);
         }).catch(error => error)
    }
  }

**Comment by darioduarte** [comment]
just using the **unsubscribeListeners ()** method solves the problem.

navigation.addListener('focus', () => {
  getStepsGoogleFit();
});

navigation.addListener('blur', () => {
  GoogleFit.unsubscribeListeners();
});
