### ISSUE TITLE
the app on PlayStore is able to connect to fit

### ISSUE THREAD

**Issue by nguyentrung0904** [StasDoskalenko/react-native-google-fit#66]
My react native app is able to connect to google fit in release/debug mode (deploy directly to phone / through crashlytics )

But when I uploaded to to store and download from the phone, the box asking Allow/Deny does not appear.

Even stranger that if i downloaded the apk from console and install it directly it works.

**Comment by StasDoskalenko** [comment]
@nguyentrung0904 hey are you sure you have a release certificate for the app?

**Comment by nguyentrung0904** [comment]
I ran this:
`keytool -list -keystore my-release-key.keystore`
and get the SHA1 => create client key. 

Other parts of the app work fine including request for camera/sms...

**Comment by nguyentrung0904** [comment]
I guess I have to set up Consent Screen as well

**Comment by nguyentrung0904** [comment]
I dont add client_secret.json to the app. I think setting up client id on googleconsole is sufficicnet right?
My AndroidManifest.xml
`    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.READ_SMS" />
    <uses-permission android:name="android.permission.WRITE_SMS" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.FITNESS_LOCATION_READ" />
    <uses-permission android:name="android.permission.FITNESS_ACTIVITY_READ_WRITE" />
    <uses-permission android:name="android.permission.FITNESS_BODY_READ_WRITE" />
    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />`


I believe i used the correct release cert as the app works perfectly fine in appstore.

**Comment by nguyentrung0904** [comment]
Hi mate,

thanks for your support. I have resolved it by adding cert gen by google play store which is differed from my release cert to get ClientID and also update the AndroidManifest

**Comment by buddhishan** [comment]
@nguyentrung0904 I am experiencing the same issue. Can you explain the solution a little bit. Thanks in advance

**Comment by nguyentrung0904** [comment]
Hi, you have to go to GooglePlay Console and get the App Certificate and add that to https://console.cloud.google.com/apis to get the client ID. 

Please note that The Cert in the store is not the same as the release cert.
