### ISSUE TITLE
get activity types

### ISSUE THREAD

**Issue by tvansteelandt** [StasDoskalenko/react-native-google-fit#67]
Is it possible to get the type of activity with the distance sample?
I want to make a difference between e.g. a 5km walk, or a 10km run.

Thanks!

**Comment by EJohnF** [comment]
actually, there is. But it isn't well-documented feature. 
Check this file - https://github.com/StasDoskalenko/react-native-google-fit/blob/master/android/src/main/java/com/reactnative/googlefit/ActivityHistory.java

getActivitySamples - returns you all activities along with there name. 
Note - name actually is a number from this list
https://developers.google.com/fit/rest/v1/reference/activity-types

**Comment by StasDoskalenko** [comment]
added todo in project
https://github.com/StasDoskalenko/react-native-google-fit/projects/1
