### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dmitriys-lits** [StasDoskalenko/react-native-google-fit#68]
After updating the package to `0.7.0` in my project I see the error when `./gradlew assembleRelease`:

```
> Task :react-native-google-fit:compileDebugJavaWithJavac FAILED
/Users/dmitriisalenko/projects/xendera-enterprise/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java:173: error: cannot find symbol
        GoogleSignInAccount gsa = GoogleSignIn.getAccountForScopes(mReactContext, new Scope(Scopes.FITNESS_ACTIVITY_READ));
                                              ^
  symbol:   method getAccountForScopes(ReactContext,Scope)
  location: class GoogleSignIn
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-google-fit:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by dmitriys-lits** [comment]
@EJohnF do you know something about it? Would be grateful for investigation or help.

**Comment by EJohnF** [comment]
Have you changed anything in your code? 

Can you pls check 0.6.2 version or this commit - https://github.com/StasDoskalenko/react-native-google-fit/commit/a87757dceaef5e401ae5d1839a31d55db04c18e4

I would assume the problem with version of com.google.android.gms:play-services-fitness  lib

**Comment by StasDoskalenko** [comment]
@dmitriys-lits have you tried ```./gradlew clean``` ?

**Comment by StasDoskalenko** [comment]
@EJohnF ya I guess `com.google.android.gms.common.api.GoogleApi. getAccountForScopes ()` is available since 15 Google Play Services API

**Comment by dmitriys-lits** [comment]
Seems like really I had the problem with Google Play Services API version.

Everything is okay now, thank you all for help.
