### ISSUE TITLE
disconnect() function is not working okay

### ISSUE THREAD

**Issue by dmitriys-lits** [StasDoskalenko/react-native-google-fit#69]
After invoking `disconnect` method `isAuthorized` and `authorize` is not working correctly.

**HTC:**

1. Invoke `authorize`
2. Invoke `disconnect`
3. Invoke `authorize`

**Expected result:**

See android prompt with Google Account choosing.

**Actual result:**

Nothing happens because `isAuthorized` returns `true`

**Comment by StasDoskalenko** [comment]
@dmitriys-lits yeah this is a good point!
I'll merge it right now and publish, thanks!
