### ISSUE TITLE
isEnabled() returns false

### ISSUE THREAD

**Issue by MonteyMontey** [StasDoskalenko/react-native-google-fit#72]
I don't know which factors influence the isEnabled() result (and what it means exactly), can anyone give me a hint? I also can't find any documentation really besides the readme

**Comment by EJohnF** [comment]
did you grand a permission to read from google fit? 

there should be a pop-up which asks which google account to use and which data will be accessible for the app.


isEnable - check whether permissions granted or not. You can use it before 'authorize' call - to check, do you need to call 'authorize' or not.

**Comment by MonteyMontey** [comment]
yeah I got that pop-up, selected my google account and confirmed but isEnable() still returns false unfortunately

**Comment by EJohnF** [comment]
Pop-up with google account selection, and then grad permissions, right? 
Bcs for me it seems like a problem with correct installation (in google console not everything done well) - also had the same. Need to double check that you allowed Fitness API in google console for your App

**Comment by MonteyMontey** [comment]
mhh, I don't think that it's a problem with google console configuration because it got it working in a pure android application with the exact same configuration in the console.

**Comment by ScreamZ** [comment]
I don't think this is specially related to the library, the thing is the library work well for nominal scenario.  But this is not always the case and we should have some behavior that is:

1. Easy to understand & debug
2. Or even better be transparent.

**Comment by ilyafriedman** [comment]
Same here

**Comment by pdaw** [comment]
I had the same issue but in the end, I noticed, that the callback has two parameters - an error and a boolean response, so handling this should look like:

```
GoogleFit.isEnabled((error, isEnabled) => {
...
}
```

**Comment by amarnathsdr** [comment]
Hello, I wanted to know If you had some trouble with the isEnabled value. When I kill the app, or even the day+1, the value of isEnabled is back to false ... 
If you have any informations about it, it would be great !!!!

**Comment by StasDoskalenko** [comment]
@amarnathsdr could you please try with the latest version?
And try checkIsAuthorized() method - it returns a promise
