### ISSUE TITLE
disconnect() is not a function

### ISSUE THREAD

**Issue by nithincharly1991** [StasDoskalenko/react-native-google-fit#75]
when trying to call GoogleFit.disconnect(), it says _reactNativeGoogleFit.default.disconnect is not a function

**Comment by EJohnF** [comment]
do you use the last version of the lib? 
Can you pls share your code?

**Comment by nithincharly1991** [comment]
yeah, i have upgraded to 0.7.1. Every other functionalities works as expected. I tried to call  GoogleFit.disconnect(); in another function.

**Comment by EJohnF** [comment]
I'd expect that there is a problem with correct import. But in this case, it's strange that others are work.
Try to `console.log(GoogleFit)` - to see what's the object there.

**Comment by nithincharly1991** [comment]
It was my bad. I have done ./gradlew clean, uninstalled and rebuild the app. Now it works fine
