### ISSUE TITLE
Can we just omit this

### ISSUE THREAD

**Issue by ScreamZ** [StasDoskalenko/react-native-google-fit#76]
Hi,

I think this behavior is strange. If we call authorize and this is already authorized we simply return anything.

We must resolve or reject callback in order to maintain a consistent state… Or the program will wait indefinitely for a response.

https://github.com/StasDoskalenko/react-native-google-fit/blob/43201fa8dffdbe0344b23f3745ca49701abfe963/android/src/main/java/com/reactnative/googlefit/GoogleFitModule.java#L78

**Comment by dmitriys-lits** [comment]
I'll take a look at this problem on weekend.

**Comment by ScreamZ** [comment]
@dmitriys-lits Any news on this ?

**Comment by dmitriys-lits** [comment]
@ScreamZ have a lack of time to do it now 😞

**Comment by jay-jlm** [comment]
@ScreamZ  @dmitriys-lits 
Wouldn't just exposing the isAuthorized() method to JS land work at least as a temporary solution?
This way the corners cases can be dealt with on the JS side.
It literally took me 30 seconds to do code it  😜 , please let me know if it looks correct and if I should submit a PR. Thanks!

**Comment by StasDoskalenko** [comment]
@jay-jlm @ScreamZ Hey Guys could you please re-test with the latest version?
authorize() now returns a Promise with backward capability for event listeners.
And JS Class now has `isAuthorized` flag along with `checkIsAuthorized `method to verify native status.
