### ISSUE TITLE
How to get hear rate and blood pressure ?

### ISSUE THREAD

**Issue by damnnkst** [StasDoskalenko/react-native-google-fit#80]
I can't find function for get hear rate and blood pressure ? Can you share this function with me ?

**Comment by luisrivas** [comment]
@damnnkst Actually doesn't exist a method to retrive that info on this library

**Comment by StasDoskalenko** [comment]
@damnnkst @luisrivas added a TODO card in project https://github.com/StasDoskalenko/react-native-google-fit/projects/1
