### ISSUE TITLE
can't we call .authorize() multiple times?

### ISSUE THREAD

**Issue by buddhishan** [StasDoskalenko/react-native-google-fit#81]
I want to update the step data every 120 seconds. Thus, I am calling .authorize() with a timer. But after the first successful time, I get neither .onAuthorize() nor .onAuthorizeFailure() called. Looking forward for a kind explanation. Thanks!

**Comment by vinayan3** [comment]
I've ran into this as well. If you read the Java code for `authorize`
```
    @ReactMethod
    public void authorize() {
        final Activity activity = getCurrentActivity();

        if (mGoogleFitManager == null) {
            mGoogleFitManager = new GoogleFitManager(mReactContext, activity);
        }

        if (mGoogleFitManager.isAuthorized()) {
            return;
        }
        mGoogleFitManager.authorize();
    }
``` 

If it's already authorized it will directly return... which means you don't get a call back to `onAuthorize` or `onAuthorizeFailure`.

The work around that I've found is to call  from Javascript
``
RNGoogleFit.isEnabled((msg, isEnabled) => { 

  if(isEnabled) { 
    // yay
  }  else {
   /// do the RNGoogleFit.authorize() stuff you'll get call backs.
 } 
```

**Comment by buddhishan** [comment]
Thank you. It was really helpful
