### ISSUE TITLE
acccount info of a granted User

### ISSUE THREAD

**Issue by VijayDinanath** [StasDoskalenko/react-native-google-fit#82]
How will I get the account info for which I have given the google fit permission ?

**Comment by StasDoskalenko** [comment]
@VijayDinanath hey! Are you interested in email? Please reopen it if you still need a help

**Comment by im-aditya** [comment]
It would be great if we can get email info.

**Comment by paddy57** [comment]
how can we access user information who is authorized?

**Comment by AylanBoscarino** [comment]
To have the option of getting the email of the current user would be of great use.

**Comment by akiladevinda** [comment]
@StasDoskalenko  Thanks for this awesome library ! Can we get user email which provided to google fit ?

**Comment by antoinedelp** [comment]
+ 1 for the email info! It would be of great help
