### ISSUE TITLE
Authorization - Cancel is there a limit to logins?

### ISSUE THREAD

**Issue by jerinjohnk** [StasDoskalenko/react-native-google-fit#89]
I was using this library initially but after a few days of usage(steps, recording etc) it started throwing error Authorization canceled.
Earlier I switched to a new google account and created a new `client_id.json` once more when I had encountered this error and it started working again.

Now while creating OAuth account I noticed this warning
> OAuth is limited to 100 sensitive scope logins until the OAuth consent screen is published. This may require a verification process that can take several days.

So is the error caused due to this 100 login limit?
Does google consider same email id authorization as a login event?
I had already applied for OAuth Consent Screen verification. 
But its stuck at
`Your consent screen is being verified. This may take up to several days. Your last approved consent screen is still in use.`

Anyone else faced this issue?

**Comment by StasDoskalenko** [comment]
Hmm very strange. Are you still facing this issue?

**Comment by jerinjohnk** [comment]
Since it wasn't working at that time, I regenerated a new keystore file and started using that instead.
