### ISSUE TITLE
GoogleFit.authorize() function and the client_secrets.json Saga.

### ISSUE THREAD

**Issue by salles-sandro** [StasDoskalenko/react-native-google-fit#90]
Just to let anyone else that, like me, spent lots of precious time struggling with the authorize method and the error below:

> "ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{4460f51: android.os.BinderProxy@6992179}, message=null}"

After searching the entire internet i found a comment mentioning that the **client_secrets.json** file generated after the https://developers.google.com/fit/android/get-api-key  process should be store exactly at this location:

**app/android/app/src/main/resources/client_secrets.json**

Then... at least for me, things are finally working.

@StasDoskalenko ... if it's the case, if this instruction is really valid and not only for my case it would be nice to have that documented :-)

**Comment by StasDoskalenko** [comment]
@salles-sandro thanks! Readme now restructured https://github.com/StasDoskalenko/react-native-google-fit/blob/master/docs/INSTALLATION.md#just-in-case-sign_in_required-error-thanks-salles-sandro-

**Comment by andersonveiga** [comment]
Still doesnt work... I get the same error. @salles-sandro can you share where you found that comment that this file is needed? Ive tried many things to make this work, but without success

**Comment by andersonveiga** [comment]
Nevermind, turns out I it was a problem of certificates
