### ISSUE TITLE
GoogleFit.authorize() does not return if permissions are denied

### ISSUE THREAD

**Issue by dj-8891** [StasDoskalenko/react-native-google-fit#91]
When GoogleFit.authorize() is called, the account selection page opens up, if you do not select any account and instead press back, the app goes into a sort of wait state for a long time. Same happens if you do select an account and on the permissions page, you deny the permissions. Once the app goes into this so called wait state, the device back button also stops working in the app. Is there any way to check if the user has denied permission or have pressed back button instead of selecting any account so that some other action can be triggered instead of going into the wait state?

**Comment by StasDoskalenko** [comment]
@dj-8891 hey could you please recheck with the latest version?

**Comment by dj-8891** [comment]
Tried with 0.9.5, but getting this error while building
~myProject~\node_modules\react-native-google-fit\android\src\main\java\com\reactnative\googlefit\GoogleFitModule.java:91: error: ';' expected
        boolean isAuthorized = false
                                    ^
~myProject~\node_modules\react-native-google-fit\android\src\main\java\com\reactnative\googlefit\GoogleFitModule.java:93: error: ';' expected
            isAuthorized = true

After adding the ';' at required places, got this error
~myProject~\node_modules\react-native-google-fit\android\src\main\java\com\reactnative\googlefit\GoogleFitModule.java:95: error: cannot find symbol
        WritableMap map = Arguments.createMap();
        ^
  symbol:   class WritableMap
  location: class GoogleFitModule

After adding the code to resolve this, encountered this:
~myProject~\node_modules\react-native-google-fit\android\src\main\java\com\reactnative\googlefit\GoogleFitModule.java:98: error: missing return statement
    }

I tried to modify the code to resolve these errors(did the required changes in GoogleFitModule.java - isAuthorized() method) but couldn't get rid of the last one as it might require modifying the calling and return code of the function and hence I didn't touch it.

I also tried commenting the function(stupid, I know) and ran the app and the functionality to handle permission denied and back button press scenario seems to be working but after the first request for permission is denied, the app doesn't go for asking permission the next. I think this is related to me commenting the troubling method mentioned above.

In my opinion, once the issue with isAuthorized() method is resolved, the new functionality implemented by you to handle the given scenarios should work fine. I will also try correcting the issue once I get time.

**Comment by StasDoskalenko** [comment]
@dj-8891 thank you for the report!
I just published version 0.9.6, could you try it? Thanks!

**Comment by dj-8891** [comment]
I tried but got stuck with this in 0.9.7 version:
\node_modules\react-native-google-fit\android\src\main\java\com\reactnative\googlefit\GoogleFitModule.java:62: error: cannot find symbol
        super.onHostResume();
             ^
  symbol: method onHostResume()
D:\React Native\googleApiPOC\node_modules\react-native-google-fit\android\src\main\java\com\reactnative\googlefit\GoogleFitModule.java:70: error: cannot find symbol
        super.onHostPause();
             ^
  symbol: method onHostPause()

Not able to figure out why though.

**Comment by StasDoskalenko** [comment]
@dj-8891 0.98 :D

**Comment by StasDoskalenko** [comment]
@dj-8891 check the example app

**Comment by dj-8891** [comment]
I tried with 0.9.9 and things seems to be working smooth now.
Thanks for the prompt help and quick replies!! :)

**Comment by shrikanttapkeer07** [comment]
> @dj-8891 check the example app

Example app does not even start when cloned and installed dependencies

**Comment by gigby** [comment]
@StasDoskalenko I faced this bug on 0.16.1 version.
