### ISSUE TITLE
Authorize with promise doesn't work

### ISSUE THREAD

**Issue by gaykov** [StasDoskalenko/react-native-google-fit#93]
Hi @StasDoskalenko, thanks for supporting this library! I've found it really helpful in my project.

Unfortunately, the current version of the `authorize` function is not consistent (sometimes it returns promise, sometimes object) and loses the promise (for me `.then` was never called after the successful authorization.

The fastest workaround I've found is something with callbacks, like the following snippet (I just modified the existent code):

```
authorize = async (onSuccess, onError) => {
    const successResponse = { success: true };

    try {
      await this.checkIsAuthorized();
      if (this.isAuthorized) {
        onSuccess(successResponse);
      }

      this.onAuthorize(() => {
        this.isAuthorized = true;
        onSuccess(successResponse);
      });
      this.onAuthorizeFailure(error => {
        this.isAuthorized = false;
        onError({ success: false, error });
      });

      googleFit.authorize();
    } catch (err) {
      return onError({ success: false });
    }
  };
```

which works and the callback is called after the successfull authorization.

Also, I'd love to contribute to the project now, because there are some features that I want to use in my project that's not currently exist here. A few of them:

1. Dynamic Permissions (users will be afraid that we ask blood pressure if we don't need it).
2. Ability to save workouts (I've seen that there's is a PR open that requires some additional work).

So could you please let me know if you're working on any of this tasks so we wouldn't do the same work twice :)

**Comment by StasDoskalenko** [comment]
@gaykov thank you for the support! yeah I'll double check this function

**Comment by StasDoskalenko** [comment]
@gaykov hey! I've fixed it. Now it works as expected. Also I've added an example app

**Comment by gaykov** [comment]
@StasDoskalenko tested it and can confirm that it works, thanks!
