### ISSUE TITLE
How to log out from google fit account I have connected ?

### ISSUE THREAD

**Issue by nguyenson2012** [StasDoskalenko/react-native-google-fit#97]

**Comment by mahendra13** [comment]
I am looking for the solution, how to logout from the google account once login.

**Comment by GabrieIIeaI** [comment]
You need the Google Fit app to remove the google account connected.

Profile > Settings > Manage connected apps

There is the place to you remove the apps with permissions on Google Fit.

**Comment by aboveyunhai** [comment]
`GoogleFit.disconnect();`
